services:

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nextjs
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/app
      - /app/node_modules
    env_file: .env.docker
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    env_file: .env.docker
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
      
volumes:
  postgres_db: