
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/User'
export type * from './models/Session'
export type * from './models/Book'
export type * from './models/Music'
export type * from './models/Magazine'
export type * from './models/Artwork'
export type * from './models/Museum'
export type * from './models/Gallery'
export type * from './models/Image'
export type * from './models/Photograph'
export type * from './models/Idea'
export type * from './models/Quote'
export type * from './models/New'
export type * from './commonInputTypes'