
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CustomCollection` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model CustomCollection
 * 
 */
export type CustomCollectionModel = runtime.Types.Result.DefaultSelection<Prisma.$CustomCollectionPayload>

export type AggregateCustomCollection = {
  _count: CustomCollectionCountAggregateOutputType | null
  _min: CustomCollectionMinAggregateOutputType | null
  _max: CustomCollectionMaxAggregateOutputType | null
}

export type CustomCollectionMinAggregateOutputType = {
  id: string | null
  userId: string | null
  title: string | null
  description: string | null
  reason: string | null
  imageUrl: string | null
  createdAt: Date | null
}

export type CustomCollectionMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  title: string | null
  description: string | null
  reason: string | null
  imageUrl: string | null
  createdAt: Date | null
}

export type CustomCollectionCountAggregateOutputType = {
  id: number
  userId: number
  title: number
  description: number
  reason: number
  imageUrl: number
  createdAt: number
  _all: number
}


export type CustomCollectionMinAggregateInputType = {
  id?: true
  userId?: true
  title?: true
  description?: true
  reason?: true
  imageUrl?: true
  createdAt?: true
}

export type CustomCollectionMaxAggregateInputType = {
  id?: true
  userId?: true
  title?: true
  description?: true
  reason?: true
  imageUrl?: true
  createdAt?: true
}

export type CustomCollectionCountAggregateInputType = {
  id?: true
  userId?: true
  title?: true
  description?: true
  reason?: true
  imageUrl?: true
  createdAt?: true
  _all?: true
}

export type CustomCollectionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CustomCollection to aggregate.
   */
  where?: Prisma.CustomCollectionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CustomCollections to fetch.
   */
  orderBy?: Prisma.CustomCollectionOrderByWithRelationInput | Prisma.CustomCollectionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CustomCollectionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CustomCollections from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CustomCollections.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CustomCollections
  **/
  _count?: true | CustomCollectionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CustomCollectionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CustomCollectionMaxAggregateInputType
}

export type GetCustomCollectionAggregateType<T extends CustomCollectionAggregateArgs> = {
      [P in keyof T & keyof AggregateCustomCollection]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCustomCollection[P]>
    : Prisma.GetScalarType<T[P], AggregateCustomCollection[P]>
}




export type CustomCollectionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CustomCollectionWhereInput
  orderBy?: Prisma.CustomCollectionOrderByWithAggregationInput | Prisma.CustomCollectionOrderByWithAggregationInput[]
  by: Prisma.CustomCollectionScalarFieldEnum[] | Prisma.CustomCollectionScalarFieldEnum
  having?: Prisma.CustomCollectionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CustomCollectionCountAggregateInputType | true
  _min?: CustomCollectionMinAggregateInputType
  _max?: CustomCollectionMaxAggregateInputType
}

export type CustomCollectionGroupByOutputType = {
  id: string
  userId: string
  title: string
  description: string
  reason: string
  imageUrl: string | null
  createdAt: Date
  _count: CustomCollectionCountAggregateOutputType | null
  _min: CustomCollectionMinAggregateOutputType | null
  _max: CustomCollectionMaxAggregateOutputType | null
}

export type GetCustomCollectionGroupByPayload<T extends CustomCollectionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CustomCollectionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CustomCollectionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CustomCollectionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CustomCollectionGroupByOutputType[P]>
      }
    >
  >



export type CustomCollectionWhereInput = {
  AND?: Prisma.CustomCollectionWhereInput | Prisma.CustomCollectionWhereInput[]
  OR?: Prisma.CustomCollectionWhereInput[]
  NOT?: Prisma.CustomCollectionWhereInput | Prisma.CustomCollectionWhereInput[]
  id?: Prisma.StringFilter<"CustomCollection"> | string
  userId?: Prisma.StringFilter<"CustomCollection"> | string
  title?: Prisma.StringFilter<"CustomCollection"> | string
  description?: Prisma.StringFilter<"CustomCollection"> | string
  reason?: Prisma.StringFilter<"CustomCollection"> | string
  imageUrl?: Prisma.StringNullableFilter<"CustomCollection"> | string | null
  createdAt?: Prisma.DateTimeFilter<"CustomCollection"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  objects?: Prisma.CustomCollectionObjectListRelationFilter
}

export type CustomCollectionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  objects?: Prisma.CustomCollectionObjectOrderByRelationAggregateInput
}

export type CustomCollectionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.CustomCollectionWhereInput | Prisma.CustomCollectionWhereInput[]
  OR?: Prisma.CustomCollectionWhereInput[]
  NOT?: Prisma.CustomCollectionWhereInput | Prisma.CustomCollectionWhereInput[]
  userId?: Prisma.StringFilter<"CustomCollection"> | string
  title?: Prisma.StringFilter<"CustomCollection"> | string
  description?: Prisma.StringFilter<"CustomCollection"> | string
  reason?: Prisma.StringFilter<"CustomCollection"> | string
  imageUrl?: Prisma.StringNullableFilter<"CustomCollection"> | string | null
  createdAt?: Prisma.DateTimeFilter<"CustomCollection"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  objects?: Prisma.CustomCollectionObjectListRelationFilter
}, "id">

export type CustomCollectionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.CustomCollectionCountOrderByAggregateInput
  _max?: Prisma.CustomCollectionMaxOrderByAggregateInput
  _min?: Prisma.CustomCollectionMinOrderByAggregateInput
}

export type CustomCollectionScalarWhereWithAggregatesInput = {
  AND?: Prisma.CustomCollectionScalarWhereWithAggregatesInput | Prisma.CustomCollectionScalarWhereWithAggregatesInput[]
  OR?: Prisma.CustomCollectionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CustomCollectionScalarWhereWithAggregatesInput | Prisma.CustomCollectionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CustomCollection"> | string
  userId?: Prisma.StringWithAggregatesFilter<"CustomCollection"> | string
  title?: Prisma.StringWithAggregatesFilter<"CustomCollection"> | string
  description?: Prisma.StringWithAggregatesFilter<"CustomCollection"> | string
  reason?: Prisma.StringWithAggregatesFilter<"CustomCollection"> | string
  imageUrl?: Prisma.StringNullableWithAggregatesFilter<"CustomCollection"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CustomCollection"> | Date | string
}

export type CustomCollectionCreateInput = {
  id?: string
  title: string
  description: string
  reason: string
  imageUrl?: string | null
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutCustomCollectionsInput
  objects?: Prisma.CustomCollectionObjectCreateNestedManyWithoutCollectionInput
}

export type CustomCollectionUncheckedCreateInput = {
  id?: string
  userId: string
  title: string
  description: string
  reason: string
  imageUrl?: string | null
  createdAt?: Date | string
  objects?: Prisma.CustomCollectionObjectUncheckedCreateNestedManyWithoutCollectionInput
}

export type CustomCollectionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutCustomCollectionsNestedInput
  objects?: Prisma.CustomCollectionObjectUpdateManyWithoutCollectionNestedInput
}

export type CustomCollectionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  objects?: Prisma.CustomCollectionObjectUncheckedUpdateManyWithoutCollectionNestedInput
}

export type CustomCollectionCreateManyInput = {
  id?: string
  userId: string
  title: string
  description: string
  reason: string
  imageUrl?: string | null
  createdAt?: Date | string
}

export type CustomCollectionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CustomCollectionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CustomCollectionListRelationFilter = {
  every?: Prisma.CustomCollectionWhereInput
  some?: Prisma.CustomCollectionWhereInput
  none?: Prisma.CustomCollectionWhereInput
}

export type CustomCollectionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CustomCollectionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CustomCollectionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CustomCollectionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CustomCollectionScalarRelationFilter = {
  is?: Prisma.CustomCollectionWhereInput
  isNot?: Prisma.CustomCollectionWhereInput
}

export type CustomCollectionCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.CustomCollectionCreateWithoutUserInput, Prisma.CustomCollectionUncheckedCreateWithoutUserInput> | Prisma.CustomCollectionCreateWithoutUserInput[] | Prisma.CustomCollectionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CustomCollectionCreateOrConnectWithoutUserInput | Prisma.CustomCollectionCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.CustomCollectionCreateManyUserInputEnvelope
  connect?: Prisma.CustomCollectionWhereUniqueInput | Prisma.CustomCollectionWhereUniqueInput[]
}

export type CustomCollectionUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.CustomCollectionCreateWithoutUserInput, Prisma.CustomCollectionUncheckedCreateWithoutUserInput> | Prisma.CustomCollectionCreateWithoutUserInput[] | Prisma.CustomCollectionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CustomCollectionCreateOrConnectWithoutUserInput | Prisma.CustomCollectionCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.CustomCollectionCreateManyUserInputEnvelope
  connect?: Prisma.CustomCollectionWhereUniqueInput | Prisma.CustomCollectionWhereUniqueInput[]
}

export type CustomCollectionUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.CustomCollectionCreateWithoutUserInput, Prisma.CustomCollectionUncheckedCreateWithoutUserInput> | Prisma.CustomCollectionCreateWithoutUserInput[] | Prisma.CustomCollectionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CustomCollectionCreateOrConnectWithoutUserInput | Prisma.CustomCollectionCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.CustomCollectionUpsertWithWhereUniqueWithoutUserInput | Prisma.CustomCollectionUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.CustomCollectionCreateManyUserInputEnvelope
  set?: Prisma.CustomCollectionWhereUniqueInput | Prisma.CustomCollectionWhereUniqueInput[]
  disconnect?: Prisma.CustomCollectionWhereUniqueInput | Prisma.CustomCollectionWhereUniqueInput[]
  delete?: Prisma.CustomCollectionWhereUniqueInput | Prisma.CustomCollectionWhereUniqueInput[]
  connect?: Prisma.CustomCollectionWhereUniqueInput | Prisma.CustomCollectionWhereUniqueInput[]
  update?: Prisma.CustomCollectionUpdateWithWhereUniqueWithoutUserInput | Prisma.CustomCollectionUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.CustomCollectionUpdateManyWithWhereWithoutUserInput | Prisma.CustomCollectionUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.CustomCollectionScalarWhereInput | Prisma.CustomCollectionScalarWhereInput[]
}

export type CustomCollectionUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.CustomCollectionCreateWithoutUserInput, Prisma.CustomCollectionUncheckedCreateWithoutUserInput> | Prisma.CustomCollectionCreateWithoutUserInput[] | Prisma.CustomCollectionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CustomCollectionCreateOrConnectWithoutUserInput | Prisma.CustomCollectionCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.CustomCollectionUpsertWithWhereUniqueWithoutUserInput | Prisma.CustomCollectionUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.CustomCollectionCreateManyUserInputEnvelope
  set?: Prisma.CustomCollectionWhereUniqueInput | Prisma.CustomCollectionWhereUniqueInput[]
  disconnect?: Prisma.CustomCollectionWhereUniqueInput | Prisma.CustomCollectionWhereUniqueInput[]
  delete?: Prisma.CustomCollectionWhereUniqueInput | Prisma.CustomCollectionWhereUniqueInput[]
  connect?: Prisma.CustomCollectionWhereUniqueInput | Prisma.CustomCollectionWhereUniqueInput[]
  update?: Prisma.CustomCollectionUpdateWithWhereUniqueWithoutUserInput | Prisma.CustomCollectionUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.CustomCollectionUpdateManyWithWhereWithoutUserInput | Prisma.CustomCollectionUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.CustomCollectionScalarWhereInput | Prisma.CustomCollectionScalarWhereInput[]
}

export type CustomCollectionCreateNestedOneWithoutObjectsInput = {
  create?: Prisma.XOR<Prisma.CustomCollectionCreateWithoutObjectsInput, Prisma.CustomCollectionUncheckedCreateWithoutObjectsInput>
  connectOrCreate?: Prisma.CustomCollectionCreateOrConnectWithoutObjectsInput
  connect?: Prisma.CustomCollectionWhereUniqueInput
}

export type CustomCollectionUpdateOneRequiredWithoutObjectsNestedInput = {
  create?: Prisma.XOR<Prisma.CustomCollectionCreateWithoutObjectsInput, Prisma.CustomCollectionUncheckedCreateWithoutObjectsInput>
  connectOrCreate?: Prisma.CustomCollectionCreateOrConnectWithoutObjectsInput
  upsert?: Prisma.CustomCollectionUpsertWithoutObjectsInput
  connect?: Prisma.CustomCollectionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CustomCollectionUpdateToOneWithWhereWithoutObjectsInput, Prisma.CustomCollectionUpdateWithoutObjectsInput>, Prisma.CustomCollectionUncheckedUpdateWithoutObjectsInput>
}

export type CustomCollectionCreateWithoutUserInput = {
  id?: string
  title: string
  description: string
  reason: string
  imageUrl?: string | null
  createdAt?: Date | string
  objects?: Prisma.CustomCollectionObjectCreateNestedManyWithoutCollectionInput
}

export type CustomCollectionUncheckedCreateWithoutUserInput = {
  id?: string
  title: string
  description: string
  reason: string
  imageUrl?: string | null
  createdAt?: Date | string
  objects?: Prisma.CustomCollectionObjectUncheckedCreateNestedManyWithoutCollectionInput
}

export type CustomCollectionCreateOrConnectWithoutUserInput = {
  where: Prisma.CustomCollectionWhereUniqueInput
  create: Prisma.XOR<Prisma.CustomCollectionCreateWithoutUserInput, Prisma.CustomCollectionUncheckedCreateWithoutUserInput>
}

export type CustomCollectionCreateManyUserInputEnvelope = {
  data: Prisma.CustomCollectionCreateManyUserInput | Prisma.CustomCollectionCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type CustomCollectionUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.CustomCollectionWhereUniqueInput
  update: Prisma.XOR<Prisma.CustomCollectionUpdateWithoutUserInput, Prisma.CustomCollectionUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.CustomCollectionCreateWithoutUserInput, Prisma.CustomCollectionUncheckedCreateWithoutUserInput>
}

export type CustomCollectionUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.CustomCollectionWhereUniqueInput
  data: Prisma.XOR<Prisma.CustomCollectionUpdateWithoutUserInput, Prisma.CustomCollectionUncheckedUpdateWithoutUserInput>
}

export type CustomCollectionUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.CustomCollectionScalarWhereInput
  data: Prisma.XOR<Prisma.CustomCollectionUpdateManyMutationInput, Prisma.CustomCollectionUncheckedUpdateManyWithoutUserInput>
}

export type CustomCollectionScalarWhereInput = {
  AND?: Prisma.CustomCollectionScalarWhereInput | Prisma.CustomCollectionScalarWhereInput[]
  OR?: Prisma.CustomCollectionScalarWhereInput[]
  NOT?: Prisma.CustomCollectionScalarWhereInput | Prisma.CustomCollectionScalarWhereInput[]
  id?: Prisma.StringFilter<"CustomCollection"> | string
  userId?: Prisma.StringFilter<"CustomCollection"> | string
  title?: Prisma.StringFilter<"CustomCollection"> | string
  description?: Prisma.StringFilter<"CustomCollection"> | string
  reason?: Prisma.StringFilter<"CustomCollection"> | string
  imageUrl?: Prisma.StringNullableFilter<"CustomCollection"> | string | null
  createdAt?: Prisma.DateTimeFilter<"CustomCollection"> | Date | string
}

export type CustomCollectionCreateWithoutObjectsInput = {
  id?: string
  title: string
  description: string
  reason: string
  imageUrl?: string | null
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutCustomCollectionsInput
}

export type CustomCollectionUncheckedCreateWithoutObjectsInput = {
  id?: string
  userId: string
  title: string
  description: string
  reason: string
  imageUrl?: string | null
  createdAt?: Date | string
}

export type CustomCollectionCreateOrConnectWithoutObjectsInput = {
  where: Prisma.CustomCollectionWhereUniqueInput
  create: Prisma.XOR<Prisma.CustomCollectionCreateWithoutObjectsInput, Prisma.CustomCollectionUncheckedCreateWithoutObjectsInput>
}

export type CustomCollectionUpsertWithoutObjectsInput = {
  update: Prisma.XOR<Prisma.CustomCollectionUpdateWithoutObjectsInput, Prisma.CustomCollectionUncheckedUpdateWithoutObjectsInput>
  create: Prisma.XOR<Prisma.CustomCollectionCreateWithoutObjectsInput, Prisma.CustomCollectionUncheckedCreateWithoutObjectsInput>
  where?: Prisma.CustomCollectionWhereInput
}

export type CustomCollectionUpdateToOneWithWhereWithoutObjectsInput = {
  where?: Prisma.CustomCollectionWhereInput
  data: Prisma.XOR<Prisma.CustomCollectionUpdateWithoutObjectsInput, Prisma.CustomCollectionUncheckedUpdateWithoutObjectsInput>
}

export type CustomCollectionUpdateWithoutObjectsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutCustomCollectionsNestedInput
}

export type CustomCollectionUncheckedUpdateWithoutObjectsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CustomCollectionCreateManyUserInput = {
  id?: string
  title: string
  description: string
  reason: string
  imageUrl?: string | null
  createdAt?: Date | string
}

export type CustomCollectionUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  objects?: Prisma.CustomCollectionObjectUpdateManyWithoutCollectionNestedInput
}

export type CustomCollectionUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  objects?: Prisma.CustomCollectionObjectUncheckedUpdateManyWithoutCollectionNestedInput
}

export type CustomCollectionUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type CustomCollectionCountOutputType
 */

export type CustomCollectionCountOutputType = {
  objects: number
}

export type CustomCollectionCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  objects?: boolean | CustomCollectionCountOutputTypeCountObjectsArgs
}

/**
 * CustomCollectionCountOutputType without action
 */
export type CustomCollectionCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomCollectionCountOutputType
   */
  select?: Prisma.CustomCollectionCountOutputTypeSelect<ExtArgs> | null
}

/**
 * CustomCollectionCountOutputType without action
 */
export type CustomCollectionCountOutputTypeCountObjectsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CustomCollectionObjectWhereInput
}


export type CustomCollectionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  title?: boolean
  description?: boolean
  reason?: boolean
  imageUrl?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  objects?: boolean | Prisma.CustomCollection$objectsArgs<ExtArgs>
  _count?: boolean | Prisma.CustomCollectionCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["customCollection"]>

export type CustomCollectionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  title?: boolean
  description?: boolean
  reason?: boolean
  imageUrl?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["customCollection"]>

export type CustomCollectionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  title?: boolean
  description?: boolean
  reason?: boolean
  imageUrl?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["customCollection"]>

export type CustomCollectionSelectScalar = {
  id?: boolean
  userId?: boolean
  title?: boolean
  description?: boolean
  reason?: boolean
  imageUrl?: boolean
  createdAt?: boolean
}

export type CustomCollectionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "title" | "description" | "reason" | "imageUrl" | "createdAt", ExtArgs["result"]["customCollection"]>
export type CustomCollectionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  objects?: boolean | Prisma.CustomCollection$objectsArgs<ExtArgs>
  _count?: boolean | Prisma.CustomCollectionCountOutputTypeDefaultArgs<ExtArgs>
}
export type CustomCollectionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type CustomCollectionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $CustomCollectionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CustomCollection"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    objects: Prisma.$CustomCollectionObjectPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    title: string
    description: string
    reason: string
    imageUrl: string | null
    createdAt: Date
  }, ExtArgs["result"]["customCollection"]>
  composites: {}
}

export type CustomCollectionGetPayload<S extends boolean | null | undefined | CustomCollectionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CustomCollectionPayload, S>

export type CustomCollectionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CustomCollectionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CustomCollectionCountAggregateInputType | true
  }

export interface CustomCollectionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CustomCollection'], meta: { name: 'CustomCollection' } }
  /**
   * Find zero or one CustomCollection that matches the filter.
   * @param {CustomCollectionFindUniqueArgs} args - Arguments to find a CustomCollection
   * @example
   * // Get one CustomCollection
   * const customCollection = await prisma.customCollection.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CustomCollectionFindUniqueArgs>(args: Prisma.SelectSubset<T, CustomCollectionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CustomCollectionClient<runtime.Types.Result.GetResult<Prisma.$CustomCollectionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CustomCollection that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CustomCollectionFindUniqueOrThrowArgs} args - Arguments to find a CustomCollection
   * @example
   * // Get one CustomCollection
   * const customCollection = await prisma.customCollection.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CustomCollectionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CustomCollectionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CustomCollectionClient<runtime.Types.Result.GetResult<Prisma.$CustomCollectionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CustomCollection that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomCollectionFindFirstArgs} args - Arguments to find a CustomCollection
   * @example
   * // Get one CustomCollection
   * const customCollection = await prisma.customCollection.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CustomCollectionFindFirstArgs>(args?: Prisma.SelectSubset<T, CustomCollectionFindFirstArgs<ExtArgs>>): Prisma.Prisma__CustomCollectionClient<runtime.Types.Result.GetResult<Prisma.$CustomCollectionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CustomCollection that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomCollectionFindFirstOrThrowArgs} args - Arguments to find a CustomCollection
   * @example
   * // Get one CustomCollection
   * const customCollection = await prisma.customCollection.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CustomCollectionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CustomCollectionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CustomCollectionClient<runtime.Types.Result.GetResult<Prisma.$CustomCollectionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CustomCollections that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomCollectionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CustomCollections
   * const customCollections = await prisma.customCollection.findMany()
   * 
   * // Get first 10 CustomCollections
   * const customCollections = await prisma.customCollection.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const customCollectionWithIdOnly = await prisma.customCollection.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CustomCollectionFindManyArgs>(args?: Prisma.SelectSubset<T, CustomCollectionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CustomCollectionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CustomCollection.
   * @param {CustomCollectionCreateArgs} args - Arguments to create a CustomCollection.
   * @example
   * // Create one CustomCollection
   * const CustomCollection = await prisma.customCollection.create({
   *   data: {
   *     // ... data to create a CustomCollection
   *   }
   * })
   * 
   */
  create<T extends CustomCollectionCreateArgs>(args: Prisma.SelectSubset<T, CustomCollectionCreateArgs<ExtArgs>>): Prisma.Prisma__CustomCollectionClient<runtime.Types.Result.GetResult<Prisma.$CustomCollectionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CustomCollections.
   * @param {CustomCollectionCreateManyArgs} args - Arguments to create many CustomCollections.
   * @example
   * // Create many CustomCollections
   * const customCollection = await prisma.customCollection.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CustomCollectionCreateManyArgs>(args?: Prisma.SelectSubset<T, CustomCollectionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CustomCollections and returns the data saved in the database.
   * @param {CustomCollectionCreateManyAndReturnArgs} args - Arguments to create many CustomCollections.
   * @example
   * // Create many CustomCollections
   * const customCollection = await prisma.customCollection.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CustomCollections and only return the `id`
   * const customCollectionWithIdOnly = await prisma.customCollection.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CustomCollectionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CustomCollectionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CustomCollectionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CustomCollection.
   * @param {CustomCollectionDeleteArgs} args - Arguments to delete one CustomCollection.
   * @example
   * // Delete one CustomCollection
   * const CustomCollection = await prisma.customCollection.delete({
   *   where: {
   *     // ... filter to delete one CustomCollection
   *   }
   * })
   * 
   */
  delete<T extends CustomCollectionDeleteArgs>(args: Prisma.SelectSubset<T, CustomCollectionDeleteArgs<ExtArgs>>): Prisma.Prisma__CustomCollectionClient<runtime.Types.Result.GetResult<Prisma.$CustomCollectionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CustomCollection.
   * @param {CustomCollectionUpdateArgs} args - Arguments to update one CustomCollection.
   * @example
   * // Update one CustomCollection
   * const customCollection = await prisma.customCollection.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CustomCollectionUpdateArgs>(args: Prisma.SelectSubset<T, CustomCollectionUpdateArgs<ExtArgs>>): Prisma.Prisma__CustomCollectionClient<runtime.Types.Result.GetResult<Prisma.$CustomCollectionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CustomCollections.
   * @param {CustomCollectionDeleteManyArgs} args - Arguments to filter CustomCollections to delete.
   * @example
   * // Delete a few CustomCollections
   * const { count } = await prisma.customCollection.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CustomCollectionDeleteManyArgs>(args?: Prisma.SelectSubset<T, CustomCollectionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CustomCollections.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomCollectionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CustomCollections
   * const customCollection = await prisma.customCollection.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CustomCollectionUpdateManyArgs>(args: Prisma.SelectSubset<T, CustomCollectionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CustomCollections and returns the data updated in the database.
   * @param {CustomCollectionUpdateManyAndReturnArgs} args - Arguments to update many CustomCollections.
   * @example
   * // Update many CustomCollections
   * const customCollection = await prisma.customCollection.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CustomCollections and only return the `id`
   * const customCollectionWithIdOnly = await prisma.customCollection.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CustomCollectionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CustomCollectionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CustomCollectionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CustomCollection.
   * @param {CustomCollectionUpsertArgs} args - Arguments to update or create a CustomCollection.
   * @example
   * // Update or create a CustomCollection
   * const customCollection = await prisma.customCollection.upsert({
   *   create: {
   *     // ... data to create a CustomCollection
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CustomCollection we want to update
   *   }
   * })
   */
  upsert<T extends CustomCollectionUpsertArgs>(args: Prisma.SelectSubset<T, CustomCollectionUpsertArgs<ExtArgs>>): Prisma.Prisma__CustomCollectionClient<runtime.Types.Result.GetResult<Prisma.$CustomCollectionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CustomCollections.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomCollectionCountArgs} args - Arguments to filter CustomCollections to count.
   * @example
   * // Count the number of CustomCollections
   * const count = await prisma.customCollection.count({
   *   where: {
   *     // ... the filter for the CustomCollections we want to count
   *   }
   * })
  **/
  count<T extends CustomCollectionCountArgs>(
    args?: Prisma.Subset<T, CustomCollectionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CustomCollectionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CustomCollection.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomCollectionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CustomCollectionAggregateArgs>(args: Prisma.Subset<T, CustomCollectionAggregateArgs>): Prisma.PrismaPromise<GetCustomCollectionAggregateType<T>>

  /**
   * Group by CustomCollection.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomCollectionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CustomCollectionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CustomCollectionGroupByArgs['orderBy'] }
      : { orderBy?: CustomCollectionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CustomCollectionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCustomCollectionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CustomCollection model
 */
readonly fields: CustomCollectionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CustomCollection.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CustomCollectionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  objects<T extends Prisma.CustomCollection$objectsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CustomCollection$objectsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CustomCollectionObjectPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CustomCollection model
 */
export interface CustomCollectionFieldRefs {
  readonly id: Prisma.FieldRef<"CustomCollection", 'String'>
  readonly userId: Prisma.FieldRef<"CustomCollection", 'String'>
  readonly title: Prisma.FieldRef<"CustomCollection", 'String'>
  readonly description: Prisma.FieldRef<"CustomCollection", 'String'>
  readonly reason: Prisma.FieldRef<"CustomCollection", 'String'>
  readonly imageUrl: Prisma.FieldRef<"CustomCollection", 'String'>
  readonly createdAt: Prisma.FieldRef<"CustomCollection", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CustomCollection findUnique
 */
export type CustomCollectionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomCollection
   */
  select?: Prisma.CustomCollectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomCollection
   */
  omit?: Prisma.CustomCollectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomCollectionInclude<ExtArgs> | null
  /**
   * Filter, which CustomCollection to fetch.
   */
  where: Prisma.CustomCollectionWhereUniqueInput
}

/**
 * CustomCollection findUniqueOrThrow
 */
export type CustomCollectionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomCollection
   */
  select?: Prisma.CustomCollectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomCollection
   */
  omit?: Prisma.CustomCollectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomCollectionInclude<ExtArgs> | null
  /**
   * Filter, which CustomCollection to fetch.
   */
  where: Prisma.CustomCollectionWhereUniqueInput
}

/**
 * CustomCollection findFirst
 */
export type CustomCollectionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomCollection
   */
  select?: Prisma.CustomCollectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomCollection
   */
  omit?: Prisma.CustomCollectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomCollectionInclude<ExtArgs> | null
  /**
   * Filter, which CustomCollection to fetch.
   */
  where?: Prisma.CustomCollectionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CustomCollections to fetch.
   */
  orderBy?: Prisma.CustomCollectionOrderByWithRelationInput | Prisma.CustomCollectionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CustomCollections.
   */
  cursor?: Prisma.CustomCollectionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CustomCollections from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CustomCollections.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CustomCollections.
   */
  distinct?: Prisma.CustomCollectionScalarFieldEnum | Prisma.CustomCollectionScalarFieldEnum[]
}

/**
 * CustomCollection findFirstOrThrow
 */
export type CustomCollectionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomCollection
   */
  select?: Prisma.CustomCollectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomCollection
   */
  omit?: Prisma.CustomCollectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomCollectionInclude<ExtArgs> | null
  /**
   * Filter, which CustomCollection to fetch.
   */
  where?: Prisma.CustomCollectionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CustomCollections to fetch.
   */
  orderBy?: Prisma.CustomCollectionOrderByWithRelationInput | Prisma.CustomCollectionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CustomCollections.
   */
  cursor?: Prisma.CustomCollectionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CustomCollections from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CustomCollections.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CustomCollections.
   */
  distinct?: Prisma.CustomCollectionScalarFieldEnum | Prisma.CustomCollectionScalarFieldEnum[]
}

/**
 * CustomCollection findMany
 */
export type CustomCollectionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomCollection
   */
  select?: Prisma.CustomCollectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomCollection
   */
  omit?: Prisma.CustomCollectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomCollectionInclude<ExtArgs> | null
  /**
   * Filter, which CustomCollections to fetch.
   */
  where?: Prisma.CustomCollectionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CustomCollections to fetch.
   */
  orderBy?: Prisma.CustomCollectionOrderByWithRelationInput | Prisma.CustomCollectionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CustomCollections.
   */
  cursor?: Prisma.CustomCollectionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CustomCollections from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CustomCollections.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CustomCollections.
   */
  distinct?: Prisma.CustomCollectionScalarFieldEnum | Prisma.CustomCollectionScalarFieldEnum[]
}

/**
 * CustomCollection create
 */
export type CustomCollectionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomCollection
   */
  select?: Prisma.CustomCollectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomCollection
   */
  omit?: Prisma.CustomCollectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomCollectionInclude<ExtArgs> | null
  /**
   * The data needed to create a CustomCollection.
   */
  data: Prisma.XOR<Prisma.CustomCollectionCreateInput, Prisma.CustomCollectionUncheckedCreateInput>
}

/**
 * CustomCollection createMany
 */
export type CustomCollectionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CustomCollections.
   */
  data: Prisma.CustomCollectionCreateManyInput | Prisma.CustomCollectionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CustomCollection createManyAndReturn
 */
export type CustomCollectionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomCollection
   */
  select?: Prisma.CustomCollectionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CustomCollection
   */
  omit?: Prisma.CustomCollectionOmit<ExtArgs> | null
  /**
   * The data used to create many CustomCollections.
   */
  data: Prisma.CustomCollectionCreateManyInput | Prisma.CustomCollectionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomCollectionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CustomCollection update
 */
export type CustomCollectionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomCollection
   */
  select?: Prisma.CustomCollectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomCollection
   */
  omit?: Prisma.CustomCollectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomCollectionInclude<ExtArgs> | null
  /**
   * The data needed to update a CustomCollection.
   */
  data: Prisma.XOR<Prisma.CustomCollectionUpdateInput, Prisma.CustomCollectionUncheckedUpdateInput>
  /**
   * Choose, which CustomCollection to update.
   */
  where: Prisma.CustomCollectionWhereUniqueInput
}

/**
 * CustomCollection updateMany
 */
export type CustomCollectionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CustomCollections.
   */
  data: Prisma.XOR<Prisma.CustomCollectionUpdateManyMutationInput, Prisma.CustomCollectionUncheckedUpdateManyInput>
  /**
   * Filter which CustomCollections to update
   */
  where?: Prisma.CustomCollectionWhereInput
  /**
   * Limit how many CustomCollections to update.
   */
  limit?: number
}

/**
 * CustomCollection updateManyAndReturn
 */
export type CustomCollectionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomCollection
   */
  select?: Prisma.CustomCollectionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CustomCollection
   */
  omit?: Prisma.CustomCollectionOmit<ExtArgs> | null
  /**
   * The data used to update CustomCollections.
   */
  data: Prisma.XOR<Prisma.CustomCollectionUpdateManyMutationInput, Prisma.CustomCollectionUncheckedUpdateManyInput>
  /**
   * Filter which CustomCollections to update
   */
  where?: Prisma.CustomCollectionWhereInput
  /**
   * Limit how many CustomCollections to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomCollectionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CustomCollection upsert
 */
export type CustomCollectionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomCollection
   */
  select?: Prisma.CustomCollectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomCollection
   */
  omit?: Prisma.CustomCollectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomCollectionInclude<ExtArgs> | null
  /**
   * The filter to search for the CustomCollection to update in case it exists.
   */
  where: Prisma.CustomCollectionWhereUniqueInput
  /**
   * In case the CustomCollection found by the `where` argument doesn't exist, create a new CustomCollection with this data.
   */
  create: Prisma.XOR<Prisma.CustomCollectionCreateInput, Prisma.CustomCollectionUncheckedCreateInput>
  /**
   * In case the CustomCollection was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CustomCollectionUpdateInput, Prisma.CustomCollectionUncheckedUpdateInput>
}

/**
 * CustomCollection delete
 */
export type CustomCollectionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomCollection
   */
  select?: Prisma.CustomCollectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomCollection
   */
  omit?: Prisma.CustomCollectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomCollectionInclude<ExtArgs> | null
  /**
   * Filter which CustomCollection to delete.
   */
  where: Prisma.CustomCollectionWhereUniqueInput
}

/**
 * CustomCollection deleteMany
 */
export type CustomCollectionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CustomCollections to delete
   */
  where?: Prisma.CustomCollectionWhereInput
  /**
   * Limit how many CustomCollections to delete.
   */
  limit?: number
}

/**
 * CustomCollection.objects
 */
export type CustomCollection$objectsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomCollectionObject
   */
  select?: Prisma.CustomCollectionObjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomCollectionObject
   */
  omit?: Prisma.CustomCollectionObjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomCollectionObjectInclude<ExtArgs> | null
  where?: Prisma.CustomCollectionObjectWhereInput
  orderBy?: Prisma.CustomCollectionObjectOrderByWithRelationInput | Prisma.CustomCollectionObjectOrderByWithRelationInput[]
  cursor?: Prisma.CustomCollectionObjectWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CustomCollectionObjectScalarFieldEnum | Prisma.CustomCollectionObjectScalarFieldEnum[]
}

/**
 * CustomCollection without action
 */
export type CustomCollectionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomCollection
   */
  select?: Prisma.CustomCollectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomCollection
   */
  omit?: Prisma.CustomCollectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomCollectionInclude<ExtArgs> | null
}
