
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CustomCollectionObject` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model CustomCollectionObject
 * 
 */
export type CustomCollectionObjectModel = runtime.Types.Result.DefaultSelection<Prisma.$CustomCollectionObjectPayload>

export type AggregateCustomCollectionObject = {
  _count: CustomCollectionObjectCountAggregateOutputType | null
  _avg: CustomCollectionObjectAvgAggregateOutputType | null
  _sum: CustomCollectionObjectSumAggregateOutputType | null
  _min: CustomCollectionObjectMinAggregateOutputType | null
  _max: CustomCollectionObjectMaxAggregateOutputType | null
}

export type CustomCollectionObjectAvgAggregateOutputType = {
  id: number | null
}

export type CustomCollectionObjectSumAggregateOutputType = {
  id: number | null
}

export type CustomCollectionObjectMinAggregateOutputType = {
  id: number | null
  collectionId: string | null
  title: string | null
  description: string | null
  note: string | null
  isFavorite: boolean | null
  imageUrl: string | null
  createdAt: Date | null
}

export type CustomCollectionObjectMaxAggregateOutputType = {
  id: number | null
  collectionId: string | null
  title: string | null
  description: string | null
  note: string | null
  isFavorite: boolean | null
  imageUrl: string | null
  createdAt: Date | null
}

export type CustomCollectionObjectCountAggregateOutputType = {
  id: number
  collectionId: number
  title: number
  description: number
  note: number
  isFavorite: number
  imageUrl: number
  createdAt: number
  _all: number
}


export type CustomCollectionObjectAvgAggregateInputType = {
  id?: true
}

export type CustomCollectionObjectSumAggregateInputType = {
  id?: true
}

export type CustomCollectionObjectMinAggregateInputType = {
  id?: true
  collectionId?: true
  title?: true
  description?: true
  note?: true
  isFavorite?: true
  imageUrl?: true
  createdAt?: true
}

export type CustomCollectionObjectMaxAggregateInputType = {
  id?: true
  collectionId?: true
  title?: true
  description?: true
  note?: true
  isFavorite?: true
  imageUrl?: true
  createdAt?: true
}

export type CustomCollectionObjectCountAggregateInputType = {
  id?: true
  collectionId?: true
  title?: true
  description?: true
  note?: true
  isFavorite?: true
  imageUrl?: true
  createdAt?: true
  _all?: true
}

export type CustomCollectionObjectAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CustomCollectionObject to aggregate.
   */
  where?: Prisma.CustomCollectionObjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CustomCollectionObjects to fetch.
   */
  orderBy?: Prisma.CustomCollectionObjectOrderByWithRelationInput | Prisma.CustomCollectionObjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CustomCollectionObjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CustomCollectionObjects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CustomCollectionObjects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CustomCollectionObjects
  **/
  _count?: true | CustomCollectionObjectCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CustomCollectionObjectAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CustomCollectionObjectSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CustomCollectionObjectMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CustomCollectionObjectMaxAggregateInputType
}

export type GetCustomCollectionObjectAggregateType<T extends CustomCollectionObjectAggregateArgs> = {
      [P in keyof T & keyof AggregateCustomCollectionObject]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCustomCollectionObject[P]>
    : Prisma.GetScalarType<T[P], AggregateCustomCollectionObject[P]>
}




export type CustomCollectionObjectGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CustomCollectionObjectWhereInput
  orderBy?: Prisma.CustomCollectionObjectOrderByWithAggregationInput | Prisma.CustomCollectionObjectOrderByWithAggregationInput[]
  by: Prisma.CustomCollectionObjectScalarFieldEnum[] | Prisma.CustomCollectionObjectScalarFieldEnum
  having?: Prisma.CustomCollectionObjectScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CustomCollectionObjectCountAggregateInputType | true
  _avg?: CustomCollectionObjectAvgAggregateInputType
  _sum?: CustomCollectionObjectSumAggregateInputType
  _min?: CustomCollectionObjectMinAggregateInputType
  _max?: CustomCollectionObjectMaxAggregateInputType
}

export type CustomCollectionObjectGroupByOutputType = {
  id: number
  collectionId: string
  title: string
  description: string | null
  note: string | null
  isFavorite: boolean
  imageUrl: string | null
  createdAt: Date
  _count: CustomCollectionObjectCountAggregateOutputType | null
  _avg: CustomCollectionObjectAvgAggregateOutputType | null
  _sum: CustomCollectionObjectSumAggregateOutputType | null
  _min: CustomCollectionObjectMinAggregateOutputType | null
  _max: CustomCollectionObjectMaxAggregateOutputType | null
}

export type GetCustomCollectionObjectGroupByPayload<T extends CustomCollectionObjectGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CustomCollectionObjectGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CustomCollectionObjectGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CustomCollectionObjectGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CustomCollectionObjectGroupByOutputType[P]>
      }
    >
  >



export type CustomCollectionObjectWhereInput = {
  AND?: Prisma.CustomCollectionObjectWhereInput | Prisma.CustomCollectionObjectWhereInput[]
  OR?: Prisma.CustomCollectionObjectWhereInput[]
  NOT?: Prisma.CustomCollectionObjectWhereInput | Prisma.CustomCollectionObjectWhereInput[]
  id?: Prisma.IntFilter<"CustomCollectionObject"> | number
  collectionId?: Prisma.StringFilter<"CustomCollectionObject"> | string
  title?: Prisma.StringFilter<"CustomCollectionObject"> | string
  description?: Prisma.StringNullableFilter<"CustomCollectionObject"> | string | null
  note?: Prisma.StringNullableFilter<"CustomCollectionObject"> | string | null
  isFavorite?: Prisma.BoolFilter<"CustomCollectionObject"> | boolean
  imageUrl?: Prisma.StringNullableFilter<"CustomCollectionObject"> | string | null
  createdAt?: Prisma.DateTimeFilter<"CustomCollectionObject"> | Date | string
  collection?: Prisma.XOR<Prisma.CustomCollectionScalarRelationFilter, Prisma.CustomCollectionWhereInput>
}

export type CustomCollectionObjectOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  collectionId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  note?: Prisma.SortOrderInput | Prisma.SortOrder
  isFavorite?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  collection?: Prisma.CustomCollectionOrderByWithRelationInput
}

export type CustomCollectionObjectWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.CustomCollectionObjectWhereInput | Prisma.CustomCollectionObjectWhereInput[]
  OR?: Prisma.CustomCollectionObjectWhereInput[]
  NOT?: Prisma.CustomCollectionObjectWhereInput | Prisma.CustomCollectionObjectWhereInput[]
  collectionId?: Prisma.StringFilter<"CustomCollectionObject"> | string
  title?: Prisma.StringFilter<"CustomCollectionObject"> | string
  description?: Prisma.StringNullableFilter<"CustomCollectionObject"> | string | null
  note?: Prisma.StringNullableFilter<"CustomCollectionObject"> | string | null
  isFavorite?: Prisma.BoolFilter<"CustomCollectionObject"> | boolean
  imageUrl?: Prisma.StringNullableFilter<"CustomCollectionObject"> | string | null
  createdAt?: Prisma.DateTimeFilter<"CustomCollectionObject"> | Date | string
  collection?: Prisma.XOR<Prisma.CustomCollectionScalarRelationFilter, Prisma.CustomCollectionWhereInput>
}, "id">

export type CustomCollectionObjectOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  collectionId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  note?: Prisma.SortOrderInput | Prisma.SortOrder
  isFavorite?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.CustomCollectionObjectCountOrderByAggregateInput
  _avg?: Prisma.CustomCollectionObjectAvgOrderByAggregateInput
  _max?: Prisma.CustomCollectionObjectMaxOrderByAggregateInput
  _min?: Prisma.CustomCollectionObjectMinOrderByAggregateInput
  _sum?: Prisma.CustomCollectionObjectSumOrderByAggregateInput
}

export type CustomCollectionObjectScalarWhereWithAggregatesInput = {
  AND?: Prisma.CustomCollectionObjectScalarWhereWithAggregatesInput | Prisma.CustomCollectionObjectScalarWhereWithAggregatesInput[]
  OR?: Prisma.CustomCollectionObjectScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CustomCollectionObjectScalarWhereWithAggregatesInput | Prisma.CustomCollectionObjectScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"CustomCollectionObject"> | number
  collectionId?: Prisma.StringWithAggregatesFilter<"CustomCollectionObject"> | string
  title?: Prisma.StringWithAggregatesFilter<"CustomCollectionObject"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"CustomCollectionObject"> | string | null
  note?: Prisma.StringNullableWithAggregatesFilter<"CustomCollectionObject"> | string | null
  isFavorite?: Prisma.BoolWithAggregatesFilter<"CustomCollectionObject"> | boolean
  imageUrl?: Prisma.StringNullableWithAggregatesFilter<"CustomCollectionObject"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CustomCollectionObject"> | Date | string
}

export type CustomCollectionObjectCreateInput = {
  title: string
  description?: string | null
  note?: string | null
  isFavorite?: boolean
  imageUrl?: string | null
  createdAt?: Date | string
  collection: Prisma.CustomCollectionCreateNestedOneWithoutObjectsInput
}

export type CustomCollectionObjectUncheckedCreateInput = {
  id?: number
  collectionId: string
  title: string
  description?: string | null
  note?: string | null
  isFavorite?: boolean
  imageUrl?: string | null
  createdAt?: Date | string
}

export type CustomCollectionObjectUpdateInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isFavorite?: Prisma.BoolFieldUpdateOperationsInput | boolean
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  collection?: Prisma.CustomCollectionUpdateOneRequiredWithoutObjectsNestedInput
}

export type CustomCollectionObjectUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  collectionId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isFavorite?: Prisma.BoolFieldUpdateOperationsInput | boolean
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CustomCollectionObjectCreateManyInput = {
  id?: number
  collectionId: string
  title: string
  description?: string | null
  note?: string | null
  isFavorite?: boolean
  imageUrl?: string | null
  createdAt?: Date | string
}

export type CustomCollectionObjectUpdateManyMutationInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isFavorite?: Prisma.BoolFieldUpdateOperationsInput | boolean
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CustomCollectionObjectUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  collectionId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isFavorite?: Prisma.BoolFieldUpdateOperationsInput | boolean
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CustomCollectionObjectListRelationFilter = {
  every?: Prisma.CustomCollectionObjectWhereInput
  some?: Prisma.CustomCollectionObjectWhereInput
  none?: Prisma.CustomCollectionObjectWhereInput
}

export type CustomCollectionObjectOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CustomCollectionObjectCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  collectionId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  note?: Prisma.SortOrder
  isFavorite?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CustomCollectionObjectAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type CustomCollectionObjectMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  collectionId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  note?: Prisma.SortOrder
  isFavorite?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CustomCollectionObjectMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  collectionId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  note?: Prisma.SortOrder
  isFavorite?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CustomCollectionObjectSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type CustomCollectionObjectCreateNestedManyWithoutCollectionInput = {
  create?: Prisma.XOR<Prisma.CustomCollectionObjectCreateWithoutCollectionInput, Prisma.CustomCollectionObjectUncheckedCreateWithoutCollectionInput> | Prisma.CustomCollectionObjectCreateWithoutCollectionInput[] | Prisma.CustomCollectionObjectUncheckedCreateWithoutCollectionInput[]
  connectOrCreate?: Prisma.CustomCollectionObjectCreateOrConnectWithoutCollectionInput | Prisma.CustomCollectionObjectCreateOrConnectWithoutCollectionInput[]
  createMany?: Prisma.CustomCollectionObjectCreateManyCollectionInputEnvelope
  connect?: Prisma.CustomCollectionObjectWhereUniqueInput | Prisma.CustomCollectionObjectWhereUniqueInput[]
}

export type CustomCollectionObjectUncheckedCreateNestedManyWithoutCollectionInput = {
  create?: Prisma.XOR<Prisma.CustomCollectionObjectCreateWithoutCollectionInput, Prisma.CustomCollectionObjectUncheckedCreateWithoutCollectionInput> | Prisma.CustomCollectionObjectCreateWithoutCollectionInput[] | Prisma.CustomCollectionObjectUncheckedCreateWithoutCollectionInput[]
  connectOrCreate?: Prisma.CustomCollectionObjectCreateOrConnectWithoutCollectionInput | Prisma.CustomCollectionObjectCreateOrConnectWithoutCollectionInput[]
  createMany?: Prisma.CustomCollectionObjectCreateManyCollectionInputEnvelope
  connect?: Prisma.CustomCollectionObjectWhereUniqueInput | Prisma.CustomCollectionObjectWhereUniqueInput[]
}

export type CustomCollectionObjectUpdateManyWithoutCollectionNestedInput = {
  create?: Prisma.XOR<Prisma.CustomCollectionObjectCreateWithoutCollectionInput, Prisma.CustomCollectionObjectUncheckedCreateWithoutCollectionInput> | Prisma.CustomCollectionObjectCreateWithoutCollectionInput[] | Prisma.CustomCollectionObjectUncheckedCreateWithoutCollectionInput[]
  connectOrCreate?: Prisma.CustomCollectionObjectCreateOrConnectWithoutCollectionInput | Prisma.CustomCollectionObjectCreateOrConnectWithoutCollectionInput[]
  upsert?: Prisma.CustomCollectionObjectUpsertWithWhereUniqueWithoutCollectionInput | Prisma.CustomCollectionObjectUpsertWithWhereUniqueWithoutCollectionInput[]
  createMany?: Prisma.CustomCollectionObjectCreateManyCollectionInputEnvelope
  set?: Prisma.CustomCollectionObjectWhereUniqueInput | Prisma.CustomCollectionObjectWhereUniqueInput[]
  disconnect?: Prisma.CustomCollectionObjectWhereUniqueInput | Prisma.CustomCollectionObjectWhereUniqueInput[]
  delete?: Prisma.CustomCollectionObjectWhereUniqueInput | Prisma.CustomCollectionObjectWhereUniqueInput[]
  connect?: Prisma.CustomCollectionObjectWhereUniqueInput | Prisma.CustomCollectionObjectWhereUniqueInput[]
  update?: Prisma.CustomCollectionObjectUpdateWithWhereUniqueWithoutCollectionInput | Prisma.CustomCollectionObjectUpdateWithWhereUniqueWithoutCollectionInput[]
  updateMany?: Prisma.CustomCollectionObjectUpdateManyWithWhereWithoutCollectionInput | Prisma.CustomCollectionObjectUpdateManyWithWhereWithoutCollectionInput[]
  deleteMany?: Prisma.CustomCollectionObjectScalarWhereInput | Prisma.CustomCollectionObjectScalarWhereInput[]
}

export type CustomCollectionObjectUncheckedUpdateManyWithoutCollectionNestedInput = {
  create?: Prisma.XOR<Prisma.CustomCollectionObjectCreateWithoutCollectionInput, Prisma.CustomCollectionObjectUncheckedCreateWithoutCollectionInput> | Prisma.CustomCollectionObjectCreateWithoutCollectionInput[] | Prisma.CustomCollectionObjectUncheckedCreateWithoutCollectionInput[]
  connectOrCreate?: Prisma.CustomCollectionObjectCreateOrConnectWithoutCollectionInput | Prisma.CustomCollectionObjectCreateOrConnectWithoutCollectionInput[]
  upsert?: Prisma.CustomCollectionObjectUpsertWithWhereUniqueWithoutCollectionInput | Prisma.CustomCollectionObjectUpsertWithWhereUniqueWithoutCollectionInput[]
  createMany?: Prisma.CustomCollectionObjectCreateManyCollectionInputEnvelope
  set?: Prisma.CustomCollectionObjectWhereUniqueInput | Prisma.CustomCollectionObjectWhereUniqueInput[]
  disconnect?: Prisma.CustomCollectionObjectWhereUniqueInput | Prisma.CustomCollectionObjectWhereUniqueInput[]
  delete?: Prisma.CustomCollectionObjectWhereUniqueInput | Prisma.CustomCollectionObjectWhereUniqueInput[]
  connect?: Prisma.CustomCollectionObjectWhereUniqueInput | Prisma.CustomCollectionObjectWhereUniqueInput[]
  update?: Prisma.CustomCollectionObjectUpdateWithWhereUniqueWithoutCollectionInput | Prisma.CustomCollectionObjectUpdateWithWhereUniqueWithoutCollectionInput[]
  updateMany?: Prisma.CustomCollectionObjectUpdateManyWithWhereWithoutCollectionInput | Prisma.CustomCollectionObjectUpdateManyWithWhereWithoutCollectionInput[]
  deleteMany?: Prisma.CustomCollectionObjectScalarWhereInput | Prisma.CustomCollectionObjectScalarWhereInput[]
}

export type CustomCollectionObjectCreateWithoutCollectionInput = {
  title: string
  description?: string | null
  note?: string | null
  isFavorite?: boolean
  imageUrl?: string | null
  createdAt?: Date | string
}

export type CustomCollectionObjectUncheckedCreateWithoutCollectionInput = {
  id?: number
  title: string
  description?: string | null
  note?: string | null
  isFavorite?: boolean
  imageUrl?: string | null
  createdAt?: Date | string
}

export type CustomCollectionObjectCreateOrConnectWithoutCollectionInput = {
  where: Prisma.CustomCollectionObjectWhereUniqueInput
  create: Prisma.XOR<Prisma.CustomCollectionObjectCreateWithoutCollectionInput, Prisma.CustomCollectionObjectUncheckedCreateWithoutCollectionInput>
}

export type CustomCollectionObjectCreateManyCollectionInputEnvelope = {
  data: Prisma.CustomCollectionObjectCreateManyCollectionInput | Prisma.CustomCollectionObjectCreateManyCollectionInput[]
  skipDuplicates?: boolean
}

export type CustomCollectionObjectUpsertWithWhereUniqueWithoutCollectionInput = {
  where: Prisma.CustomCollectionObjectWhereUniqueInput
  update: Prisma.XOR<Prisma.CustomCollectionObjectUpdateWithoutCollectionInput, Prisma.CustomCollectionObjectUncheckedUpdateWithoutCollectionInput>
  create: Prisma.XOR<Prisma.CustomCollectionObjectCreateWithoutCollectionInput, Prisma.CustomCollectionObjectUncheckedCreateWithoutCollectionInput>
}

export type CustomCollectionObjectUpdateWithWhereUniqueWithoutCollectionInput = {
  where: Prisma.CustomCollectionObjectWhereUniqueInput
  data: Prisma.XOR<Prisma.CustomCollectionObjectUpdateWithoutCollectionInput, Prisma.CustomCollectionObjectUncheckedUpdateWithoutCollectionInput>
}

export type CustomCollectionObjectUpdateManyWithWhereWithoutCollectionInput = {
  where: Prisma.CustomCollectionObjectScalarWhereInput
  data: Prisma.XOR<Prisma.CustomCollectionObjectUpdateManyMutationInput, Prisma.CustomCollectionObjectUncheckedUpdateManyWithoutCollectionInput>
}

export type CustomCollectionObjectScalarWhereInput = {
  AND?: Prisma.CustomCollectionObjectScalarWhereInput | Prisma.CustomCollectionObjectScalarWhereInput[]
  OR?: Prisma.CustomCollectionObjectScalarWhereInput[]
  NOT?: Prisma.CustomCollectionObjectScalarWhereInput | Prisma.CustomCollectionObjectScalarWhereInput[]
  id?: Prisma.IntFilter<"CustomCollectionObject"> | number
  collectionId?: Prisma.StringFilter<"CustomCollectionObject"> | string
  title?: Prisma.StringFilter<"CustomCollectionObject"> | string
  description?: Prisma.StringNullableFilter<"CustomCollectionObject"> | string | null
  note?: Prisma.StringNullableFilter<"CustomCollectionObject"> | string | null
  isFavorite?: Prisma.BoolFilter<"CustomCollectionObject"> | boolean
  imageUrl?: Prisma.StringNullableFilter<"CustomCollectionObject"> | string | null
  createdAt?: Prisma.DateTimeFilter<"CustomCollectionObject"> | Date | string
}

export type CustomCollectionObjectCreateManyCollectionInput = {
  id?: number
  title: string
  description?: string | null
  note?: string | null
  isFavorite?: boolean
  imageUrl?: string | null
  createdAt?: Date | string
}

export type CustomCollectionObjectUpdateWithoutCollectionInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isFavorite?: Prisma.BoolFieldUpdateOperationsInput | boolean
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CustomCollectionObjectUncheckedUpdateWithoutCollectionInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isFavorite?: Prisma.BoolFieldUpdateOperationsInput | boolean
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CustomCollectionObjectUncheckedUpdateManyWithoutCollectionInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isFavorite?: Prisma.BoolFieldUpdateOperationsInput | boolean
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type CustomCollectionObjectSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  collectionId?: boolean
  title?: boolean
  description?: boolean
  note?: boolean
  isFavorite?: boolean
  imageUrl?: boolean
  createdAt?: boolean
  collection?: boolean | Prisma.CustomCollectionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["customCollectionObject"]>

export type CustomCollectionObjectSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  collectionId?: boolean
  title?: boolean
  description?: boolean
  note?: boolean
  isFavorite?: boolean
  imageUrl?: boolean
  createdAt?: boolean
  collection?: boolean | Prisma.CustomCollectionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["customCollectionObject"]>

export type CustomCollectionObjectSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  collectionId?: boolean
  title?: boolean
  description?: boolean
  note?: boolean
  isFavorite?: boolean
  imageUrl?: boolean
  createdAt?: boolean
  collection?: boolean | Prisma.CustomCollectionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["customCollectionObject"]>

export type CustomCollectionObjectSelectScalar = {
  id?: boolean
  collectionId?: boolean
  title?: boolean
  description?: boolean
  note?: boolean
  isFavorite?: boolean
  imageUrl?: boolean
  createdAt?: boolean
}

export type CustomCollectionObjectOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "collectionId" | "title" | "description" | "note" | "isFavorite" | "imageUrl" | "createdAt", ExtArgs["result"]["customCollectionObject"]>
export type CustomCollectionObjectInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  collection?: boolean | Prisma.CustomCollectionDefaultArgs<ExtArgs>
}
export type CustomCollectionObjectIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  collection?: boolean | Prisma.CustomCollectionDefaultArgs<ExtArgs>
}
export type CustomCollectionObjectIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  collection?: boolean | Prisma.CustomCollectionDefaultArgs<ExtArgs>
}

export type $CustomCollectionObjectPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CustomCollectionObject"
  objects: {
    collection: Prisma.$CustomCollectionPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    collectionId: string
    title: string
    description: string | null
    note: string | null
    isFavorite: boolean
    imageUrl: string | null
    createdAt: Date
  }, ExtArgs["result"]["customCollectionObject"]>
  composites: {}
}

export type CustomCollectionObjectGetPayload<S extends boolean | null | undefined | CustomCollectionObjectDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CustomCollectionObjectPayload, S>

export type CustomCollectionObjectCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CustomCollectionObjectFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CustomCollectionObjectCountAggregateInputType | true
  }

export interface CustomCollectionObjectDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CustomCollectionObject'], meta: { name: 'CustomCollectionObject' } }
  /**
   * Find zero or one CustomCollectionObject that matches the filter.
   * @param {CustomCollectionObjectFindUniqueArgs} args - Arguments to find a CustomCollectionObject
   * @example
   * // Get one CustomCollectionObject
   * const customCollectionObject = await prisma.customCollectionObject.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CustomCollectionObjectFindUniqueArgs>(args: Prisma.SelectSubset<T, CustomCollectionObjectFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CustomCollectionObjectClient<runtime.Types.Result.GetResult<Prisma.$CustomCollectionObjectPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CustomCollectionObject that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CustomCollectionObjectFindUniqueOrThrowArgs} args - Arguments to find a CustomCollectionObject
   * @example
   * // Get one CustomCollectionObject
   * const customCollectionObject = await prisma.customCollectionObject.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CustomCollectionObjectFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CustomCollectionObjectFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CustomCollectionObjectClient<runtime.Types.Result.GetResult<Prisma.$CustomCollectionObjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CustomCollectionObject that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomCollectionObjectFindFirstArgs} args - Arguments to find a CustomCollectionObject
   * @example
   * // Get one CustomCollectionObject
   * const customCollectionObject = await prisma.customCollectionObject.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CustomCollectionObjectFindFirstArgs>(args?: Prisma.SelectSubset<T, CustomCollectionObjectFindFirstArgs<ExtArgs>>): Prisma.Prisma__CustomCollectionObjectClient<runtime.Types.Result.GetResult<Prisma.$CustomCollectionObjectPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CustomCollectionObject that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomCollectionObjectFindFirstOrThrowArgs} args - Arguments to find a CustomCollectionObject
   * @example
   * // Get one CustomCollectionObject
   * const customCollectionObject = await prisma.customCollectionObject.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CustomCollectionObjectFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CustomCollectionObjectFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CustomCollectionObjectClient<runtime.Types.Result.GetResult<Prisma.$CustomCollectionObjectPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CustomCollectionObjects that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomCollectionObjectFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CustomCollectionObjects
   * const customCollectionObjects = await prisma.customCollectionObject.findMany()
   * 
   * // Get first 10 CustomCollectionObjects
   * const customCollectionObjects = await prisma.customCollectionObject.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const customCollectionObjectWithIdOnly = await prisma.customCollectionObject.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CustomCollectionObjectFindManyArgs>(args?: Prisma.SelectSubset<T, CustomCollectionObjectFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CustomCollectionObjectPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CustomCollectionObject.
   * @param {CustomCollectionObjectCreateArgs} args - Arguments to create a CustomCollectionObject.
   * @example
   * // Create one CustomCollectionObject
   * const CustomCollectionObject = await prisma.customCollectionObject.create({
   *   data: {
   *     // ... data to create a CustomCollectionObject
   *   }
   * })
   * 
   */
  create<T extends CustomCollectionObjectCreateArgs>(args: Prisma.SelectSubset<T, CustomCollectionObjectCreateArgs<ExtArgs>>): Prisma.Prisma__CustomCollectionObjectClient<runtime.Types.Result.GetResult<Prisma.$CustomCollectionObjectPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CustomCollectionObjects.
   * @param {CustomCollectionObjectCreateManyArgs} args - Arguments to create many CustomCollectionObjects.
   * @example
   * // Create many CustomCollectionObjects
   * const customCollectionObject = await prisma.customCollectionObject.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CustomCollectionObjectCreateManyArgs>(args?: Prisma.SelectSubset<T, CustomCollectionObjectCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CustomCollectionObjects and returns the data saved in the database.
   * @param {CustomCollectionObjectCreateManyAndReturnArgs} args - Arguments to create many CustomCollectionObjects.
   * @example
   * // Create many CustomCollectionObjects
   * const customCollectionObject = await prisma.customCollectionObject.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CustomCollectionObjects and only return the `id`
   * const customCollectionObjectWithIdOnly = await prisma.customCollectionObject.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CustomCollectionObjectCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CustomCollectionObjectCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CustomCollectionObjectPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CustomCollectionObject.
   * @param {CustomCollectionObjectDeleteArgs} args - Arguments to delete one CustomCollectionObject.
   * @example
   * // Delete one CustomCollectionObject
   * const CustomCollectionObject = await prisma.customCollectionObject.delete({
   *   where: {
   *     // ... filter to delete one CustomCollectionObject
   *   }
   * })
   * 
   */
  delete<T extends CustomCollectionObjectDeleteArgs>(args: Prisma.SelectSubset<T, CustomCollectionObjectDeleteArgs<ExtArgs>>): Prisma.Prisma__CustomCollectionObjectClient<runtime.Types.Result.GetResult<Prisma.$CustomCollectionObjectPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CustomCollectionObject.
   * @param {CustomCollectionObjectUpdateArgs} args - Arguments to update one CustomCollectionObject.
   * @example
   * // Update one CustomCollectionObject
   * const customCollectionObject = await prisma.customCollectionObject.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CustomCollectionObjectUpdateArgs>(args: Prisma.SelectSubset<T, CustomCollectionObjectUpdateArgs<ExtArgs>>): Prisma.Prisma__CustomCollectionObjectClient<runtime.Types.Result.GetResult<Prisma.$CustomCollectionObjectPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CustomCollectionObjects.
   * @param {CustomCollectionObjectDeleteManyArgs} args - Arguments to filter CustomCollectionObjects to delete.
   * @example
   * // Delete a few CustomCollectionObjects
   * const { count } = await prisma.customCollectionObject.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CustomCollectionObjectDeleteManyArgs>(args?: Prisma.SelectSubset<T, CustomCollectionObjectDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CustomCollectionObjects.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomCollectionObjectUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CustomCollectionObjects
   * const customCollectionObject = await prisma.customCollectionObject.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CustomCollectionObjectUpdateManyArgs>(args: Prisma.SelectSubset<T, CustomCollectionObjectUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CustomCollectionObjects and returns the data updated in the database.
   * @param {CustomCollectionObjectUpdateManyAndReturnArgs} args - Arguments to update many CustomCollectionObjects.
   * @example
   * // Update many CustomCollectionObjects
   * const customCollectionObject = await prisma.customCollectionObject.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CustomCollectionObjects and only return the `id`
   * const customCollectionObjectWithIdOnly = await prisma.customCollectionObject.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CustomCollectionObjectUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CustomCollectionObjectUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CustomCollectionObjectPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CustomCollectionObject.
   * @param {CustomCollectionObjectUpsertArgs} args - Arguments to update or create a CustomCollectionObject.
   * @example
   * // Update or create a CustomCollectionObject
   * const customCollectionObject = await prisma.customCollectionObject.upsert({
   *   create: {
   *     // ... data to create a CustomCollectionObject
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CustomCollectionObject we want to update
   *   }
   * })
   */
  upsert<T extends CustomCollectionObjectUpsertArgs>(args: Prisma.SelectSubset<T, CustomCollectionObjectUpsertArgs<ExtArgs>>): Prisma.Prisma__CustomCollectionObjectClient<runtime.Types.Result.GetResult<Prisma.$CustomCollectionObjectPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CustomCollectionObjects.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomCollectionObjectCountArgs} args - Arguments to filter CustomCollectionObjects to count.
   * @example
   * // Count the number of CustomCollectionObjects
   * const count = await prisma.customCollectionObject.count({
   *   where: {
   *     // ... the filter for the CustomCollectionObjects we want to count
   *   }
   * })
  **/
  count<T extends CustomCollectionObjectCountArgs>(
    args?: Prisma.Subset<T, CustomCollectionObjectCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CustomCollectionObjectCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CustomCollectionObject.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomCollectionObjectAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CustomCollectionObjectAggregateArgs>(args: Prisma.Subset<T, CustomCollectionObjectAggregateArgs>): Prisma.PrismaPromise<GetCustomCollectionObjectAggregateType<T>>

  /**
   * Group by CustomCollectionObject.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomCollectionObjectGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CustomCollectionObjectGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CustomCollectionObjectGroupByArgs['orderBy'] }
      : { orderBy?: CustomCollectionObjectGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CustomCollectionObjectGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCustomCollectionObjectGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CustomCollectionObject model
 */
readonly fields: CustomCollectionObjectFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CustomCollectionObject.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CustomCollectionObjectClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  collection<T extends Prisma.CustomCollectionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CustomCollectionDefaultArgs<ExtArgs>>): Prisma.Prisma__CustomCollectionClient<runtime.Types.Result.GetResult<Prisma.$CustomCollectionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CustomCollectionObject model
 */
export interface CustomCollectionObjectFieldRefs {
  readonly id: Prisma.FieldRef<"CustomCollectionObject", 'Int'>
  readonly collectionId: Prisma.FieldRef<"CustomCollectionObject", 'String'>
  readonly title: Prisma.FieldRef<"CustomCollectionObject", 'String'>
  readonly description: Prisma.FieldRef<"CustomCollectionObject", 'String'>
  readonly note: Prisma.FieldRef<"CustomCollectionObject", 'String'>
  readonly isFavorite: Prisma.FieldRef<"CustomCollectionObject", 'Boolean'>
  readonly imageUrl: Prisma.FieldRef<"CustomCollectionObject", 'String'>
  readonly createdAt: Prisma.FieldRef<"CustomCollectionObject", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CustomCollectionObject findUnique
 */
export type CustomCollectionObjectFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomCollectionObject
   */
  select?: Prisma.CustomCollectionObjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomCollectionObject
   */
  omit?: Prisma.CustomCollectionObjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomCollectionObjectInclude<ExtArgs> | null
  /**
   * Filter, which CustomCollectionObject to fetch.
   */
  where: Prisma.CustomCollectionObjectWhereUniqueInput
}

/**
 * CustomCollectionObject findUniqueOrThrow
 */
export type CustomCollectionObjectFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomCollectionObject
   */
  select?: Prisma.CustomCollectionObjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomCollectionObject
   */
  omit?: Prisma.CustomCollectionObjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomCollectionObjectInclude<ExtArgs> | null
  /**
   * Filter, which CustomCollectionObject to fetch.
   */
  where: Prisma.CustomCollectionObjectWhereUniqueInput
}

/**
 * CustomCollectionObject findFirst
 */
export type CustomCollectionObjectFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomCollectionObject
   */
  select?: Prisma.CustomCollectionObjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomCollectionObject
   */
  omit?: Prisma.CustomCollectionObjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomCollectionObjectInclude<ExtArgs> | null
  /**
   * Filter, which CustomCollectionObject to fetch.
   */
  where?: Prisma.CustomCollectionObjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CustomCollectionObjects to fetch.
   */
  orderBy?: Prisma.CustomCollectionObjectOrderByWithRelationInput | Prisma.CustomCollectionObjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CustomCollectionObjects.
   */
  cursor?: Prisma.CustomCollectionObjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CustomCollectionObjects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CustomCollectionObjects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CustomCollectionObjects.
   */
  distinct?: Prisma.CustomCollectionObjectScalarFieldEnum | Prisma.CustomCollectionObjectScalarFieldEnum[]
}

/**
 * CustomCollectionObject findFirstOrThrow
 */
export type CustomCollectionObjectFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomCollectionObject
   */
  select?: Prisma.CustomCollectionObjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomCollectionObject
   */
  omit?: Prisma.CustomCollectionObjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomCollectionObjectInclude<ExtArgs> | null
  /**
   * Filter, which CustomCollectionObject to fetch.
   */
  where?: Prisma.CustomCollectionObjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CustomCollectionObjects to fetch.
   */
  orderBy?: Prisma.CustomCollectionObjectOrderByWithRelationInput | Prisma.CustomCollectionObjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CustomCollectionObjects.
   */
  cursor?: Prisma.CustomCollectionObjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CustomCollectionObjects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CustomCollectionObjects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CustomCollectionObjects.
   */
  distinct?: Prisma.CustomCollectionObjectScalarFieldEnum | Prisma.CustomCollectionObjectScalarFieldEnum[]
}

/**
 * CustomCollectionObject findMany
 */
export type CustomCollectionObjectFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomCollectionObject
   */
  select?: Prisma.CustomCollectionObjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomCollectionObject
   */
  omit?: Prisma.CustomCollectionObjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomCollectionObjectInclude<ExtArgs> | null
  /**
   * Filter, which CustomCollectionObjects to fetch.
   */
  where?: Prisma.CustomCollectionObjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CustomCollectionObjects to fetch.
   */
  orderBy?: Prisma.CustomCollectionObjectOrderByWithRelationInput | Prisma.CustomCollectionObjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CustomCollectionObjects.
   */
  cursor?: Prisma.CustomCollectionObjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CustomCollectionObjects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CustomCollectionObjects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CustomCollectionObjects.
   */
  distinct?: Prisma.CustomCollectionObjectScalarFieldEnum | Prisma.CustomCollectionObjectScalarFieldEnum[]
}

/**
 * CustomCollectionObject create
 */
export type CustomCollectionObjectCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomCollectionObject
   */
  select?: Prisma.CustomCollectionObjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomCollectionObject
   */
  omit?: Prisma.CustomCollectionObjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomCollectionObjectInclude<ExtArgs> | null
  /**
   * The data needed to create a CustomCollectionObject.
   */
  data: Prisma.XOR<Prisma.CustomCollectionObjectCreateInput, Prisma.CustomCollectionObjectUncheckedCreateInput>
}

/**
 * CustomCollectionObject createMany
 */
export type CustomCollectionObjectCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CustomCollectionObjects.
   */
  data: Prisma.CustomCollectionObjectCreateManyInput | Prisma.CustomCollectionObjectCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CustomCollectionObject createManyAndReturn
 */
export type CustomCollectionObjectCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomCollectionObject
   */
  select?: Prisma.CustomCollectionObjectSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CustomCollectionObject
   */
  omit?: Prisma.CustomCollectionObjectOmit<ExtArgs> | null
  /**
   * The data used to create many CustomCollectionObjects.
   */
  data: Prisma.CustomCollectionObjectCreateManyInput | Prisma.CustomCollectionObjectCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomCollectionObjectIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CustomCollectionObject update
 */
export type CustomCollectionObjectUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomCollectionObject
   */
  select?: Prisma.CustomCollectionObjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomCollectionObject
   */
  omit?: Prisma.CustomCollectionObjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomCollectionObjectInclude<ExtArgs> | null
  /**
   * The data needed to update a CustomCollectionObject.
   */
  data: Prisma.XOR<Prisma.CustomCollectionObjectUpdateInput, Prisma.CustomCollectionObjectUncheckedUpdateInput>
  /**
   * Choose, which CustomCollectionObject to update.
   */
  where: Prisma.CustomCollectionObjectWhereUniqueInput
}

/**
 * CustomCollectionObject updateMany
 */
export type CustomCollectionObjectUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CustomCollectionObjects.
   */
  data: Prisma.XOR<Prisma.CustomCollectionObjectUpdateManyMutationInput, Prisma.CustomCollectionObjectUncheckedUpdateManyInput>
  /**
   * Filter which CustomCollectionObjects to update
   */
  where?: Prisma.CustomCollectionObjectWhereInput
  /**
   * Limit how many CustomCollectionObjects to update.
   */
  limit?: number
}

/**
 * CustomCollectionObject updateManyAndReturn
 */
export type CustomCollectionObjectUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomCollectionObject
   */
  select?: Prisma.CustomCollectionObjectSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CustomCollectionObject
   */
  omit?: Prisma.CustomCollectionObjectOmit<ExtArgs> | null
  /**
   * The data used to update CustomCollectionObjects.
   */
  data: Prisma.XOR<Prisma.CustomCollectionObjectUpdateManyMutationInput, Prisma.CustomCollectionObjectUncheckedUpdateManyInput>
  /**
   * Filter which CustomCollectionObjects to update
   */
  where?: Prisma.CustomCollectionObjectWhereInput
  /**
   * Limit how many CustomCollectionObjects to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomCollectionObjectIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CustomCollectionObject upsert
 */
export type CustomCollectionObjectUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomCollectionObject
   */
  select?: Prisma.CustomCollectionObjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomCollectionObject
   */
  omit?: Prisma.CustomCollectionObjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomCollectionObjectInclude<ExtArgs> | null
  /**
   * The filter to search for the CustomCollectionObject to update in case it exists.
   */
  where: Prisma.CustomCollectionObjectWhereUniqueInput
  /**
   * In case the CustomCollectionObject found by the `where` argument doesn't exist, create a new CustomCollectionObject with this data.
   */
  create: Prisma.XOR<Prisma.CustomCollectionObjectCreateInput, Prisma.CustomCollectionObjectUncheckedCreateInput>
  /**
   * In case the CustomCollectionObject was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CustomCollectionObjectUpdateInput, Prisma.CustomCollectionObjectUncheckedUpdateInput>
}

/**
 * CustomCollectionObject delete
 */
export type CustomCollectionObjectDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomCollectionObject
   */
  select?: Prisma.CustomCollectionObjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomCollectionObject
   */
  omit?: Prisma.CustomCollectionObjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomCollectionObjectInclude<ExtArgs> | null
  /**
   * Filter which CustomCollectionObject to delete.
   */
  where: Prisma.CustomCollectionObjectWhereUniqueInput
}

/**
 * CustomCollectionObject deleteMany
 */
export type CustomCollectionObjectDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CustomCollectionObjects to delete
   */
  where?: Prisma.CustomCollectionObjectWhereInput
  /**
   * Limit how many CustomCollectionObjects to delete.
   */
  limit?: number
}

/**
 * CustomCollectionObject without action
 */
export type CustomCollectionObjectDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomCollectionObject
   */
  select?: Prisma.CustomCollectionObjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomCollectionObject
   */
  omit?: Prisma.CustomCollectionObjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomCollectionObjectInclude<ExtArgs> | null
}
