
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Museum` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Museum
 * 
 */
export type MuseumModel = runtime.Types.Result.DefaultSelection<Prisma.$MuseumPayload>

export type AggregateMuseum = {
  _count: MuseumCountAggregateOutputType | null
  _avg: MuseumAvgAggregateOutputType | null
  _sum: MuseumSumAggregateOutputType | null
  _min: MuseumMinAggregateOutputType | null
  _max: MuseumMaxAggregateOutputType | null
}

export type MuseumAvgAggregateOutputType = {
  id: number | null
}

export type MuseumSumAggregateOutputType = {
  id: number | null
}

export type MuseumMinAggregateOutputType = {
  id: number | null
  userId: string | null
  title: string | null
  city: string | null
  exhibition: string | null
  date: Date | null
  discovered_by: string | null
  note: string | null
  imageUrl: string | null
  createdAt: Date | null
}

export type MuseumMaxAggregateOutputType = {
  id: number | null
  userId: string | null
  title: string | null
  city: string | null
  exhibition: string | null
  date: Date | null
  discovered_by: string | null
  note: string | null
  imageUrl: string | null
  createdAt: Date | null
}

export type MuseumCountAggregateOutputType = {
  id: number
  userId: number
  title: number
  city: number
  exhibition: number
  date: number
  discovered_by: number
  note: number
  imageUrl: number
  createdAt: number
  _all: number
}


export type MuseumAvgAggregateInputType = {
  id?: true
}

export type MuseumSumAggregateInputType = {
  id?: true
}

export type MuseumMinAggregateInputType = {
  id?: true
  userId?: true
  title?: true
  city?: true
  exhibition?: true
  date?: true
  discovered_by?: true
  note?: true
  imageUrl?: true
  createdAt?: true
}

export type MuseumMaxAggregateInputType = {
  id?: true
  userId?: true
  title?: true
  city?: true
  exhibition?: true
  date?: true
  discovered_by?: true
  note?: true
  imageUrl?: true
  createdAt?: true
}

export type MuseumCountAggregateInputType = {
  id?: true
  userId?: true
  title?: true
  city?: true
  exhibition?: true
  date?: true
  discovered_by?: true
  note?: true
  imageUrl?: true
  createdAt?: true
  _all?: true
}

export type MuseumAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Museum to aggregate.
   */
  where?: Prisma.MuseumWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Museums to fetch.
   */
  orderBy?: Prisma.MuseumOrderByWithRelationInput | Prisma.MuseumOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MuseumWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Museums from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Museums.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Museums
  **/
  _count?: true | MuseumCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MuseumAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MuseumSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MuseumMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MuseumMaxAggregateInputType
}

export type GetMuseumAggregateType<T extends MuseumAggregateArgs> = {
      [P in keyof T & keyof AggregateMuseum]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMuseum[P]>
    : Prisma.GetScalarType<T[P], AggregateMuseum[P]>
}




export type MuseumGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MuseumWhereInput
  orderBy?: Prisma.MuseumOrderByWithAggregationInput | Prisma.MuseumOrderByWithAggregationInput[]
  by: Prisma.MuseumScalarFieldEnum[] | Prisma.MuseumScalarFieldEnum
  having?: Prisma.MuseumScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MuseumCountAggregateInputType | true
  _avg?: MuseumAvgAggregateInputType
  _sum?: MuseumSumAggregateInputType
  _min?: MuseumMinAggregateInputType
  _max?: MuseumMaxAggregateInputType
}

export type MuseumGroupByOutputType = {
  id: number
  userId: string
  title: string
  city: string
  exhibition: string
  date: Date
  discovered_by: string
  note: string
  imageUrl: string | null
  createdAt: Date
  _count: MuseumCountAggregateOutputType | null
  _avg: MuseumAvgAggregateOutputType | null
  _sum: MuseumSumAggregateOutputType | null
  _min: MuseumMinAggregateOutputType | null
  _max: MuseumMaxAggregateOutputType | null
}

export type GetMuseumGroupByPayload<T extends MuseumGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MuseumGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MuseumGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MuseumGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MuseumGroupByOutputType[P]>
      }
    >
  >



export type MuseumWhereInput = {
  AND?: Prisma.MuseumWhereInput | Prisma.MuseumWhereInput[]
  OR?: Prisma.MuseumWhereInput[]
  NOT?: Prisma.MuseumWhereInput | Prisma.MuseumWhereInput[]
  id?: Prisma.IntFilter<"Museum"> | number
  userId?: Prisma.StringFilter<"Museum"> | string
  title?: Prisma.StringFilter<"Museum"> | string
  city?: Prisma.StringFilter<"Museum"> | string
  exhibition?: Prisma.StringFilter<"Museum"> | string
  date?: Prisma.DateTimeFilter<"Museum"> | Date | string
  discovered_by?: Prisma.StringFilter<"Museum"> | string
  note?: Prisma.StringFilter<"Museum"> | string
  imageUrl?: Prisma.StringNullableFilter<"Museum"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Museum"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type MuseumOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  city?: Prisma.SortOrder
  exhibition?: Prisma.SortOrder
  date?: Prisma.SortOrder
  discovered_by?: Prisma.SortOrder
  note?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type MuseumWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.MuseumWhereInput | Prisma.MuseumWhereInput[]
  OR?: Prisma.MuseumWhereInput[]
  NOT?: Prisma.MuseumWhereInput | Prisma.MuseumWhereInput[]
  userId?: Prisma.StringFilter<"Museum"> | string
  title?: Prisma.StringFilter<"Museum"> | string
  city?: Prisma.StringFilter<"Museum"> | string
  exhibition?: Prisma.StringFilter<"Museum"> | string
  date?: Prisma.DateTimeFilter<"Museum"> | Date | string
  discovered_by?: Prisma.StringFilter<"Museum"> | string
  note?: Prisma.StringFilter<"Museum"> | string
  imageUrl?: Prisma.StringNullableFilter<"Museum"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Museum"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type MuseumOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  city?: Prisma.SortOrder
  exhibition?: Prisma.SortOrder
  date?: Prisma.SortOrder
  discovered_by?: Prisma.SortOrder
  note?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.MuseumCountOrderByAggregateInput
  _avg?: Prisma.MuseumAvgOrderByAggregateInput
  _max?: Prisma.MuseumMaxOrderByAggregateInput
  _min?: Prisma.MuseumMinOrderByAggregateInput
  _sum?: Prisma.MuseumSumOrderByAggregateInput
}

export type MuseumScalarWhereWithAggregatesInput = {
  AND?: Prisma.MuseumScalarWhereWithAggregatesInput | Prisma.MuseumScalarWhereWithAggregatesInput[]
  OR?: Prisma.MuseumScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MuseumScalarWhereWithAggregatesInput | Prisma.MuseumScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Museum"> | number
  userId?: Prisma.StringWithAggregatesFilter<"Museum"> | string
  title?: Prisma.StringWithAggregatesFilter<"Museum"> | string
  city?: Prisma.StringWithAggregatesFilter<"Museum"> | string
  exhibition?: Prisma.StringWithAggregatesFilter<"Museum"> | string
  date?: Prisma.DateTimeWithAggregatesFilter<"Museum"> | Date | string
  discovered_by?: Prisma.StringWithAggregatesFilter<"Museum"> | string
  note?: Prisma.StringWithAggregatesFilter<"Museum"> | string
  imageUrl?: Prisma.StringNullableWithAggregatesFilter<"Museum"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Museum"> | Date | string
}

export type MuseumCreateInput = {
  title: string
  city: string
  exhibition: string
  date: Date | string
  discovered_by: string
  note: string
  imageUrl?: string | null
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutMuseumsInput
}

export type MuseumUncheckedCreateInput = {
  id?: number
  userId: string
  title: string
  city: string
  exhibition: string
  date: Date | string
  discovered_by: string
  note: string
  imageUrl?: string | null
  createdAt?: Date | string
}

export type MuseumUpdateInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  exhibition?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  discovered_by?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutMuseumsNestedInput
}

export type MuseumUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  exhibition?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  discovered_by?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MuseumCreateManyInput = {
  id?: number
  userId: string
  title: string
  city: string
  exhibition: string
  date: Date | string
  discovered_by: string
  note: string
  imageUrl?: string | null
  createdAt?: Date | string
}

export type MuseumUpdateManyMutationInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  exhibition?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  discovered_by?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MuseumUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  exhibition?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  discovered_by?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MuseumListRelationFilter = {
  every?: Prisma.MuseumWhereInput
  some?: Prisma.MuseumWhereInput
  none?: Prisma.MuseumWhereInput
}

export type MuseumOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type MuseumCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  city?: Prisma.SortOrder
  exhibition?: Prisma.SortOrder
  date?: Prisma.SortOrder
  discovered_by?: Prisma.SortOrder
  note?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type MuseumAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type MuseumMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  city?: Prisma.SortOrder
  exhibition?: Prisma.SortOrder
  date?: Prisma.SortOrder
  discovered_by?: Prisma.SortOrder
  note?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type MuseumMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  city?: Prisma.SortOrder
  exhibition?: Prisma.SortOrder
  date?: Prisma.SortOrder
  discovered_by?: Prisma.SortOrder
  note?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type MuseumSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type MuseumCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.MuseumCreateWithoutUserInput, Prisma.MuseumUncheckedCreateWithoutUserInput> | Prisma.MuseumCreateWithoutUserInput[] | Prisma.MuseumUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.MuseumCreateOrConnectWithoutUserInput | Prisma.MuseumCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.MuseumCreateManyUserInputEnvelope
  connect?: Prisma.MuseumWhereUniqueInput | Prisma.MuseumWhereUniqueInput[]
}

export type MuseumUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.MuseumCreateWithoutUserInput, Prisma.MuseumUncheckedCreateWithoutUserInput> | Prisma.MuseumCreateWithoutUserInput[] | Prisma.MuseumUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.MuseumCreateOrConnectWithoutUserInput | Prisma.MuseumCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.MuseumCreateManyUserInputEnvelope
  connect?: Prisma.MuseumWhereUniqueInput | Prisma.MuseumWhereUniqueInput[]
}

export type MuseumUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.MuseumCreateWithoutUserInput, Prisma.MuseumUncheckedCreateWithoutUserInput> | Prisma.MuseumCreateWithoutUserInput[] | Prisma.MuseumUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.MuseumCreateOrConnectWithoutUserInput | Prisma.MuseumCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.MuseumUpsertWithWhereUniqueWithoutUserInput | Prisma.MuseumUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.MuseumCreateManyUserInputEnvelope
  set?: Prisma.MuseumWhereUniqueInput | Prisma.MuseumWhereUniqueInput[]
  disconnect?: Prisma.MuseumWhereUniqueInput | Prisma.MuseumWhereUniqueInput[]
  delete?: Prisma.MuseumWhereUniqueInput | Prisma.MuseumWhereUniqueInput[]
  connect?: Prisma.MuseumWhereUniqueInput | Prisma.MuseumWhereUniqueInput[]
  update?: Prisma.MuseumUpdateWithWhereUniqueWithoutUserInput | Prisma.MuseumUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.MuseumUpdateManyWithWhereWithoutUserInput | Prisma.MuseumUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.MuseumScalarWhereInput | Prisma.MuseumScalarWhereInput[]
}

export type MuseumUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.MuseumCreateWithoutUserInput, Prisma.MuseumUncheckedCreateWithoutUserInput> | Prisma.MuseumCreateWithoutUserInput[] | Prisma.MuseumUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.MuseumCreateOrConnectWithoutUserInput | Prisma.MuseumCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.MuseumUpsertWithWhereUniqueWithoutUserInput | Prisma.MuseumUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.MuseumCreateManyUserInputEnvelope
  set?: Prisma.MuseumWhereUniqueInput | Prisma.MuseumWhereUniqueInput[]
  disconnect?: Prisma.MuseumWhereUniqueInput | Prisma.MuseumWhereUniqueInput[]
  delete?: Prisma.MuseumWhereUniqueInput | Prisma.MuseumWhereUniqueInput[]
  connect?: Prisma.MuseumWhereUniqueInput | Prisma.MuseumWhereUniqueInput[]
  update?: Prisma.MuseumUpdateWithWhereUniqueWithoutUserInput | Prisma.MuseumUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.MuseumUpdateManyWithWhereWithoutUserInput | Prisma.MuseumUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.MuseumScalarWhereInput | Prisma.MuseumScalarWhereInput[]
}

export type MuseumCreateWithoutUserInput = {
  title: string
  city: string
  exhibition: string
  date: Date | string
  discovered_by: string
  note: string
  imageUrl?: string | null
  createdAt?: Date | string
}

export type MuseumUncheckedCreateWithoutUserInput = {
  id?: number
  title: string
  city: string
  exhibition: string
  date: Date | string
  discovered_by: string
  note: string
  imageUrl?: string | null
  createdAt?: Date | string
}

export type MuseumCreateOrConnectWithoutUserInput = {
  where: Prisma.MuseumWhereUniqueInput
  create: Prisma.XOR<Prisma.MuseumCreateWithoutUserInput, Prisma.MuseumUncheckedCreateWithoutUserInput>
}

export type MuseumCreateManyUserInputEnvelope = {
  data: Prisma.MuseumCreateManyUserInput | Prisma.MuseumCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type MuseumUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.MuseumWhereUniqueInput
  update: Prisma.XOR<Prisma.MuseumUpdateWithoutUserInput, Prisma.MuseumUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.MuseumCreateWithoutUserInput, Prisma.MuseumUncheckedCreateWithoutUserInput>
}

export type MuseumUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.MuseumWhereUniqueInput
  data: Prisma.XOR<Prisma.MuseumUpdateWithoutUserInput, Prisma.MuseumUncheckedUpdateWithoutUserInput>
}

export type MuseumUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.MuseumScalarWhereInput
  data: Prisma.XOR<Prisma.MuseumUpdateManyMutationInput, Prisma.MuseumUncheckedUpdateManyWithoutUserInput>
}

export type MuseumScalarWhereInput = {
  AND?: Prisma.MuseumScalarWhereInput | Prisma.MuseumScalarWhereInput[]
  OR?: Prisma.MuseumScalarWhereInput[]
  NOT?: Prisma.MuseumScalarWhereInput | Prisma.MuseumScalarWhereInput[]
  id?: Prisma.IntFilter<"Museum"> | number
  userId?: Prisma.StringFilter<"Museum"> | string
  title?: Prisma.StringFilter<"Museum"> | string
  city?: Prisma.StringFilter<"Museum"> | string
  exhibition?: Prisma.StringFilter<"Museum"> | string
  date?: Prisma.DateTimeFilter<"Museum"> | Date | string
  discovered_by?: Prisma.StringFilter<"Museum"> | string
  note?: Prisma.StringFilter<"Museum"> | string
  imageUrl?: Prisma.StringNullableFilter<"Museum"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Museum"> | Date | string
}

export type MuseumCreateManyUserInput = {
  id?: number
  title: string
  city: string
  exhibition: string
  date: Date | string
  discovered_by: string
  note: string
  imageUrl?: string | null
  createdAt?: Date | string
}

export type MuseumUpdateWithoutUserInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  exhibition?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  discovered_by?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MuseumUncheckedUpdateWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  exhibition?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  discovered_by?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MuseumUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  exhibition?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  discovered_by?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type MuseumSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  title?: boolean
  city?: boolean
  exhibition?: boolean
  date?: boolean
  discovered_by?: boolean
  note?: boolean
  imageUrl?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["museum"]>

export type MuseumSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  title?: boolean
  city?: boolean
  exhibition?: boolean
  date?: boolean
  discovered_by?: boolean
  note?: boolean
  imageUrl?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["museum"]>

export type MuseumSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  title?: boolean
  city?: boolean
  exhibition?: boolean
  date?: boolean
  discovered_by?: boolean
  note?: boolean
  imageUrl?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["museum"]>

export type MuseumSelectScalar = {
  id?: boolean
  userId?: boolean
  title?: boolean
  city?: boolean
  exhibition?: boolean
  date?: boolean
  discovered_by?: boolean
  note?: boolean
  imageUrl?: boolean
  createdAt?: boolean
}

export type MuseumOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "title" | "city" | "exhibition" | "date" | "discovered_by" | "note" | "imageUrl" | "createdAt", ExtArgs["result"]["museum"]>
export type MuseumInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type MuseumIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type MuseumIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $MuseumPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Museum"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    userId: string
    title: string
    city: string
    exhibition: string
    date: Date
    discovered_by: string
    note: string
    imageUrl: string | null
    createdAt: Date
  }, ExtArgs["result"]["museum"]>
  composites: {}
}

export type MuseumGetPayload<S extends boolean | null | undefined | MuseumDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MuseumPayload, S>

export type MuseumCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MuseumFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MuseumCountAggregateInputType | true
  }

export interface MuseumDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Museum'], meta: { name: 'Museum' } }
  /**
   * Find zero or one Museum that matches the filter.
   * @param {MuseumFindUniqueArgs} args - Arguments to find a Museum
   * @example
   * // Get one Museum
   * const museum = await prisma.museum.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MuseumFindUniqueArgs>(args: Prisma.SelectSubset<T, MuseumFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MuseumClient<runtime.Types.Result.GetResult<Prisma.$MuseumPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Museum that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MuseumFindUniqueOrThrowArgs} args - Arguments to find a Museum
   * @example
   * // Get one Museum
   * const museum = await prisma.museum.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MuseumFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MuseumFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MuseumClient<runtime.Types.Result.GetResult<Prisma.$MuseumPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Museum that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MuseumFindFirstArgs} args - Arguments to find a Museum
   * @example
   * // Get one Museum
   * const museum = await prisma.museum.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MuseumFindFirstArgs>(args?: Prisma.SelectSubset<T, MuseumFindFirstArgs<ExtArgs>>): Prisma.Prisma__MuseumClient<runtime.Types.Result.GetResult<Prisma.$MuseumPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Museum that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MuseumFindFirstOrThrowArgs} args - Arguments to find a Museum
   * @example
   * // Get one Museum
   * const museum = await prisma.museum.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MuseumFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MuseumFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MuseumClient<runtime.Types.Result.GetResult<Prisma.$MuseumPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Museums that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MuseumFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Museums
   * const museums = await prisma.museum.findMany()
   * 
   * // Get first 10 Museums
   * const museums = await prisma.museum.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const museumWithIdOnly = await prisma.museum.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MuseumFindManyArgs>(args?: Prisma.SelectSubset<T, MuseumFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MuseumPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Museum.
   * @param {MuseumCreateArgs} args - Arguments to create a Museum.
   * @example
   * // Create one Museum
   * const Museum = await prisma.museum.create({
   *   data: {
   *     // ... data to create a Museum
   *   }
   * })
   * 
   */
  create<T extends MuseumCreateArgs>(args: Prisma.SelectSubset<T, MuseumCreateArgs<ExtArgs>>): Prisma.Prisma__MuseumClient<runtime.Types.Result.GetResult<Prisma.$MuseumPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Museums.
   * @param {MuseumCreateManyArgs} args - Arguments to create many Museums.
   * @example
   * // Create many Museums
   * const museum = await prisma.museum.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MuseumCreateManyArgs>(args?: Prisma.SelectSubset<T, MuseumCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Museums and returns the data saved in the database.
   * @param {MuseumCreateManyAndReturnArgs} args - Arguments to create many Museums.
   * @example
   * // Create many Museums
   * const museum = await prisma.museum.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Museums and only return the `id`
   * const museumWithIdOnly = await prisma.museum.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MuseumCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MuseumCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MuseumPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Museum.
   * @param {MuseumDeleteArgs} args - Arguments to delete one Museum.
   * @example
   * // Delete one Museum
   * const Museum = await prisma.museum.delete({
   *   where: {
   *     // ... filter to delete one Museum
   *   }
   * })
   * 
   */
  delete<T extends MuseumDeleteArgs>(args: Prisma.SelectSubset<T, MuseumDeleteArgs<ExtArgs>>): Prisma.Prisma__MuseumClient<runtime.Types.Result.GetResult<Prisma.$MuseumPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Museum.
   * @param {MuseumUpdateArgs} args - Arguments to update one Museum.
   * @example
   * // Update one Museum
   * const museum = await prisma.museum.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MuseumUpdateArgs>(args: Prisma.SelectSubset<T, MuseumUpdateArgs<ExtArgs>>): Prisma.Prisma__MuseumClient<runtime.Types.Result.GetResult<Prisma.$MuseumPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Museums.
   * @param {MuseumDeleteManyArgs} args - Arguments to filter Museums to delete.
   * @example
   * // Delete a few Museums
   * const { count } = await prisma.museum.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MuseumDeleteManyArgs>(args?: Prisma.SelectSubset<T, MuseumDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Museums.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MuseumUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Museums
   * const museum = await prisma.museum.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MuseumUpdateManyArgs>(args: Prisma.SelectSubset<T, MuseumUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Museums and returns the data updated in the database.
   * @param {MuseumUpdateManyAndReturnArgs} args - Arguments to update many Museums.
   * @example
   * // Update many Museums
   * const museum = await prisma.museum.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Museums and only return the `id`
   * const museumWithIdOnly = await prisma.museum.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MuseumUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MuseumUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MuseumPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Museum.
   * @param {MuseumUpsertArgs} args - Arguments to update or create a Museum.
   * @example
   * // Update or create a Museum
   * const museum = await prisma.museum.upsert({
   *   create: {
   *     // ... data to create a Museum
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Museum we want to update
   *   }
   * })
   */
  upsert<T extends MuseumUpsertArgs>(args: Prisma.SelectSubset<T, MuseumUpsertArgs<ExtArgs>>): Prisma.Prisma__MuseumClient<runtime.Types.Result.GetResult<Prisma.$MuseumPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Museums.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MuseumCountArgs} args - Arguments to filter Museums to count.
   * @example
   * // Count the number of Museums
   * const count = await prisma.museum.count({
   *   where: {
   *     // ... the filter for the Museums we want to count
   *   }
   * })
  **/
  count<T extends MuseumCountArgs>(
    args?: Prisma.Subset<T, MuseumCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MuseumCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Museum.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MuseumAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MuseumAggregateArgs>(args: Prisma.Subset<T, MuseumAggregateArgs>): Prisma.PrismaPromise<GetMuseumAggregateType<T>>

  /**
   * Group by Museum.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MuseumGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MuseumGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MuseumGroupByArgs['orderBy'] }
      : { orderBy?: MuseumGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MuseumGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMuseumGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Museum model
 */
readonly fields: MuseumFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Museum.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MuseumClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Museum model
 */
export interface MuseumFieldRefs {
  readonly id: Prisma.FieldRef<"Museum", 'Int'>
  readonly userId: Prisma.FieldRef<"Museum", 'String'>
  readonly title: Prisma.FieldRef<"Museum", 'String'>
  readonly city: Prisma.FieldRef<"Museum", 'String'>
  readonly exhibition: Prisma.FieldRef<"Museum", 'String'>
  readonly date: Prisma.FieldRef<"Museum", 'DateTime'>
  readonly discovered_by: Prisma.FieldRef<"Museum", 'String'>
  readonly note: Prisma.FieldRef<"Museum", 'String'>
  readonly imageUrl: Prisma.FieldRef<"Museum", 'String'>
  readonly createdAt: Prisma.FieldRef<"Museum", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Museum findUnique
 */
export type MuseumFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Museum
   */
  select?: Prisma.MuseumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Museum
   */
  omit?: Prisma.MuseumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MuseumInclude<ExtArgs> | null
  /**
   * Filter, which Museum to fetch.
   */
  where: Prisma.MuseumWhereUniqueInput
}

/**
 * Museum findUniqueOrThrow
 */
export type MuseumFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Museum
   */
  select?: Prisma.MuseumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Museum
   */
  omit?: Prisma.MuseumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MuseumInclude<ExtArgs> | null
  /**
   * Filter, which Museum to fetch.
   */
  where: Prisma.MuseumWhereUniqueInput
}

/**
 * Museum findFirst
 */
export type MuseumFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Museum
   */
  select?: Prisma.MuseumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Museum
   */
  omit?: Prisma.MuseumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MuseumInclude<ExtArgs> | null
  /**
   * Filter, which Museum to fetch.
   */
  where?: Prisma.MuseumWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Museums to fetch.
   */
  orderBy?: Prisma.MuseumOrderByWithRelationInput | Prisma.MuseumOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Museums.
   */
  cursor?: Prisma.MuseumWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Museums from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Museums.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Museums.
   */
  distinct?: Prisma.MuseumScalarFieldEnum | Prisma.MuseumScalarFieldEnum[]
}

/**
 * Museum findFirstOrThrow
 */
export type MuseumFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Museum
   */
  select?: Prisma.MuseumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Museum
   */
  omit?: Prisma.MuseumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MuseumInclude<ExtArgs> | null
  /**
   * Filter, which Museum to fetch.
   */
  where?: Prisma.MuseumWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Museums to fetch.
   */
  orderBy?: Prisma.MuseumOrderByWithRelationInput | Prisma.MuseumOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Museums.
   */
  cursor?: Prisma.MuseumWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Museums from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Museums.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Museums.
   */
  distinct?: Prisma.MuseumScalarFieldEnum | Prisma.MuseumScalarFieldEnum[]
}

/**
 * Museum findMany
 */
export type MuseumFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Museum
   */
  select?: Prisma.MuseumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Museum
   */
  omit?: Prisma.MuseumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MuseumInclude<ExtArgs> | null
  /**
   * Filter, which Museums to fetch.
   */
  where?: Prisma.MuseumWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Museums to fetch.
   */
  orderBy?: Prisma.MuseumOrderByWithRelationInput | Prisma.MuseumOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Museums.
   */
  cursor?: Prisma.MuseumWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Museums from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Museums.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Museums.
   */
  distinct?: Prisma.MuseumScalarFieldEnum | Prisma.MuseumScalarFieldEnum[]
}

/**
 * Museum create
 */
export type MuseumCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Museum
   */
  select?: Prisma.MuseumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Museum
   */
  omit?: Prisma.MuseumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MuseumInclude<ExtArgs> | null
  /**
   * The data needed to create a Museum.
   */
  data: Prisma.XOR<Prisma.MuseumCreateInput, Prisma.MuseumUncheckedCreateInput>
}

/**
 * Museum createMany
 */
export type MuseumCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Museums.
   */
  data: Prisma.MuseumCreateManyInput | Prisma.MuseumCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Museum createManyAndReturn
 */
export type MuseumCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Museum
   */
  select?: Prisma.MuseumSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Museum
   */
  omit?: Prisma.MuseumOmit<ExtArgs> | null
  /**
   * The data used to create many Museums.
   */
  data: Prisma.MuseumCreateManyInput | Prisma.MuseumCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MuseumIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Museum update
 */
export type MuseumUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Museum
   */
  select?: Prisma.MuseumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Museum
   */
  omit?: Prisma.MuseumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MuseumInclude<ExtArgs> | null
  /**
   * The data needed to update a Museum.
   */
  data: Prisma.XOR<Prisma.MuseumUpdateInput, Prisma.MuseumUncheckedUpdateInput>
  /**
   * Choose, which Museum to update.
   */
  where: Prisma.MuseumWhereUniqueInput
}

/**
 * Museum updateMany
 */
export type MuseumUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Museums.
   */
  data: Prisma.XOR<Prisma.MuseumUpdateManyMutationInput, Prisma.MuseumUncheckedUpdateManyInput>
  /**
   * Filter which Museums to update
   */
  where?: Prisma.MuseumWhereInput
  /**
   * Limit how many Museums to update.
   */
  limit?: number
}

/**
 * Museum updateManyAndReturn
 */
export type MuseumUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Museum
   */
  select?: Prisma.MuseumSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Museum
   */
  omit?: Prisma.MuseumOmit<ExtArgs> | null
  /**
   * The data used to update Museums.
   */
  data: Prisma.XOR<Prisma.MuseumUpdateManyMutationInput, Prisma.MuseumUncheckedUpdateManyInput>
  /**
   * Filter which Museums to update
   */
  where?: Prisma.MuseumWhereInput
  /**
   * Limit how many Museums to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MuseumIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Museum upsert
 */
export type MuseumUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Museum
   */
  select?: Prisma.MuseumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Museum
   */
  omit?: Prisma.MuseumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MuseumInclude<ExtArgs> | null
  /**
   * The filter to search for the Museum to update in case it exists.
   */
  where: Prisma.MuseumWhereUniqueInput
  /**
   * In case the Museum found by the `where` argument doesn't exist, create a new Museum with this data.
   */
  create: Prisma.XOR<Prisma.MuseumCreateInput, Prisma.MuseumUncheckedCreateInput>
  /**
   * In case the Museum was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MuseumUpdateInput, Prisma.MuseumUncheckedUpdateInput>
}

/**
 * Museum delete
 */
export type MuseumDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Museum
   */
  select?: Prisma.MuseumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Museum
   */
  omit?: Prisma.MuseumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MuseumInclude<ExtArgs> | null
  /**
   * Filter which Museum to delete.
   */
  where: Prisma.MuseumWhereUniqueInput
}

/**
 * Museum deleteMany
 */
export type MuseumDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Museums to delete
   */
  where?: Prisma.MuseumWhereInput
  /**
   * Limit how many Museums to delete.
   */
  limit?: number
}

/**
 * Museum without action
 */
export type MuseumDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Museum
   */
  select?: Prisma.MuseumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Museum
   */
  omit?: Prisma.MuseumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MuseumInclude<ExtArgs> | null
}
