
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Music` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Music
 * 
 */
export type MusicModel = runtime.Types.Result.DefaultSelection<Prisma.$MusicPayload>

export type AggregateMusic = {
  _count: MusicCountAggregateOutputType | null
  _avg: MusicAvgAggregateOutputType | null
  _sum: MusicSumAggregateOutputType | null
  _min: MusicMinAggregateOutputType | null
  _max: MusicMaxAggregateOutputType | null
}

export type MusicAvgAggregateOutputType = {
  id: number | null
}

export type MusicSumAggregateOutputType = {
  id: number | null
}

export type MusicMinAggregateOutputType = {
  id: number | null
  userId: string | null
  format: string | null
  title: string | null
  author: string | null
  year: string | null
  discovered_by: string | null
  note: string | null
  bestQuote: string | null
  imageUrl: string | null
  createdAt: Date | null
}

export type MusicMaxAggregateOutputType = {
  id: number | null
  userId: string | null
  format: string | null
  title: string | null
  author: string | null
  year: string | null
  discovered_by: string | null
  note: string | null
  bestQuote: string | null
  imageUrl: string | null
  createdAt: Date | null
}

export type MusicCountAggregateOutputType = {
  id: number
  userId: number
  format: number
  title: number
  author: number
  year: number
  discovered_by: number
  note: number
  bestQuote: number
  imageUrl: number
  createdAt: number
  _all: number
}


export type MusicAvgAggregateInputType = {
  id?: true
}

export type MusicSumAggregateInputType = {
  id?: true
}

export type MusicMinAggregateInputType = {
  id?: true
  userId?: true
  format?: true
  title?: true
  author?: true
  year?: true
  discovered_by?: true
  note?: true
  bestQuote?: true
  imageUrl?: true
  createdAt?: true
}

export type MusicMaxAggregateInputType = {
  id?: true
  userId?: true
  format?: true
  title?: true
  author?: true
  year?: true
  discovered_by?: true
  note?: true
  bestQuote?: true
  imageUrl?: true
  createdAt?: true
}

export type MusicCountAggregateInputType = {
  id?: true
  userId?: true
  format?: true
  title?: true
  author?: true
  year?: true
  discovered_by?: true
  note?: true
  bestQuote?: true
  imageUrl?: true
  createdAt?: true
  _all?: true
}

export type MusicAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Music to aggregate.
   */
  where?: Prisma.MusicWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Music to fetch.
   */
  orderBy?: Prisma.MusicOrderByWithRelationInput | Prisma.MusicOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MusicWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Music from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Music.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Music
  **/
  _count?: true | MusicCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MusicAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MusicSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MusicMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MusicMaxAggregateInputType
}

export type GetMusicAggregateType<T extends MusicAggregateArgs> = {
      [P in keyof T & keyof AggregateMusic]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMusic[P]>
    : Prisma.GetScalarType<T[P], AggregateMusic[P]>
}




export type MusicGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MusicWhereInput
  orderBy?: Prisma.MusicOrderByWithAggregationInput | Prisma.MusicOrderByWithAggregationInput[]
  by: Prisma.MusicScalarFieldEnum[] | Prisma.MusicScalarFieldEnum
  having?: Prisma.MusicScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MusicCountAggregateInputType | true
  _avg?: MusicAvgAggregateInputType
  _sum?: MusicSumAggregateInputType
  _min?: MusicMinAggregateInputType
  _max?: MusicMaxAggregateInputType
}

export type MusicGroupByOutputType = {
  id: number
  userId: string
  format: string
  title: string
  author: string
  year: string
  discovered_by: string
  note: string
  bestQuote: string
  imageUrl: string | null
  createdAt: Date
  _count: MusicCountAggregateOutputType | null
  _avg: MusicAvgAggregateOutputType | null
  _sum: MusicSumAggregateOutputType | null
  _min: MusicMinAggregateOutputType | null
  _max: MusicMaxAggregateOutputType | null
}

export type GetMusicGroupByPayload<T extends MusicGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MusicGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MusicGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MusicGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MusicGroupByOutputType[P]>
      }
    >
  >



export type MusicWhereInput = {
  AND?: Prisma.MusicWhereInput | Prisma.MusicWhereInput[]
  OR?: Prisma.MusicWhereInput[]
  NOT?: Prisma.MusicWhereInput | Prisma.MusicWhereInput[]
  id?: Prisma.IntFilter<"Music"> | number
  userId?: Prisma.StringFilter<"Music"> | string
  format?: Prisma.StringFilter<"Music"> | string
  title?: Prisma.StringFilter<"Music"> | string
  author?: Prisma.StringFilter<"Music"> | string
  year?: Prisma.StringFilter<"Music"> | string
  discovered_by?: Prisma.StringFilter<"Music"> | string
  note?: Prisma.StringFilter<"Music"> | string
  bestQuote?: Prisma.StringFilter<"Music"> | string
  imageUrl?: Prisma.StringNullableFilter<"Music"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Music"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type MusicOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  format?: Prisma.SortOrder
  title?: Prisma.SortOrder
  author?: Prisma.SortOrder
  year?: Prisma.SortOrder
  discovered_by?: Prisma.SortOrder
  note?: Prisma.SortOrder
  bestQuote?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type MusicWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.MusicWhereInput | Prisma.MusicWhereInput[]
  OR?: Prisma.MusicWhereInput[]
  NOT?: Prisma.MusicWhereInput | Prisma.MusicWhereInput[]
  userId?: Prisma.StringFilter<"Music"> | string
  format?: Prisma.StringFilter<"Music"> | string
  title?: Prisma.StringFilter<"Music"> | string
  author?: Prisma.StringFilter<"Music"> | string
  year?: Prisma.StringFilter<"Music"> | string
  discovered_by?: Prisma.StringFilter<"Music"> | string
  note?: Prisma.StringFilter<"Music"> | string
  bestQuote?: Prisma.StringFilter<"Music"> | string
  imageUrl?: Prisma.StringNullableFilter<"Music"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Music"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type MusicOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  format?: Prisma.SortOrder
  title?: Prisma.SortOrder
  author?: Prisma.SortOrder
  year?: Prisma.SortOrder
  discovered_by?: Prisma.SortOrder
  note?: Prisma.SortOrder
  bestQuote?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.MusicCountOrderByAggregateInput
  _avg?: Prisma.MusicAvgOrderByAggregateInput
  _max?: Prisma.MusicMaxOrderByAggregateInput
  _min?: Prisma.MusicMinOrderByAggregateInput
  _sum?: Prisma.MusicSumOrderByAggregateInput
}

export type MusicScalarWhereWithAggregatesInput = {
  AND?: Prisma.MusicScalarWhereWithAggregatesInput | Prisma.MusicScalarWhereWithAggregatesInput[]
  OR?: Prisma.MusicScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MusicScalarWhereWithAggregatesInput | Prisma.MusicScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Music"> | number
  userId?: Prisma.StringWithAggregatesFilter<"Music"> | string
  format?: Prisma.StringWithAggregatesFilter<"Music"> | string
  title?: Prisma.StringWithAggregatesFilter<"Music"> | string
  author?: Prisma.StringWithAggregatesFilter<"Music"> | string
  year?: Prisma.StringWithAggregatesFilter<"Music"> | string
  discovered_by?: Prisma.StringWithAggregatesFilter<"Music"> | string
  note?: Prisma.StringWithAggregatesFilter<"Music"> | string
  bestQuote?: Prisma.StringWithAggregatesFilter<"Music"> | string
  imageUrl?: Prisma.StringNullableWithAggregatesFilter<"Music"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Music"> | Date | string
}

export type MusicCreateInput = {
  format: string
  title: string
  author: string
  year: string
  discovered_by: string
  note: string
  bestQuote: string
  imageUrl?: string | null
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutMusicInput
}

export type MusicUncheckedCreateInput = {
  id?: number
  userId: string
  format: string
  title: string
  author: string
  year: string
  discovered_by: string
  note: string
  bestQuote: string
  imageUrl?: string | null
  createdAt?: Date | string
}

export type MusicUpdateInput = {
  format?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  author?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.StringFieldUpdateOperationsInput | string
  discovered_by?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.StringFieldUpdateOperationsInput | string
  bestQuote?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutMusicNestedInput
}

export type MusicUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  format?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  author?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.StringFieldUpdateOperationsInput | string
  discovered_by?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.StringFieldUpdateOperationsInput | string
  bestQuote?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MusicCreateManyInput = {
  id?: number
  userId: string
  format: string
  title: string
  author: string
  year: string
  discovered_by: string
  note: string
  bestQuote: string
  imageUrl?: string | null
  createdAt?: Date | string
}

export type MusicUpdateManyMutationInput = {
  format?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  author?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.StringFieldUpdateOperationsInput | string
  discovered_by?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.StringFieldUpdateOperationsInput | string
  bestQuote?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MusicUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  format?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  author?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.StringFieldUpdateOperationsInput | string
  discovered_by?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.StringFieldUpdateOperationsInput | string
  bestQuote?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MusicListRelationFilter = {
  every?: Prisma.MusicWhereInput
  some?: Prisma.MusicWhereInput
  none?: Prisma.MusicWhereInput
}

export type MusicOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type MusicCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  format?: Prisma.SortOrder
  title?: Prisma.SortOrder
  author?: Prisma.SortOrder
  year?: Prisma.SortOrder
  discovered_by?: Prisma.SortOrder
  note?: Prisma.SortOrder
  bestQuote?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type MusicAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type MusicMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  format?: Prisma.SortOrder
  title?: Prisma.SortOrder
  author?: Prisma.SortOrder
  year?: Prisma.SortOrder
  discovered_by?: Prisma.SortOrder
  note?: Prisma.SortOrder
  bestQuote?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type MusicMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  format?: Prisma.SortOrder
  title?: Prisma.SortOrder
  author?: Prisma.SortOrder
  year?: Prisma.SortOrder
  discovered_by?: Prisma.SortOrder
  note?: Prisma.SortOrder
  bestQuote?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type MusicSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type MusicCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.MusicCreateWithoutUserInput, Prisma.MusicUncheckedCreateWithoutUserInput> | Prisma.MusicCreateWithoutUserInput[] | Prisma.MusicUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.MusicCreateOrConnectWithoutUserInput | Prisma.MusicCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.MusicCreateManyUserInputEnvelope
  connect?: Prisma.MusicWhereUniqueInput | Prisma.MusicWhereUniqueInput[]
}

export type MusicUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.MusicCreateWithoutUserInput, Prisma.MusicUncheckedCreateWithoutUserInput> | Prisma.MusicCreateWithoutUserInput[] | Prisma.MusicUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.MusicCreateOrConnectWithoutUserInput | Prisma.MusicCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.MusicCreateManyUserInputEnvelope
  connect?: Prisma.MusicWhereUniqueInput | Prisma.MusicWhereUniqueInput[]
}

export type MusicUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.MusicCreateWithoutUserInput, Prisma.MusicUncheckedCreateWithoutUserInput> | Prisma.MusicCreateWithoutUserInput[] | Prisma.MusicUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.MusicCreateOrConnectWithoutUserInput | Prisma.MusicCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.MusicUpsertWithWhereUniqueWithoutUserInput | Prisma.MusicUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.MusicCreateManyUserInputEnvelope
  set?: Prisma.MusicWhereUniqueInput | Prisma.MusicWhereUniqueInput[]
  disconnect?: Prisma.MusicWhereUniqueInput | Prisma.MusicWhereUniqueInput[]
  delete?: Prisma.MusicWhereUniqueInput | Prisma.MusicWhereUniqueInput[]
  connect?: Prisma.MusicWhereUniqueInput | Prisma.MusicWhereUniqueInput[]
  update?: Prisma.MusicUpdateWithWhereUniqueWithoutUserInput | Prisma.MusicUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.MusicUpdateManyWithWhereWithoutUserInput | Prisma.MusicUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.MusicScalarWhereInput | Prisma.MusicScalarWhereInput[]
}

export type MusicUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.MusicCreateWithoutUserInput, Prisma.MusicUncheckedCreateWithoutUserInput> | Prisma.MusicCreateWithoutUserInput[] | Prisma.MusicUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.MusicCreateOrConnectWithoutUserInput | Prisma.MusicCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.MusicUpsertWithWhereUniqueWithoutUserInput | Prisma.MusicUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.MusicCreateManyUserInputEnvelope
  set?: Prisma.MusicWhereUniqueInput | Prisma.MusicWhereUniqueInput[]
  disconnect?: Prisma.MusicWhereUniqueInput | Prisma.MusicWhereUniqueInput[]
  delete?: Prisma.MusicWhereUniqueInput | Prisma.MusicWhereUniqueInput[]
  connect?: Prisma.MusicWhereUniqueInput | Prisma.MusicWhereUniqueInput[]
  update?: Prisma.MusicUpdateWithWhereUniqueWithoutUserInput | Prisma.MusicUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.MusicUpdateManyWithWhereWithoutUserInput | Prisma.MusicUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.MusicScalarWhereInput | Prisma.MusicScalarWhereInput[]
}

export type MusicCreateWithoutUserInput = {
  format: string
  title: string
  author: string
  year: string
  discovered_by: string
  note: string
  bestQuote: string
  imageUrl?: string | null
  createdAt?: Date | string
}

export type MusicUncheckedCreateWithoutUserInput = {
  id?: number
  format: string
  title: string
  author: string
  year: string
  discovered_by: string
  note: string
  bestQuote: string
  imageUrl?: string | null
  createdAt?: Date | string
}

export type MusicCreateOrConnectWithoutUserInput = {
  where: Prisma.MusicWhereUniqueInput
  create: Prisma.XOR<Prisma.MusicCreateWithoutUserInput, Prisma.MusicUncheckedCreateWithoutUserInput>
}

export type MusicCreateManyUserInputEnvelope = {
  data: Prisma.MusicCreateManyUserInput | Prisma.MusicCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type MusicUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.MusicWhereUniqueInput
  update: Prisma.XOR<Prisma.MusicUpdateWithoutUserInput, Prisma.MusicUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.MusicCreateWithoutUserInput, Prisma.MusicUncheckedCreateWithoutUserInput>
}

export type MusicUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.MusicWhereUniqueInput
  data: Prisma.XOR<Prisma.MusicUpdateWithoutUserInput, Prisma.MusicUncheckedUpdateWithoutUserInput>
}

export type MusicUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.MusicScalarWhereInput
  data: Prisma.XOR<Prisma.MusicUpdateManyMutationInput, Prisma.MusicUncheckedUpdateManyWithoutUserInput>
}

export type MusicScalarWhereInput = {
  AND?: Prisma.MusicScalarWhereInput | Prisma.MusicScalarWhereInput[]
  OR?: Prisma.MusicScalarWhereInput[]
  NOT?: Prisma.MusicScalarWhereInput | Prisma.MusicScalarWhereInput[]
  id?: Prisma.IntFilter<"Music"> | number
  userId?: Prisma.StringFilter<"Music"> | string
  format?: Prisma.StringFilter<"Music"> | string
  title?: Prisma.StringFilter<"Music"> | string
  author?: Prisma.StringFilter<"Music"> | string
  year?: Prisma.StringFilter<"Music"> | string
  discovered_by?: Prisma.StringFilter<"Music"> | string
  note?: Prisma.StringFilter<"Music"> | string
  bestQuote?: Prisma.StringFilter<"Music"> | string
  imageUrl?: Prisma.StringNullableFilter<"Music"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Music"> | Date | string
}

export type MusicCreateManyUserInput = {
  id?: number
  format: string
  title: string
  author: string
  year: string
  discovered_by: string
  note: string
  bestQuote: string
  imageUrl?: string | null
  createdAt?: Date | string
}

export type MusicUpdateWithoutUserInput = {
  format?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  author?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.StringFieldUpdateOperationsInput | string
  discovered_by?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.StringFieldUpdateOperationsInput | string
  bestQuote?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MusicUncheckedUpdateWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  format?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  author?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.StringFieldUpdateOperationsInput | string
  discovered_by?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.StringFieldUpdateOperationsInput | string
  bestQuote?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MusicUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  format?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  author?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.StringFieldUpdateOperationsInput | string
  discovered_by?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.StringFieldUpdateOperationsInput | string
  bestQuote?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type MusicSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  format?: boolean
  title?: boolean
  author?: boolean
  year?: boolean
  discovered_by?: boolean
  note?: boolean
  bestQuote?: boolean
  imageUrl?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["music"]>

export type MusicSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  format?: boolean
  title?: boolean
  author?: boolean
  year?: boolean
  discovered_by?: boolean
  note?: boolean
  bestQuote?: boolean
  imageUrl?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["music"]>

export type MusicSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  format?: boolean
  title?: boolean
  author?: boolean
  year?: boolean
  discovered_by?: boolean
  note?: boolean
  bestQuote?: boolean
  imageUrl?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["music"]>

export type MusicSelectScalar = {
  id?: boolean
  userId?: boolean
  format?: boolean
  title?: boolean
  author?: boolean
  year?: boolean
  discovered_by?: boolean
  note?: boolean
  bestQuote?: boolean
  imageUrl?: boolean
  createdAt?: boolean
}

export type MusicOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "format" | "title" | "author" | "year" | "discovered_by" | "note" | "bestQuote" | "imageUrl" | "createdAt", ExtArgs["result"]["music"]>
export type MusicInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type MusicIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type MusicIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $MusicPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Music"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    userId: string
    format: string
    title: string
    author: string
    year: string
    discovered_by: string
    note: string
    bestQuote: string
    imageUrl: string | null
    createdAt: Date
  }, ExtArgs["result"]["music"]>
  composites: {}
}

export type MusicGetPayload<S extends boolean | null | undefined | MusicDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MusicPayload, S>

export type MusicCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MusicFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MusicCountAggregateInputType | true
  }

export interface MusicDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Music'], meta: { name: 'Music' } }
  /**
   * Find zero or one Music that matches the filter.
   * @param {MusicFindUniqueArgs} args - Arguments to find a Music
   * @example
   * // Get one Music
   * const music = await prisma.music.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MusicFindUniqueArgs>(args: Prisma.SelectSubset<T, MusicFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MusicClient<runtime.Types.Result.GetResult<Prisma.$MusicPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Music that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MusicFindUniqueOrThrowArgs} args - Arguments to find a Music
   * @example
   * // Get one Music
   * const music = await prisma.music.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MusicFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MusicFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MusicClient<runtime.Types.Result.GetResult<Prisma.$MusicPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Music that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MusicFindFirstArgs} args - Arguments to find a Music
   * @example
   * // Get one Music
   * const music = await prisma.music.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MusicFindFirstArgs>(args?: Prisma.SelectSubset<T, MusicFindFirstArgs<ExtArgs>>): Prisma.Prisma__MusicClient<runtime.Types.Result.GetResult<Prisma.$MusicPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Music that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MusicFindFirstOrThrowArgs} args - Arguments to find a Music
   * @example
   * // Get one Music
   * const music = await prisma.music.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MusicFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MusicFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MusicClient<runtime.Types.Result.GetResult<Prisma.$MusicPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Music that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MusicFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Music
   * const music = await prisma.music.findMany()
   * 
   * // Get first 10 Music
   * const music = await prisma.music.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const musicWithIdOnly = await prisma.music.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MusicFindManyArgs>(args?: Prisma.SelectSubset<T, MusicFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MusicPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Music.
   * @param {MusicCreateArgs} args - Arguments to create a Music.
   * @example
   * // Create one Music
   * const Music = await prisma.music.create({
   *   data: {
   *     // ... data to create a Music
   *   }
   * })
   * 
   */
  create<T extends MusicCreateArgs>(args: Prisma.SelectSubset<T, MusicCreateArgs<ExtArgs>>): Prisma.Prisma__MusicClient<runtime.Types.Result.GetResult<Prisma.$MusicPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Music.
   * @param {MusicCreateManyArgs} args - Arguments to create many Music.
   * @example
   * // Create many Music
   * const music = await prisma.music.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MusicCreateManyArgs>(args?: Prisma.SelectSubset<T, MusicCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Music and returns the data saved in the database.
   * @param {MusicCreateManyAndReturnArgs} args - Arguments to create many Music.
   * @example
   * // Create many Music
   * const music = await prisma.music.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Music and only return the `id`
   * const musicWithIdOnly = await prisma.music.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MusicCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MusicCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MusicPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Music.
   * @param {MusicDeleteArgs} args - Arguments to delete one Music.
   * @example
   * // Delete one Music
   * const Music = await prisma.music.delete({
   *   where: {
   *     // ... filter to delete one Music
   *   }
   * })
   * 
   */
  delete<T extends MusicDeleteArgs>(args: Prisma.SelectSubset<T, MusicDeleteArgs<ExtArgs>>): Prisma.Prisma__MusicClient<runtime.Types.Result.GetResult<Prisma.$MusicPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Music.
   * @param {MusicUpdateArgs} args - Arguments to update one Music.
   * @example
   * // Update one Music
   * const music = await prisma.music.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MusicUpdateArgs>(args: Prisma.SelectSubset<T, MusicUpdateArgs<ExtArgs>>): Prisma.Prisma__MusicClient<runtime.Types.Result.GetResult<Prisma.$MusicPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Music.
   * @param {MusicDeleteManyArgs} args - Arguments to filter Music to delete.
   * @example
   * // Delete a few Music
   * const { count } = await prisma.music.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MusicDeleteManyArgs>(args?: Prisma.SelectSubset<T, MusicDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Music.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MusicUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Music
   * const music = await prisma.music.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MusicUpdateManyArgs>(args: Prisma.SelectSubset<T, MusicUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Music and returns the data updated in the database.
   * @param {MusicUpdateManyAndReturnArgs} args - Arguments to update many Music.
   * @example
   * // Update many Music
   * const music = await prisma.music.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Music and only return the `id`
   * const musicWithIdOnly = await prisma.music.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MusicUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MusicUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MusicPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Music.
   * @param {MusicUpsertArgs} args - Arguments to update or create a Music.
   * @example
   * // Update or create a Music
   * const music = await prisma.music.upsert({
   *   create: {
   *     // ... data to create a Music
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Music we want to update
   *   }
   * })
   */
  upsert<T extends MusicUpsertArgs>(args: Prisma.SelectSubset<T, MusicUpsertArgs<ExtArgs>>): Prisma.Prisma__MusicClient<runtime.Types.Result.GetResult<Prisma.$MusicPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Music.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MusicCountArgs} args - Arguments to filter Music to count.
   * @example
   * // Count the number of Music
   * const count = await prisma.music.count({
   *   where: {
   *     // ... the filter for the Music we want to count
   *   }
   * })
  **/
  count<T extends MusicCountArgs>(
    args?: Prisma.Subset<T, MusicCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MusicCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Music.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MusicAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MusicAggregateArgs>(args: Prisma.Subset<T, MusicAggregateArgs>): Prisma.PrismaPromise<GetMusicAggregateType<T>>

  /**
   * Group by Music.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MusicGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MusicGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MusicGroupByArgs['orderBy'] }
      : { orderBy?: MusicGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MusicGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMusicGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Music model
 */
readonly fields: MusicFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Music.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MusicClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Music model
 */
export interface MusicFieldRefs {
  readonly id: Prisma.FieldRef<"Music", 'Int'>
  readonly userId: Prisma.FieldRef<"Music", 'String'>
  readonly format: Prisma.FieldRef<"Music", 'String'>
  readonly title: Prisma.FieldRef<"Music", 'String'>
  readonly author: Prisma.FieldRef<"Music", 'String'>
  readonly year: Prisma.FieldRef<"Music", 'String'>
  readonly discovered_by: Prisma.FieldRef<"Music", 'String'>
  readonly note: Prisma.FieldRef<"Music", 'String'>
  readonly bestQuote: Prisma.FieldRef<"Music", 'String'>
  readonly imageUrl: Prisma.FieldRef<"Music", 'String'>
  readonly createdAt: Prisma.FieldRef<"Music", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Music findUnique
 */
export type MusicFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Music
   */
  select?: Prisma.MusicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Music
   */
  omit?: Prisma.MusicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MusicInclude<ExtArgs> | null
  /**
   * Filter, which Music to fetch.
   */
  where: Prisma.MusicWhereUniqueInput
}

/**
 * Music findUniqueOrThrow
 */
export type MusicFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Music
   */
  select?: Prisma.MusicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Music
   */
  omit?: Prisma.MusicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MusicInclude<ExtArgs> | null
  /**
   * Filter, which Music to fetch.
   */
  where: Prisma.MusicWhereUniqueInput
}

/**
 * Music findFirst
 */
export type MusicFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Music
   */
  select?: Prisma.MusicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Music
   */
  omit?: Prisma.MusicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MusicInclude<ExtArgs> | null
  /**
   * Filter, which Music to fetch.
   */
  where?: Prisma.MusicWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Music to fetch.
   */
  orderBy?: Prisma.MusicOrderByWithRelationInput | Prisma.MusicOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Music.
   */
  cursor?: Prisma.MusicWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Music from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Music.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Music.
   */
  distinct?: Prisma.MusicScalarFieldEnum | Prisma.MusicScalarFieldEnum[]
}

/**
 * Music findFirstOrThrow
 */
export type MusicFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Music
   */
  select?: Prisma.MusicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Music
   */
  omit?: Prisma.MusicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MusicInclude<ExtArgs> | null
  /**
   * Filter, which Music to fetch.
   */
  where?: Prisma.MusicWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Music to fetch.
   */
  orderBy?: Prisma.MusicOrderByWithRelationInput | Prisma.MusicOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Music.
   */
  cursor?: Prisma.MusicWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Music from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Music.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Music.
   */
  distinct?: Prisma.MusicScalarFieldEnum | Prisma.MusicScalarFieldEnum[]
}

/**
 * Music findMany
 */
export type MusicFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Music
   */
  select?: Prisma.MusicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Music
   */
  omit?: Prisma.MusicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MusicInclude<ExtArgs> | null
  /**
   * Filter, which Music to fetch.
   */
  where?: Prisma.MusicWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Music to fetch.
   */
  orderBy?: Prisma.MusicOrderByWithRelationInput | Prisma.MusicOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Music.
   */
  cursor?: Prisma.MusicWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Music from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Music.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Music.
   */
  distinct?: Prisma.MusicScalarFieldEnum | Prisma.MusicScalarFieldEnum[]
}

/**
 * Music create
 */
export type MusicCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Music
   */
  select?: Prisma.MusicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Music
   */
  omit?: Prisma.MusicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MusicInclude<ExtArgs> | null
  /**
   * The data needed to create a Music.
   */
  data: Prisma.XOR<Prisma.MusicCreateInput, Prisma.MusicUncheckedCreateInput>
}

/**
 * Music createMany
 */
export type MusicCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Music.
   */
  data: Prisma.MusicCreateManyInput | Prisma.MusicCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Music createManyAndReturn
 */
export type MusicCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Music
   */
  select?: Prisma.MusicSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Music
   */
  omit?: Prisma.MusicOmit<ExtArgs> | null
  /**
   * The data used to create many Music.
   */
  data: Prisma.MusicCreateManyInput | Prisma.MusicCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MusicIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Music update
 */
export type MusicUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Music
   */
  select?: Prisma.MusicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Music
   */
  omit?: Prisma.MusicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MusicInclude<ExtArgs> | null
  /**
   * The data needed to update a Music.
   */
  data: Prisma.XOR<Prisma.MusicUpdateInput, Prisma.MusicUncheckedUpdateInput>
  /**
   * Choose, which Music to update.
   */
  where: Prisma.MusicWhereUniqueInput
}

/**
 * Music updateMany
 */
export type MusicUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Music.
   */
  data: Prisma.XOR<Prisma.MusicUpdateManyMutationInput, Prisma.MusicUncheckedUpdateManyInput>
  /**
   * Filter which Music to update
   */
  where?: Prisma.MusicWhereInput
  /**
   * Limit how many Music to update.
   */
  limit?: number
}

/**
 * Music updateManyAndReturn
 */
export type MusicUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Music
   */
  select?: Prisma.MusicSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Music
   */
  omit?: Prisma.MusicOmit<ExtArgs> | null
  /**
   * The data used to update Music.
   */
  data: Prisma.XOR<Prisma.MusicUpdateManyMutationInput, Prisma.MusicUncheckedUpdateManyInput>
  /**
   * Filter which Music to update
   */
  where?: Prisma.MusicWhereInput
  /**
   * Limit how many Music to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MusicIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Music upsert
 */
export type MusicUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Music
   */
  select?: Prisma.MusicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Music
   */
  omit?: Prisma.MusicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MusicInclude<ExtArgs> | null
  /**
   * The filter to search for the Music to update in case it exists.
   */
  where: Prisma.MusicWhereUniqueInput
  /**
   * In case the Music found by the `where` argument doesn't exist, create a new Music with this data.
   */
  create: Prisma.XOR<Prisma.MusicCreateInput, Prisma.MusicUncheckedCreateInput>
  /**
   * In case the Music was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MusicUpdateInput, Prisma.MusicUncheckedUpdateInput>
}

/**
 * Music delete
 */
export type MusicDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Music
   */
  select?: Prisma.MusicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Music
   */
  omit?: Prisma.MusicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MusicInclude<ExtArgs> | null
  /**
   * Filter which Music to delete.
   */
  where: Prisma.MusicWhereUniqueInput
}

/**
 * Music deleteMany
 */
export type MusicDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Music to delete
   */
  where?: Prisma.MusicWhereInput
  /**
   * Limit how many Music to delete.
   */
  limit?: number
}

/**
 * Music without action
 */
export type MusicDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Music
   */
  select?: Prisma.MusicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Music
   */
  omit?: Prisma.MusicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MusicInclude<ExtArgs> | null
}
