
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `NewCollection` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model NewCollection
 * 
 */
export type NewCollectionModel = runtime.Types.Result.DefaultSelection<Prisma.$NewCollectionPayload>

export type AggregateNewCollection = {
  _count: NewCollectionCountAggregateOutputType | null
  _avg: NewCollectionAvgAggregateOutputType | null
  _sum: NewCollectionSumAggregateOutputType | null
  _min: NewCollectionMinAggregateOutputType | null
  _max: NewCollectionMaxAggregateOutputType | null
}

export type NewCollectionAvgAggregateOutputType = {
  id: number | null
}

export type NewCollectionSumAggregateOutputType = {
  id: number | null
}

export type NewCollectionMinAggregateOutputType = {
  id: number | null
  userId: string | null
  title: string | null
  description: string | null
  reason: string | null
  imageUrl: string | null
  createdAt: Date | null
}

export type NewCollectionMaxAggregateOutputType = {
  id: number | null
  userId: string | null
  title: string | null
  description: string | null
  reason: string | null
  imageUrl: string | null
  createdAt: Date | null
}

export type NewCollectionCountAggregateOutputType = {
  id: number
  userId: number
  title: number
  description: number
  reason: number
  imageUrl: number
  createdAt: number
  _all: number
}


export type NewCollectionAvgAggregateInputType = {
  id?: true
}

export type NewCollectionSumAggregateInputType = {
  id?: true
}

export type NewCollectionMinAggregateInputType = {
  id?: true
  userId?: true
  title?: true
  description?: true
  reason?: true
  imageUrl?: true
  createdAt?: true
}

export type NewCollectionMaxAggregateInputType = {
  id?: true
  userId?: true
  title?: true
  description?: true
  reason?: true
  imageUrl?: true
  createdAt?: true
}

export type NewCollectionCountAggregateInputType = {
  id?: true
  userId?: true
  title?: true
  description?: true
  reason?: true
  imageUrl?: true
  createdAt?: true
  _all?: true
}

export type NewCollectionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which NewCollection to aggregate.
   */
  where?: Prisma.NewCollectionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NewCollections to fetch.
   */
  orderBy?: Prisma.NewCollectionOrderByWithRelationInput | Prisma.NewCollectionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.NewCollectionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NewCollections from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NewCollections.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned NewCollections
  **/
  _count?: true | NewCollectionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: NewCollectionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: NewCollectionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: NewCollectionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: NewCollectionMaxAggregateInputType
}

export type GetNewCollectionAggregateType<T extends NewCollectionAggregateArgs> = {
      [P in keyof T & keyof AggregateNewCollection]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateNewCollection[P]>
    : Prisma.GetScalarType<T[P], AggregateNewCollection[P]>
}




export type NewCollectionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.NewCollectionWhereInput
  orderBy?: Prisma.NewCollectionOrderByWithAggregationInput | Prisma.NewCollectionOrderByWithAggregationInput[]
  by: Prisma.NewCollectionScalarFieldEnum[] | Prisma.NewCollectionScalarFieldEnum
  having?: Prisma.NewCollectionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: NewCollectionCountAggregateInputType | true
  _avg?: NewCollectionAvgAggregateInputType
  _sum?: NewCollectionSumAggregateInputType
  _min?: NewCollectionMinAggregateInputType
  _max?: NewCollectionMaxAggregateInputType
}

export type NewCollectionGroupByOutputType = {
  id: number
  userId: string
  title: string
  description: string
  reason: string
  imageUrl: string | null
  createdAt: Date
  _count: NewCollectionCountAggregateOutputType | null
  _avg: NewCollectionAvgAggregateOutputType | null
  _sum: NewCollectionSumAggregateOutputType | null
  _min: NewCollectionMinAggregateOutputType | null
  _max: NewCollectionMaxAggregateOutputType | null
}

export type GetNewCollectionGroupByPayload<T extends NewCollectionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<NewCollectionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof NewCollectionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], NewCollectionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], NewCollectionGroupByOutputType[P]>
      }
    >
  >



export type NewCollectionWhereInput = {
  AND?: Prisma.NewCollectionWhereInput | Prisma.NewCollectionWhereInput[]
  OR?: Prisma.NewCollectionWhereInput[]
  NOT?: Prisma.NewCollectionWhereInput | Prisma.NewCollectionWhereInput[]
  id?: Prisma.IntFilter<"NewCollection"> | number
  userId?: Prisma.StringFilter<"NewCollection"> | string
  title?: Prisma.StringFilter<"NewCollection"> | string
  description?: Prisma.StringFilter<"NewCollection"> | string
  reason?: Prisma.StringFilter<"NewCollection"> | string
  imageUrl?: Prisma.StringNullableFilter<"NewCollection"> | string | null
  createdAt?: Prisma.DateTimeFilter<"NewCollection"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type NewCollectionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type NewCollectionWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.NewCollectionWhereInput | Prisma.NewCollectionWhereInput[]
  OR?: Prisma.NewCollectionWhereInput[]
  NOT?: Prisma.NewCollectionWhereInput | Prisma.NewCollectionWhereInput[]
  userId?: Prisma.StringFilter<"NewCollection"> | string
  title?: Prisma.StringFilter<"NewCollection"> | string
  description?: Prisma.StringFilter<"NewCollection"> | string
  reason?: Prisma.StringFilter<"NewCollection"> | string
  imageUrl?: Prisma.StringNullableFilter<"NewCollection"> | string | null
  createdAt?: Prisma.DateTimeFilter<"NewCollection"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type NewCollectionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.NewCollectionCountOrderByAggregateInput
  _avg?: Prisma.NewCollectionAvgOrderByAggregateInput
  _max?: Prisma.NewCollectionMaxOrderByAggregateInput
  _min?: Prisma.NewCollectionMinOrderByAggregateInput
  _sum?: Prisma.NewCollectionSumOrderByAggregateInput
}

export type NewCollectionScalarWhereWithAggregatesInput = {
  AND?: Prisma.NewCollectionScalarWhereWithAggregatesInput | Prisma.NewCollectionScalarWhereWithAggregatesInput[]
  OR?: Prisma.NewCollectionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.NewCollectionScalarWhereWithAggregatesInput | Prisma.NewCollectionScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"NewCollection"> | number
  userId?: Prisma.StringWithAggregatesFilter<"NewCollection"> | string
  title?: Prisma.StringWithAggregatesFilter<"NewCollection"> | string
  description?: Prisma.StringWithAggregatesFilter<"NewCollection"> | string
  reason?: Prisma.StringWithAggregatesFilter<"NewCollection"> | string
  imageUrl?: Prisma.StringNullableWithAggregatesFilter<"NewCollection"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"NewCollection"> | Date | string
}

export type NewCollectionCreateInput = {
  title: string
  description: string
  reason: string
  imageUrl?: string | null
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutNewsInput
}

export type NewCollectionUncheckedCreateInput = {
  id?: number
  userId: string
  title: string
  description: string
  reason: string
  imageUrl?: string | null
  createdAt?: Date | string
}

export type NewCollectionUpdateInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutNewsNestedInput
}

export type NewCollectionUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NewCollectionCreateManyInput = {
  id?: number
  userId: string
  title: string
  description: string
  reason: string
  imageUrl?: string | null
  createdAt?: Date | string
}

export type NewCollectionUpdateManyMutationInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NewCollectionUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NewCollectionListRelationFilter = {
  every?: Prisma.NewCollectionWhereInput
  some?: Prisma.NewCollectionWhereInput
  none?: Prisma.NewCollectionWhereInput
}

export type NewCollectionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type NewCollectionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type NewCollectionAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type NewCollectionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type NewCollectionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type NewCollectionSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type NewCollectionCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.NewCollectionCreateWithoutUserInput, Prisma.NewCollectionUncheckedCreateWithoutUserInput> | Prisma.NewCollectionCreateWithoutUserInput[] | Prisma.NewCollectionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.NewCollectionCreateOrConnectWithoutUserInput | Prisma.NewCollectionCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.NewCollectionCreateManyUserInputEnvelope
  connect?: Prisma.NewCollectionWhereUniqueInput | Prisma.NewCollectionWhereUniqueInput[]
}

export type NewCollectionUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.NewCollectionCreateWithoutUserInput, Prisma.NewCollectionUncheckedCreateWithoutUserInput> | Prisma.NewCollectionCreateWithoutUserInput[] | Prisma.NewCollectionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.NewCollectionCreateOrConnectWithoutUserInput | Prisma.NewCollectionCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.NewCollectionCreateManyUserInputEnvelope
  connect?: Prisma.NewCollectionWhereUniqueInput | Prisma.NewCollectionWhereUniqueInput[]
}

export type NewCollectionUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.NewCollectionCreateWithoutUserInput, Prisma.NewCollectionUncheckedCreateWithoutUserInput> | Prisma.NewCollectionCreateWithoutUserInput[] | Prisma.NewCollectionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.NewCollectionCreateOrConnectWithoutUserInput | Prisma.NewCollectionCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.NewCollectionUpsertWithWhereUniqueWithoutUserInput | Prisma.NewCollectionUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.NewCollectionCreateManyUserInputEnvelope
  set?: Prisma.NewCollectionWhereUniqueInput | Prisma.NewCollectionWhereUniqueInput[]
  disconnect?: Prisma.NewCollectionWhereUniqueInput | Prisma.NewCollectionWhereUniqueInput[]
  delete?: Prisma.NewCollectionWhereUniqueInput | Prisma.NewCollectionWhereUniqueInput[]
  connect?: Prisma.NewCollectionWhereUniqueInput | Prisma.NewCollectionWhereUniqueInput[]
  update?: Prisma.NewCollectionUpdateWithWhereUniqueWithoutUserInput | Prisma.NewCollectionUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.NewCollectionUpdateManyWithWhereWithoutUserInput | Prisma.NewCollectionUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.NewCollectionScalarWhereInput | Prisma.NewCollectionScalarWhereInput[]
}

export type NewCollectionUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.NewCollectionCreateWithoutUserInput, Prisma.NewCollectionUncheckedCreateWithoutUserInput> | Prisma.NewCollectionCreateWithoutUserInput[] | Prisma.NewCollectionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.NewCollectionCreateOrConnectWithoutUserInput | Prisma.NewCollectionCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.NewCollectionUpsertWithWhereUniqueWithoutUserInput | Prisma.NewCollectionUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.NewCollectionCreateManyUserInputEnvelope
  set?: Prisma.NewCollectionWhereUniqueInput | Prisma.NewCollectionWhereUniqueInput[]
  disconnect?: Prisma.NewCollectionWhereUniqueInput | Prisma.NewCollectionWhereUniqueInput[]
  delete?: Prisma.NewCollectionWhereUniqueInput | Prisma.NewCollectionWhereUniqueInput[]
  connect?: Prisma.NewCollectionWhereUniqueInput | Prisma.NewCollectionWhereUniqueInput[]
  update?: Prisma.NewCollectionUpdateWithWhereUniqueWithoutUserInput | Prisma.NewCollectionUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.NewCollectionUpdateManyWithWhereWithoutUserInput | Prisma.NewCollectionUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.NewCollectionScalarWhereInput | Prisma.NewCollectionScalarWhereInput[]
}

export type NewCollectionCreateWithoutUserInput = {
  title: string
  description: string
  reason: string
  imageUrl?: string | null
  createdAt?: Date | string
}

export type NewCollectionUncheckedCreateWithoutUserInput = {
  id?: number
  title: string
  description: string
  reason: string
  imageUrl?: string | null
  createdAt?: Date | string
}

export type NewCollectionCreateOrConnectWithoutUserInput = {
  where: Prisma.NewCollectionWhereUniqueInput
  create: Prisma.XOR<Prisma.NewCollectionCreateWithoutUserInput, Prisma.NewCollectionUncheckedCreateWithoutUserInput>
}

export type NewCollectionCreateManyUserInputEnvelope = {
  data: Prisma.NewCollectionCreateManyUserInput | Prisma.NewCollectionCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type NewCollectionUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.NewCollectionWhereUniqueInput
  update: Prisma.XOR<Prisma.NewCollectionUpdateWithoutUserInput, Prisma.NewCollectionUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.NewCollectionCreateWithoutUserInput, Prisma.NewCollectionUncheckedCreateWithoutUserInput>
}

export type NewCollectionUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.NewCollectionWhereUniqueInput
  data: Prisma.XOR<Prisma.NewCollectionUpdateWithoutUserInput, Prisma.NewCollectionUncheckedUpdateWithoutUserInput>
}

export type NewCollectionUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.NewCollectionScalarWhereInput
  data: Prisma.XOR<Prisma.NewCollectionUpdateManyMutationInput, Prisma.NewCollectionUncheckedUpdateManyWithoutUserInput>
}

export type NewCollectionScalarWhereInput = {
  AND?: Prisma.NewCollectionScalarWhereInput | Prisma.NewCollectionScalarWhereInput[]
  OR?: Prisma.NewCollectionScalarWhereInput[]
  NOT?: Prisma.NewCollectionScalarWhereInput | Prisma.NewCollectionScalarWhereInput[]
  id?: Prisma.IntFilter<"NewCollection"> | number
  userId?: Prisma.StringFilter<"NewCollection"> | string
  title?: Prisma.StringFilter<"NewCollection"> | string
  description?: Prisma.StringFilter<"NewCollection"> | string
  reason?: Prisma.StringFilter<"NewCollection"> | string
  imageUrl?: Prisma.StringNullableFilter<"NewCollection"> | string | null
  createdAt?: Prisma.DateTimeFilter<"NewCollection"> | Date | string
}

export type NewCollectionCreateManyUserInput = {
  id?: number
  title: string
  description: string
  reason: string
  imageUrl?: string | null
  createdAt?: Date | string
}

export type NewCollectionUpdateWithoutUserInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NewCollectionUncheckedUpdateWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NewCollectionUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type NewCollectionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  title?: boolean
  description?: boolean
  reason?: boolean
  imageUrl?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["newCollection"]>

export type NewCollectionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  title?: boolean
  description?: boolean
  reason?: boolean
  imageUrl?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["newCollection"]>

export type NewCollectionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  title?: boolean
  description?: boolean
  reason?: boolean
  imageUrl?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["newCollection"]>

export type NewCollectionSelectScalar = {
  id?: boolean
  userId?: boolean
  title?: boolean
  description?: boolean
  reason?: boolean
  imageUrl?: boolean
  createdAt?: boolean
}

export type NewCollectionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "title" | "description" | "reason" | "imageUrl" | "createdAt", ExtArgs["result"]["newCollection"]>
export type NewCollectionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type NewCollectionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type NewCollectionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $NewCollectionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "NewCollection"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    userId: string
    title: string
    description: string
    reason: string
    imageUrl: string | null
    createdAt: Date
  }, ExtArgs["result"]["newCollection"]>
  composites: {}
}

export type NewCollectionGetPayload<S extends boolean | null | undefined | NewCollectionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$NewCollectionPayload, S>

export type NewCollectionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<NewCollectionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: NewCollectionCountAggregateInputType | true
  }

export interface NewCollectionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['NewCollection'], meta: { name: 'NewCollection' } }
  /**
   * Find zero or one NewCollection that matches the filter.
   * @param {NewCollectionFindUniqueArgs} args - Arguments to find a NewCollection
   * @example
   * // Get one NewCollection
   * const newCollection = await prisma.newCollection.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends NewCollectionFindUniqueArgs>(args: Prisma.SelectSubset<T, NewCollectionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__NewCollectionClient<runtime.Types.Result.GetResult<Prisma.$NewCollectionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one NewCollection that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {NewCollectionFindUniqueOrThrowArgs} args - Arguments to find a NewCollection
   * @example
   * // Get one NewCollection
   * const newCollection = await prisma.newCollection.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends NewCollectionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, NewCollectionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__NewCollectionClient<runtime.Types.Result.GetResult<Prisma.$NewCollectionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first NewCollection that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewCollectionFindFirstArgs} args - Arguments to find a NewCollection
   * @example
   * // Get one NewCollection
   * const newCollection = await prisma.newCollection.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends NewCollectionFindFirstArgs>(args?: Prisma.SelectSubset<T, NewCollectionFindFirstArgs<ExtArgs>>): Prisma.Prisma__NewCollectionClient<runtime.Types.Result.GetResult<Prisma.$NewCollectionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first NewCollection that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewCollectionFindFirstOrThrowArgs} args - Arguments to find a NewCollection
   * @example
   * // Get one NewCollection
   * const newCollection = await prisma.newCollection.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends NewCollectionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, NewCollectionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__NewCollectionClient<runtime.Types.Result.GetResult<Prisma.$NewCollectionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more NewCollections that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewCollectionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all NewCollections
   * const newCollections = await prisma.newCollection.findMany()
   * 
   * // Get first 10 NewCollections
   * const newCollections = await prisma.newCollection.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const newCollectionWithIdOnly = await prisma.newCollection.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends NewCollectionFindManyArgs>(args?: Prisma.SelectSubset<T, NewCollectionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NewCollectionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a NewCollection.
   * @param {NewCollectionCreateArgs} args - Arguments to create a NewCollection.
   * @example
   * // Create one NewCollection
   * const NewCollection = await prisma.newCollection.create({
   *   data: {
   *     // ... data to create a NewCollection
   *   }
   * })
   * 
   */
  create<T extends NewCollectionCreateArgs>(args: Prisma.SelectSubset<T, NewCollectionCreateArgs<ExtArgs>>): Prisma.Prisma__NewCollectionClient<runtime.Types.Result.GetResult<Prisma.$NewCollectionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many NewCollections.
   * @param {NewCollectionCreateManyArgs} args - Arguments to create many NewCollections.
   * @example
   * // Create many NewCollections
   * const newCollection = await prisma.newCollection.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends NewCollectionCreateManyArgs>(args?: Prisma.SelectSubset<T, NewCollectionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many NewCollections and returns the data saved in the database.
   * @param {NewCollectionCreateManyAndReturnArgs} args - Arguments to create many NewCollections.
   * @example
   * // Create many NewCollections
   * const newCollection = await prisma.newCollection.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many NewCollections and only return the `id`
   * const newCollectionWithIdOnly = await prisma.newCollection.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends NewCollectionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, NewCollectionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NewCollectionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a NewCollection.
   * @param {NewCollectionDeleteArgs} args - Arguments to delete one NewCollection.
   * @example
   * // Delete one NewCollection
   * const NewCollection = await prisma.newCollection.delete({
   *   where: {
   *     // ... filter to delete one NewCollection
   *   }
   * })
   * 
   */
  delete<T extends NewCollectionDeleteArgs>(args: Prisma.SelectSubset<T, NewCollectionDeleteArgs<ExtArgs>>): Prisma.Prisma__NewCollectionClient<runtime.Types.Result.GetResult<Prisma.$NewCollectionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one NewCollection.
   * @param {NewCollectionUpdateArgs} args - Arguments to update one NewCollection.
   * @example
   * // Update one NewCollection
   * const newCollection = await prisma.newCollection.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends NewCollectionUpdateArgs>(args: Prisma.SelectSubset<T, NewCollectionUpdateArgs<ExtArgs>>): Prisma.Prisma__NewCollectionClient<runtime.Types.Result.GetResult<Prisma.$NewCollectionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more NewCollections.
   * @param {NewCollectionDeleteManyArgs} args - Arguments to filter NewCollections to delete.
   * @example
   * // Delete a few NewCollections
   * const { count } = await prisma.newCollection.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends NewCollectionDeleteManyArgs>(args?: Prisma.SelectSubset<T, NewCollectionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more NewCollections.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewCollectionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many NewCollections
   * const newCollection = await prisma.newCollection.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends NewCollectionUpdateManyArgs>(args: Prisma.SelectSubset<T, NewCollectionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more NewCollections and returns the data updated in the database.
   * @param {NewCollectionUpdateManyAndReturnArgs} args - Arguments to update many NewCollections.
   * @example
   * // Update many NewCollections
   * const newCollection = await prisma.newCollection.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more NewCollections and only return the `id`
   * const newCollectionWithIdOnly = await prisma.newCollection.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends NewCollectionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, NewCollectionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NewCollectionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one NewCollection.
   * @param {NewCollectionUpsertArgs} args - Arguments to update or create a NewCollection.
   * @example
   * // Update or create a NewCollection
   * const newCollection = await prisma.newCollection.upsert({
   *   create: {
   *     // ... data to create a NewCollection
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the NewCollection we want to update
   *   }
   * })
   */
  upsert<T extends NewCollectionUpsertArgs>(args: Prisma.SelectSubset<T, NewCollectionUpsertArgs<ExtArgs>>): Prisma.Prisma__NewCollectionClient<runtime.Types.Result.GetResult<Prisma.$NewCollectionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of NewCollections.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewCollectionCountArgs} args - Arguments to filter NewCollections to count.
   * @example
   * // Count the number of NewCollections
   * const count = await prisma.newCollection.count({
   *   where: {
   *     // ... the filter for the NewCollections we want to count
   *   }
   * })
  **/
  count<T extends NewCollectionCountArgs>(
    args?: Prisma.Subset<T, NewCollectionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], NewCollectionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a NewCollection.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewCollectionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends NewCollectionAggregateArgs>(args: Prisma.Subset<T, NewCollectionAggregateArgs>): Prisma.PrismaPromise<GetNewCollectionAggregateType<T>>

  /**
   * Group by NewCollection.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewCollectionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends NewCollectionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: NewCollectionGroupByArgs['orderBy'] }
      : { orderBy?: NewCollectionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, NewCollectionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetNewCollectionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the NewCollection model
 */
readonly fields: NewCollectionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for NewCollection.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__NewCollectionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the NewCollection model
 */
export interface NewCollectionFieldRefs {
  readonly id: Prisma.FieldRef<"NewCollection", 'Int'>
  readonly userId: Prisma.FieldRef<"NewCollection", 'String'>
  readonly title: Prisma.FieldRef<"NewCollection", 'String'>
  readonly description: Prisma.FieldRef<"NewCollection", 'String'>
  readonly reason: Prisma.FieldRef<"NewCollection", 'String'>
  readonly imageUrl: Prisma.FieldRef<"NewCollection", 'String'>
  readonly createdAt: Prisma.FieldRef<"NewCollection", 'DateTime'>
}
    

// Custom InputTypes
/**
 * NewCollection findUnique
 */
export type NewCollectionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewCollection
   */
  select?: Prisma.NewCollectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewCollection
   */
  omit?: Prisma.NewCollectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewCollectionInclude<ExtArgs> | null
  /**
   * Filter, which NewCollection to fetch.
   */
  where: Prisma.NewCollectionWhereUniqueInput
}

/**
 * NewCollection findUniqueOrThrow
 */
export type NewCollectionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewCollection
   */
  select?: Prisma.NewCollectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewCollection
   */
  omit?: Prisma.NewCollectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewCollectionInclude<ExtArgs> | null
  /**
   * Filter, which NewCollection to fetch.
   */
  where: Prisma.NewCollectionWhereUniqueInput
}

/**
 * NewCollection findFirst
 */
export type NewCollectionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewCollection
   */
  select?: Prisma.NewCollectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewCollection
   */
  omit?: Prisma.NewCollectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewCollectionInclude<ExtArgs> | null
  /**
   * Filter, which NewCollection to fetch.
   */
  where?: Prisma.NewCollectionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NewCollections to fetch.
   */
  orderBy?: Prisma.NewCollectionOrderByWithRelationInput | Prisma.NewCollectionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for NewCollections.
   */
  cursor?: Prisma.NewCollectionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NewCollections from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NewCollections.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of NewCollections.
   */
  distinct?: Prisma.NewCollectionScalarFieldEnum | Prisma.NewCollectionScalarFieldEnum[]
}

/**
 * NewCollection findFirstOrThrow
 */
export type NewCollectionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewCollection
   */
  select?: Prisma.NewCollectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewCollection
   */
  omit?: Prisma.NewCollectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewCollectionInclude<ExtArgs> | null
  /**
   * Filter, which NewCollection to fetch.
   */
  where?: Prisma.NewCollectionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NewCollections to fetch.
   */
  orderBy?: Prisma.NewCollectionOrderByWithRelationInput | Prisma.NewCollectionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for NewCollections.
   */
  cursor?: Prisma.NewCollectionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NewCollections from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NewCollections.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of NewCollections.
   */
  distinct?: Prisma.NewCollectionScalarFieldEnum | Prisma.NewCollectionScalarFieldEnum[]
}

/**
 * NewCollection findMany
 */
export type NewCollectionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewCollection
   */
  select?: Prisma.NewCollectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewCollection
   */
  omit?: Prisma.NewCollectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewCollectionInclude<ExtArgs> | null
  /**
   * Filter, which NewCollections to fetch.
   */
  where?: Prisma.NewCollectionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NewCollections to fetch.
   */
  orderBy?: Prisma.NewCollectionOrderByWithRelationInput | Prisma.NewCollectionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing NewCollections.
   */
  cursor?: Prisma.NewCollectionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NewCollections from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NewCollections.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of NewCollections.
   */
  distinct?: Prisma.NewCollectionScalarFieldEnum | Prisma.NewCollectionScalarFieldEnum[]
}

/**
 * NewCollection create
 */
export type NewCollectionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewCollection
   */
  select?: Prisma.NewCollectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewCollection
   */
  omit?: Prisma.NewCollectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewCollectionInclude<ExtArgs> | null
  /**
   * The data needed to create a NewCollection.
   */
  data: Prisma.XOR<Prisma.NewCollectionCreateInput, Prisma.NewCollectionUncheckedCreateInput>
}

/**
 * NewCollection createMany
 */
export type NewCollectionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many NewCollections.
   */
  data: Prisma.NewCollectionCreateManyInput | Prisma.NewCollectionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * NewCollection createManyAndReturn
 */
export type NewCollectionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewCollection
   */
  select?: Prisma.NewCollectionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the NewCollection
   */
  omit?: Prisma.NewCollectionOmit<ExtArgs> | null
  /**
   * The data used to create many NewCollections.
   */
  data: Prisma.NewCollectionCreateManyInput | Prisma.NewCollectionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewCollectionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * NewCollection update
 */
export type NewCollectionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewCollection
   */
  select?: Prisma.NewCollectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewCollection
   */
  omit?: Prisma.NewCollectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewCollectionInclude<ExtArgs> | null
  /**
   * The data needed to update a NewCollection.
   */
  data: Prisma.XOR<Prisma.NewCollectionUpdateInput, Prisma.NewCollectionUncheckedUpdateInput>
  /**
   * Choose, which NewCollection to update.
   */
  where: Prisma.NewCollectionWhereUniqueInput
}

/**
 * NewCollection updateMany
 */
export type NewCollectionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update NewCollections.
   */
  data: Prisma.XOR<Prisma.NewCollectionUpdateManyMutationInput, Prisma.NewCollectionUncheckedUpdateManyInput>
  /**
   * Filter which NewCollections to update
   */
  where?: Prisma.NewCollectionWhereInput
  /**
   * Limit how many NewCollections to update.
   */
  limit?: number
}

/**
 * NewCollection updateManyAndReturn
 */
export type NewCollectionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewCollection
   */
  select?: Prisma.NewCollectionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the NewCollection
   */
  omit?: Prisma.NewCollectionOmit<ExtArgs> | null
  /**
   * The data used to update NewCollections.
   */
  data: Prisma.XOR<Prisma.NewCollectionUpdateManyMutationInput, Prisma.NewCollectionUncheckedUpdateManyInput>
  /**
   * Filter which NewCollections to update
   */
  where?: Prisma.NewCollectionWhereInput
  /**
   * Limit how many NewCollections to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewCollectionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * NewCollection upsert
 */
export type NewCollectionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewCollection
   */
  select?: Prisma.NewCollectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewCollection
   */
  omit?: Prisma.NewCollectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewCollectionInclude<ExtArgs> | null
  /**
   * The filter to search for the NewCollection to update in case it exists.
   */
  where: Prisma.NewCollectionWhereUniqueInput
  /**
   * In case the NewCollection found by the `where` argument doesn't exist, create a new NewCollection with this data.
   */
  create: Prisma.XOR<Prisma.NewCollectionCreateInput, Prisma.NewCollectionUncheckedCreateInput>
  /**
   * In case the NewCollection was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.NewCollectionUpdateInput, Prisma.NewCollectionUncheckedUpdateInput>
}

/**
 * NewCollection delete
 */
export type NewCollectionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewCollection
   */
  select?: Prisma.NewCollectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewCollection
   */
  omit?: Prisma.NewCollectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewCollectionInclude<ExtArgs> | null
  /**
   * Filter which NewCollection to delete.
   */
  where: Prisma.NewCollectionWhereUniqueInput
}

/**
 * NewCollection deleteMany
 */
export type NewCollectionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which NewCollections to delete
   */
  where?: Prisma.NewCollectionWhereInput
  /**
   * Limit how many NewCollections to delete.
   */
  limit?: number
}

/**
 * NewCollection without action
 */
export type NewCollectionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewCollection
   */
  select?: Prisma.NewCollectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewCollection
   */
  omit?: Prisma.NewCollectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewCollectionInclude<ExtArgs> | null
}
