import "dotenv/config";
import { prisma } from "./prisma.client";

const USER_EMAIL = process.env.SEED_USER_EMAIL;

if (!USER_EMAIL) {
    throw new Error("SEED_USER_EMAIL ist nicht gesetzt.");
}

if (process.env.VERCEL_ENV === "production") {
    console.log("Automatisches Seeding ist für diese Umgebung deaktiviert.");
    process.exit(0);
}

const openLibraryCoverByIsbn = (isbn: string) =>
    `https://covers.openlibrary.org/b/isbn/${isbn}-L.jpg`;

const openLibraryCover = (title: string) =>
    `https://covers.openlibrary.org/b/title/${encodeURIComponent(title)}-L.jpg?default=false`;

const coverArtArchive = (releaseId: string) =>
    `https://coverartarchive.org/release/${releaseId}/front-500.jpg`;

const commonsFile = (fileName: string) =>
    `https://commons.wikimedia.org/wiki/Special:Redirect/file/${encodeURIComponent(fileName)}`;


async function seed() {
    const user = await prisma.user.findUnique({
        where: { email: USER_EMAIL },
    });

    if (!user) {
        throw new Error(`Benutzer mit der E-Mail-Adresse "${USER_EMAIL}" wurde nicht gefunden.`);
    }

    const existingSeed = await prisma.book.findFirst({
        where: {
            userId: user.id,
            title: "Lolita",
            author: "Vladimir Nabokov",
        },
    });

    if (existingSeed) {
        console.log("Seed wurde bereits angewendet. Überspringe.");
        return;
    }

    const books = [
        {
            userId: user.id,
            title: "Lolita",
            author: "Vladimir Nabokov",
            year: "1955",
            pages: 336,
            discovered_by: "Buchhandlung in Berlin",
            note: "Eine sprachlich außergewöhnliche Erzählung über Obsession, Selbsttäuschung und die Macht eines unzuverlässigen Erzählers.",
            bestQuote:
                "Auf einen Mörder kann man sich immer verlassen, wenn es um eine kunstvolle Prosa geht.",
            imageUrl: openLibraryCoverByIsbn("0425099601"),
        },
        {
            userId: user.id,
            title: "Pnin",
            author: "Vladimir Nabokov",
            year: "1957",
            pages: 191,
            discovered_by: "Empfehlung eines Freundes",
            note: "Eine zärtliche und zugleich ironische Nabokov-Figur zwischen Erinnerung, Fremdsein und Komik.",
            bestQuote: "Pnin war ein Träumer.",
            imageUrl: openLibraryCoverByIsbn("0679723412"),
        },
        {
            userId: user.id,
            title: "Ada or Ardor",
            author: "Vladimir Nabokov",
            year: "1969",
            pages: 589,
            discovered_by: "Antiquariat in Paris",
            note: "Eine obsessive, verspielte und vollkommen eigenwillige Welt.",
            bestQuote: "Alle glücklichen Familien sind inzestuös.",
            imageUrl: openLibraryCoverByIsbn("0679725229"),
        },
        {
            userId: user.id,
            title: "Die Brüder Karamasow",
            author: "Fjodor Dostojewski",
            year: "1880",
            pages: 796,
            discovered_by: "Empfehlung eines Freundes",
            note: "Glaube, Zweifel, Freiheit, Schuld und die schwierigsten Fragen menschlicher Existenz.",
            bestQuote: "Vor allem: Belüge dich selbst nicht.",
            imageUrl: openLibraryCoverByIsbn("0553212168"),
        },
        {
            userId: user.id,
            title: "Schuld und Sühne",
            author: "Fjodor Dostojewski",
            year: "1866",
            pages: 671,
            discovered_by: "Leseliste für einen langen Winter",
            note: "Psychologie, Schuld und die Grenzen moralischer Selbstrechtfertigung.",
            bestQuote:
                "Schmerz und Leiden sind für einen großen Geist und ein tiefes Herz immer unvermeidlich.",
            imageUrl: openLibraryCoverByIsbn("1411403665"),
        },
        {
            userId: user.id,
            title: "Aufzeichnungen aus dem Kellerloch",
            author: "Fjodor Dostojewski",
            year: "1864",
            pages: 160,
            discovered_by: "Universitätsbibliothek",
            note: "Bewusstsein, Trotz und der Widerstand gegen eine allzu vernünftige Welt.",
            bestQuote: "Ich bin ein kranker Mensch.",
            imageUrl: openLibraryCoverByIsbn("0140446694"),
        },
        {
            userId: user.id,
            title: "Der Idiot",
            author: "Fjodor Dostojewski",
            year: "1869",
            pages: 656,
            discovered_by: "Buchhandlung in Frankfurt",
            note: "Mitgefühl, Naivität und die Frage, ob Güte in einer zynischen Welt bestehen kann.",
            bestQuote: "Die Schönheit wird die Welt retten.",
            imageUrl: openLibraryCoverByIsbn("0553211457"),
        },
        {
            userId: user.id,
            title: "Tropic of Cancer",
            author: "Henry Miller",
            year: "1934",
            pages: 318,
            discovered_by: "Buchladen in Prag",
            note: "Paris, Armut, Sexualität, Schreiben und radikale künstlerische Freiheit.",
            bestQuote: "Ich habe kein Geld, keine Mittel und keine Hoffnung.",
            imageUrl: openLibraryCoverByIsbn("0394623754"),
        },
        {
            userId: user.id,
            title: "Tropic of Capricorn",
            author: "Henry Miller",
            year: "1939",
            pages: 384,
            discovered_by: "Empfehlung eines Schriftstellers",
            note: "Autobiografischer, wilder und sehr persönlicher Miller.",
            bestQuote: "Ein Buch zu machen bedeutet, es zu schreiben.",
            imageUrl: openLibraryCoverByIsbn("039417898X"),
        },
        {
            userId: user.id,
            title: "1984",
            author: "George Orwell",
            year: "1949",
            pages: 328,
            discovered_by: "Schulbibliothek",
            note: "Überwachung, Sprache, politische Macht und die Zerstörung unabhängigen Denkens.",
            bestQuote: "Der Große Bruder beobachtet dich.",
            imageUrl: openLibraryCoverByIsbn("0451516753"),
        },
        {
            userId: user.id,
            title: "Animal Farm",
            author: "George Orwell",
            year: "1945",
            pages: 112,
            discovered_by: "Empfehlung eines Freundes",
            note: "Eine kleine politische Fabel über Macht und ihre Korruption.",
            bestQuote:
                "Alle Tiere sind gleich, aber manche Tiere sind gleicher als andere.",
            imageUrl: openLibraryCoverByIsbn("0451526341"),
        },
        {
            userId: user.id,
            title: "Der Steppenwolf",
            author: "Hermann Hesse",
            year: "1927",
            pages: 237,
            discovered_by: "Buchhandlung in Frankfurt",
            note: "Für Menschen, die sich zwischen mehreren Versionen ihrer selbst bewegen.",
            bestQuote: "Es gibt keine Wirklichkeit außer im Augenblick.",
            imageUrl: openLibraryCoverByIsbn("0553208047"),
        },
        {
            userId: user.id,
            title: "Siddhartha",
            author: "Hermann Hesse",
            year: "1922",
            pages: 152,
            discovered_by: "Reise nach Zürich",
            note: "Die Suche nach einem eigenen Weg statt nach einer fertigen Wahrheit.",
            bestQuote: "Weisheit kann man nicht vermitteln.",
            imageUrl: openLibraryCoverByIsbn("0553208845"),
        },
        {
            userId: user.id,
            title: "Demian",
            author: "Hermann Hesse",
            year: "1919",
            pages: 176,
            discovered_by: "Empfehlung eines Freundes",
            note: "Identität, Erwachsenwerden und die Suche nach dem eigenen inneren Weg.",
            bestQuote: "Der Vogel kämpft sich aus dem Ei.",
            imageUrl: openLibraryCoverByIsbn("9681501233"),
        },
        {
            userId: user.id,
            title: "Sapiens",
            author: "Yuval Noah Harari",
            year: "2011",
            pages: 443,
            discovered_by: "Empfehlung beim Abendessen",
            note: "Geschichte der Menschheit und die Geschichten, die Gesellschaften zusammenhalten.",
            bestQuote:
                "Die eigentliche Geschichte der Menschheit beginnt mit der kognitiven Revolution.",
            imageUrl: openLibraryCoverByIsbn("0062316097"),
        },
        {
            userId: user.id,
            title: "Homo Deus",
            author: "Yuval Noah Harari",
            year: "2015",
            pages: 449,
            discovered_by: "Buchhandlung am Bahnhof",
            note: "Technologie, Zukunft und die mögliche nächste Phase der Menschheit.",
            bestQuote: "Die Geschichte begann, als Menschen Götter erfanden.",
            imageUrl: openLibraryCoverByIsbn("0062464310"),
        },
        {
            userId: user.id,
            title: "21 Lessons for the 21st Century",
            author: "Yuval Noah Harari",
            year: "2018",
            pages: 372,
            discovered_by: "Flughafenbuchhandlung",
            note: "Gegenwart, Technologie, Politik und die Frage, worauf Menschen ihre Aufmerksamkeit richten sollten.",
            bestQuote:
                "Die Zukunft gehört denen, die sich neu erfinden können.",
            imageUrl: openLibraryCoverByIsbn("1787330877"),
        },
        {
            userId: user.id,
            title: "Der Fremde",
            author: "Albert Camus",
            year: "1942",
            pages: 123,
            discovered_by: "Französische Buchhandlung",
            note: "Absurdität, Entfremdung und emotionale Distanz.",
            bestQuote:
                "Ich öffnete mich der sanften Gleichgültigkeit des Universums.",
            imageUrl: openLibraryCoverByIsbn("0881032476"),
        },
        {
            userId: user.id,
            title: "Der Prozess",
            author: "Franz Kafka",
            year: "1925",
            pages: 255,
            discovered_by: "Spaziergang durch Prag",
            note: "Bürokratie, Schuld und das Gefühl, in einem unverständlichen System gefangen zu sein.",
            bestQuote:
                "Jemand musste Josef K. verleumdet haben.",
            imageUrl: openLibraryCoverByIsbn("0805208488"),
        },
        {
            userId: user.id,
            title: "Ein Zimmer für sich allein",
            author: "Virginia Woolf",
            year: "1929",
            pages: 112,
            discovered_by: "Buchhandlung für Kunst und Literatur",
            note: "Unabhängigkeit, Geld und geistiger Raum als Voraussetzung für Kreativität.",
            bestQuote:
                "Eine Frau braucht Geld und ein eigenes Zimmer, wenn sie Belletristik schreiben will.",
            imageUrl: openLibraryCoverByIsbn("0156030411"),
        },
    ];

    const vinyl = [
        {
            userId: user.id,
            format: "Physisch",
            title: "The Dark Side of the Moon",
            author: "Pink Floyd",
            year: "1973",
            discovered_by: "Plattenladen in Berlin",
            note: "Eine Platte, die wegen Klang, Atmosphäre und Erinnerung geblieben ist.",
            bestQuote: "Alles, was du berührst.",
            imageUrl: coverArtArchive(
                "426c9989-5d2d-4ca2-893c-080a0ae45555",
            ),
        },
        {
            userId: user.id,
            format: "Physisch",
            title: "Wish You Were Here",
            author: "Pink Floyd",
            year: "1975",
            discovered_by: "Plattenbörse in Frankfurt",
            note: "Eine Platte, die wegen Klang, Atmosphäre und Erinnerung geblieben ist.",
            bestQuote: "Ich wünschte, du wärst hier.",
            imageUrl: coverArtArchive(
                "e2caa244-bf9c-4fd8-8cd4-b00802b02b02",
            ),
        },
        {
            userId: user.id,
            format: "Physisch",
            title: "Animals",
            author: "Pink Floyd",
            year: "1977",
            discovered_by: "Empfehlung eines Musikers",
            note: "Eine Platte, die wegen Klang, Atmosphäre und Erinnerung geblieben ist.",
            bestQuote: "Wer wurde in einem Haus voller Schmerz geboren?",
            imageUrl: coverArtArchive(
                "32f76eef-5004-3e80-bdf8-912298896134",
            ),
        },
        {
            userId: user.id,
            format: "Physisch",
            title: "Rain Dogs",
            author: "Tom Waits",
            year: "1985",
            discovered_by: "Vinyl-Abteilung in Paris",
            note: "Eine Platte, die wegen Klang, Atmosphäre und Erinnerung geblieben ist.",
            bestQuote: "Die Zeit ist das Feuer, in dem wir brennen.",
            imageUrl: coverArtArchive(
                "d2c65d81-1afc-3ac2-81e9-0a0abd1a538a",
            ),
        },
        {
            userId: user.id,
            format: "Physisch",
            title: "I'm Your Man",
            author: "Leonard Cohen",
            year: "1988",
            discovered_by: "Plattenladen in Wien",
            note: "Eine Platte, die wegen Klang, Atmosphäre und Erinnerung geblieben ist.",
            bestQuote: "Zuerst nehmen wir Manhattan.",
            imageUrl: coverArtArchive(
                "16573489-9224-47e0-b36f-b6015e473f9f",
            ),
        },
        {
            userId: user.id,
            format: "Physisch",
            title: "The Queen Is Dead",
            author: "The Smiths",
            year: "1986",
            discovered_by: "Empfehlung eines Freundes",
            note: "Eine Platte, die wegen Klang, Atmosphäre und Erinnerung geblieben ist.",
            bestQuote: "Das Leben ist ein Lied.",
            imageUrl: coverArtArchive(
                "2f3eb520-4126-40a7-9089-6876a2c45b67",
            ),
        },
        {
            userId: user.id,
            format: "Physisch",
            title: "Unknown Pleasures",
            author: "Joy Division",
            year: "1979",
            discovered_by: "Plattenladen in Manchester",
            note: "Eine Platte, die wegen Klang, Atmosphäre und Erinnerung geblieben ist.",
            bestQuote: "Dunkelheit ist billig.",
            imageUrl: coverArtArchive(
                "d6fc72f1-afc0-47dd-b7fc-2bf6d7c0dbd9",
            ),
        },
        {
            userId: user.id,
            format: "Physisch",
            title: "Closer",
            author: "Joy Division",
            year: "1980",
            discovered_by: "Second-Hand-Plattenladen",
            note: "Eine Platte, die wegen Klang, Atmosphäre und Erinnerung geblieben ist.",
            bestQuote: "Sie hat die Kontrolle verloren.",
            imageUrl: coverArtArchive(
                "d3434bfd-c025-39cd-8a29-a1c7552e226b",
            ),
        },
        {
            userId: user.id,
            format: "Physisch",
            title: "The Velvet Underground & Nico",
            author: "The Velvet Underground & Nico",
            year: "1967",
            discovered_by: "Plattenbörse",
            note: "Eine Platte, die wegen Klang, Atmosphäre und Erinnerung geblieben ist.",
            bestQuote: "Heroin, sei mein Tod.",
            imageUrl: coverArtArchive(
                "2657e677-49ce-480f-8868-04a0b354aec2",
            ),
        },
        {
            userId: user.id,
            format: "Physisch",
            title: "Selected Ambient Works 85–92",
            author: "Aphex Twin",
            year: "1992",
            discovered_by: "Empfehlung eines DJs",
            note: "Eine Platte, die wegen Klang, Atmosphäre und Erinnerung geblieben ist.",
            bestQuote: "Komm zu Papa.",
            imageUrl: coverArtArchive(
                "91b48d23-7a5e-47d8-8484-cd06d54224ce",
            ),
        },
        {
            userId: user.id,
            format: "Physisch",
            title: "Die Mensch·Maschine",
            author: "Kraftwerk",
            year: "1978",
            discovered_by: "Plattenladen in Düsseldorf",
            note: "Eine Platte, die wegen Klang, Atmosphäre und Erinnerung geblieben ist.",
            bestQuote: "Die Roboter.",
            imageUrl: coverArtArchive(
                "8360f429-ab2c-3b1c-ae23-3e94b7ef7438",
            ),
        },
        {
            userId: user.id,
            format: "Physisch",
            title: "The Köln Concert",
            author: "Keith Jarrett",
            year: "1975",
            discovered_by: "Jazz-Abteilung eines Antiquariats",
            note: "Eine Platte, die wegen Klang, Atmosphäre und Erinnerung geblieben ist.",
            bestQuote: "Über den Regenbogen.",
            imageUrl: coverArtArchive(
                "733b8ed9-a393-46b8-9309-69564e96e7e6",
            ),
        },
    ];

    const tracks = [
        {
            userId: user.id,
            format: "Digital",
            title: "Shine On You Crazy Diamond",
            author: "Pink Floyd",
            year: "1975",
            discovered_by: "Plattenabend",
            note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist.",
            bestQuote: "Leuchte weiter, du verrückter Diamant.",
        },
        {
            userId: user.id,
            format: "Digital",
            title: "Comfortably Numb",
            author: "Pink Floyd",
            year: "1979",
            discovered_by: "Spotify-Radio",
            note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist.",
            bestQuote: "Da ist ein Blick in deinen Augen.",
        },
        {
            userId: user.id,
            format: "Digital",
            title: "Echoes",
            author: "Pink Floyd",
            year: "1971",
            discovered_by: "Plattenabend",
            note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist.",
            bestQuote:
                "Über uns hängt der Albatros regungslos in der Luft.",
        },
        {
            userId: user.id,
            format: "Digital",
            title: "Us and Them",
            author: "Pink Floyd",
            year: "1973",
            discovered_by: "Lieblingsplaylist",
            note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist.",
            bestQuote: "Wir und sie.",
        },
        {
            userId: user.id,
            format: "Digital",
            title: "Time",
            author: "Pink Floyd",
            year: "1973",
            discovered_by: "Alte Playlist",
            note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist.",
            bestQuote: "Jedes Jahr wird kürzer.",
        },
        {
            userId: user.id,
            format: "Digital",
            title: "Wish You Were Here",
            author: "Pink Floyd",
            year: "1975",
            discovered_by: "Alte Playlist",
            note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist.",
            bestQuote: "Ich wünschte, du wärst hier.",
        },
        {
            userId: user.id,
            format: "Digital",
            title: "Hallelujah",
            author: "Leonard Cohen",
            year: "1984",
            discovered_by: "Filmabend",
            note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist.",
            bestQuote: "Ich habe gehört, es gab einst einen geheimen Akkord.",
        },
        {
            userId: user.id,
            format: "Digital",
            title: "Famous Blue Raincoat",
            author: "Leonard Cohen",
            year: "1971",
            discovered_by: "Empfehlung eines Freundes",
            note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist.",
            bestQuote: "Es ist vier Uhr morgens.",
        },
        {
            userId: user.id,
            format: "Digital",
            title: "The Partisan",
            author: "Leonard Cohen",
            year: "1969",
            discovered_by: "Dokumentarfilm",
            note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist.",
            bestQuote: "Wer wird durch das Feuer gehen?",
        },
        {
            userId: user.id,
            format: "Digital",
            title: "Tango Till They're Sore",
            author: "Tom Waits",
            year: "1985",
            discovered_by: "Tom-Waits-Playlist",
            note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist.",
            bestQuote: "Sprich niemals mit Fremden.",
        },
        {
            userId: user.id,
            format: "Digital",
            title: "Jockey Full of Bourbon",
            author: "Tom Waits",
            year: "1985",
            discovered_by: "Film entdeckt",
            note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist.",
            bestQuote: "Weißt du nicht, dass es keinen Teufel gibt?",
        },
        {
            userId: user.id,
            format: "Digital",
            title: "There Is a Light That Never Goes Out",
            author: "The Smiths",
            year: "1986",
            discovered_by: "Alte Playlist",
            note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist.",
            bestQuote: "Bring mich heute Nacht hinaus.",
        },
        {
            userId: user.id,
            format: "Digital",
            title: "Heaven Knows I'm Miserable Now",
            author: "The Smiths",
            year: "1984",
            discovered_by: "Empfehlung eines Freundes",
            note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist.",
            bestQuote: "Der Himmel weiß, dass ich jetzt unglücklich bin.",
        },
        {
            userId: user.id,
            format: "Digital",
            title: "Love Will Tear Us Apart",
            author: "Joy Division",
            year: "1980",
            discovered_by: "Clubnacht",
            note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist.",
            bestQuote: "Wenn die Routine hart zuschlägt.",
        },
        {
            userId: user.id,
            format: "Digital",
            title: "Atmosphere",
            author: "Joy Division",
            year: "1980",
            discovered_by: "Spotify",
            note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist.",
            bestQuote: "Geh in Stille.",
        },
        {
            userId: user.id,
            format: "Digital",
            title: "Bela Lugosi's Dead",
            author: "Bauhaus",
            year: "1979",
            discovered_by: "Empfehlung eines DJs",
            note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist.",
            bestQuote: "Gabba gabba hey.",
        },
        {
            userId: user.id,
            format: "Digital",
            title: "A Forest",
            author: "The Cure",
            year: "1980",
            discovered_by: "Radio",
            note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist.",
            bestQuote: "Komm näher und sieh.",
        },
        {
            userId: user.id,
            format: "Digital",
            title: "Pictures of You",
            author: "The Cure",
            year: "1989",
            discovered_by: "Alte Playlist",
            note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist.",
            bestQuote: "Gestern wachte ich auf und schmeckte nach Zitrone.",
        },
        {
            userId: user.id,
            format: "Digital",
            title: "Roads",
            author: "Portishead",
            year: "1994",
            discovered_by: "Filmabend",
            note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist.",
            bestQuote: "Oh, kann das niemand sehen?",
        },
        {
            userId: user.id,
            format: "Digital",
            title: "Glory Box",
            author: "Portishead",
            year: "1994",
            discovered_by: "Spotify",
            note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist.",
            bestQuote: "Gib mir einen Grund, dich zu lieben.",
        },
        {
            userId: user.id,
            format: "Digital",
            title: "Teardrop",
            author: "Massive Attack",
            year: "1998",
            discovered_by: "Trip-Hop-Playlist",
            note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist.",
            bestQuote: "Liebe, Liebe ist ein Verb.",
        },
        {
            userId: user.id,
            format: "Digital",
            title: "Angel",
            author: "Massive Attack",
            year: "1998",
            discovered_by: "Film entdeckt",
            note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist.",
            bestQuote: "Liebe, Liebe ist ein Verb.",
        },
        {
            userId: user.id,
            format: "Digital",
            title: "Porcelain",
            author: "Moby",
            year: "1999",
            discovered_by: "Alte Playlist",
            note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist.",
            bestQuote: "In meinen Träumen sterbe ich die ganze Zeit.",
        },
        {
            userId: user.id,
            format: "Digital",
            title: "Windowlicker",
            author: "Aphex Twin",
            year: "1999",
            discovered_by: "Empfehlung eines DJs",
            note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist.",
            bestQuote: "Fensterlecker.",
        },
        {
            userId: user.id,
            format: "Digital",
            title: "Strings of Life",
            author: "Rhythim Is Rhythim",
            year: "1987",
            discovered_by: "Techno-Archiv",
            note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist.",
            bestQuote: "Die Saiten des Lebens.",
        },
        {
            userId: user.id,
            format: "Digital",
            title: "L'Ange Naïf",
            author: "Sven Väth",
            year: "1992",
            discovered_by: "Frankfurter Clubnacht",
            note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist.",
            bestQuote: "Das Leben ist wie ein Spiel.",
        },
        {
            userId: user.id,
            format: "Digital",
            title: "Insomnia",
            author: "Faithless",
            year: "1995",
            discovered_by: "90er-Playlist",
            note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist.",
            bestQuote: "Schlaflosigkeit, bitte lass mich frei.",
        },
        {
            userId: user.id,
            format: "Digital",
            title: "Blue Monday",
            author: "New Order",
            year: "1983",
            discovered_by: "Musikvideo",
            note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist.",
            bestQuote: "Wie fühlt es sich an?",
        },
    ];

    const magazines = [
        {
            userId: user.id,
            title: "RAY",
            issue: "N°24",
            date: "September 1985",
            discovered_by: "Meine Großmutter",
            note: "Ein Filmmagazin mit einem außergewöhnlich starken visuellen Charakter.",
            bestQuote: "Fotografie ist eine Liebesaffäre mit dem Leben.",
            imageUrl: openLibraryCover("RAY"),
        },
        {
            userId: user.id,
            title: "RAY",
            issue: "N°31",
            date: "April 1987",
            discovered_by: "Flohmarkt in Frankfurt",
            note: "Ein weiteres Stück visueller Filmgeschichte.",
            bestQuote: "Kino als visuelle Erinnerung.",
            imageUrl: openLibraryCover("RAY"),
        },
        {
            userId: user.id,
            title: "Cahiers du cinéma",
            issue: "N°100",
            date: "1959",
            discovered_by: "Filmseminar",
            note: "Film als Kunstform und als Denken.",
            bestQuote: "Das Kino ist eine Kunst.",
            imageUrl: openLibraryCover("Cahiers du cinéma"),
        },
        {
            userId: user.id,
            title: "Sight & Sound",
            issue: "Summer",
            date: "1963",
            discovered_by: "Filmbuchhandlung in Berlin",
            note: "Ein kleines Stück Filmgeschichte und Filmkritik.",
            bestQuote: "Kino ist eine Art zu sehen.",
            imageUrl: openLibraryCover("Sight & Sound"),
        },
        {
            userId: user.id,
            title: "Aperture",
            issue: "N°100",
            date: "1985",
            discovered_by: "Fotografie-Ausstellung",
            note: "Fotografie, Kunst und visuelle Kultur.",
            bestQuote: "Fotografie ist eine Art zu sehen.",
            imageUrl: openLibraryCover("Aperture"),
        },
    ];

    const artworks = [
        {
            userId: user.id,
            format: "Physisch",
            title: "The Old Guitarist",
            author: "Pablo Picasso",
            year: "1903",
            technique: "Öl auf Holz",
            dimensions: "122,9 × 82,6 cm",
            discovered_by: "Museum Ludwig",
            note: "Die blaue Periode – Einsamkeit und Menschlichkeit in fast monochromen Blautönen.",
            imageUrl: commonsFile("The Old Guitarist.jpg"),
        },
        {
            userId: user.id,
            format: "Physisch",
            title: "La Vie",
            author: "Pablo Picasso",
            year: "1903",
            technique: "Öl auf Leinwand",
            dimensions: "196,5 × 128,5 cm",
            discovered_by: "Picasso-Ausstellung",
            note: "Eines der zentralen Werke der blauen Periode.",
            imageUrl: commonsFile("Pablo Picasso, 1903, La Vie.jpg"),
        },
        {
            userId: user.id,
            format: "Physisch",
            title: "The Blue Room",
            author: "Pablo Picasso",
            year: "1901",
            technique: "Öl auf Leinwand",
            dimensions: "50,5 × 62,5 cm",
            discovered_by: "Kunstbuch über Picasso",
            note: "Ein frühes Bild voller blauer Melancholie und Intimität.",
            imageUrl: commonsFile("Pablo Picasso, The Blue Room, 1901.jpg"),
        },
        {
            userId: user.id,
            format: "Physisch",
            title: "Guernica",
            author: "Pablo Picasso",
            year: "1937",
            technique: "Öl auf Leinwand",
            dimensions: "349,3 × 776,6 cm",
            discovered_by: "Kunstgeschichte-Seminar",
            note: "Gewalt, Krieg und Fragmentierung in einer monumentalen Bildsprache.",
            imageUrl: commonsFile("Picasso Guernica.jpg"),
        },
        {
            userId: user.id,
            format: "Physisch",
            title: "The Kiss",
            author: "Gustav Klimt",
            year: "1908",
            technique: "Öl und Blattgold auf Leinwand",
            dimensions: "180 × 180 cm",
            discovered_by: "Belvedere in Wien",
            note: "Dekorative Oberfläche, Intimität und eine beinahe sakrale Nähe.",
            imageUrl: commonsFile(
                "The Kiss - Gustav Klimt - Google Cultural Institute.jpg",
            ),
        },
        {
            userId: user.id,
            format: "Physisch",
            title: "Death and Life",
            author: "Gustav Klimt",
            year: "1915",
            technique: "Öl auf Leinwand",
            dimensions: "178 × 198 cm",
            discovered_by: "Klimt-Ausstellung",
            note: "Leben und Tod als ornamentale Gegenüberstellung.",
            imageUrl: commonsFile("Klimt - Tod und Leben - 1915-16.jpg"),
        },
        {
            userId: user.id,
            format: "Physisch",
            title: "Self-Portrait with Physalis",
            author: "Egon Schiele",
            year: "1912",
            technique: "Öl auf Leinwand",
            dimensions: "42,2 × 32,4 cm",
            discovered_by: "Leopold Museum",
            note: "Körper, Blick und Nervosität in einer extrem persönlichen Bildsprache.",
            imageUrl: commonsFile("Egon Schiele 010.jpg"),
        },
        {
            userId: user.id,
            format: "Physisch",
            title: "The Garden of Earthly Delights",
            author: "Hieronymus Bosch",
            year: "1500",
            technique: "Öl auf Holz",
            dimensions: "205,5 × 384,9 cm",
            discovered_by: "Kunsthistorisches Museum",
            note: "Eine Welt, die man immer wieder neu lesen und entdecken kann.",
            imageUrl: commonsFile(
                "The Garden of Earthly Delights by Bosch High Resolution.jpg",
            ),
        },
        {
            userId: user.id,
            format: "Physisch",
            title: "The Dance",
            author: "Henri Matisse",
            year: "1910",
            technique: "Öl auf Leinwand",
            dimensions: "260 × 391 cm",
            discovered_by: "Matisse-Katalog",
            note: "Bewegung auf das Wesentliche reduziert.",
            imageUrl: commonsFile("Matisse - La Danse.jpg"),
        },
        {
            userId: user.id,
            format: "Physisch",
            title: "Blue Nude II",
            author: "Henri Matisse",
            year: "1952",
            technique: "Gouache auf Papier, Cut-out",
            dimensions: "116,2 × 88,9 cm",
            discovered_by: "Ausstellung über Matisse",
            note: "Der Körper als reine Form und Rhythmus.",
            imageUrl: commonsFile("Matisse - Blue Nude II.jpg"),
        },
        {
            userId: user.id,
            format: "Physisch",
            title: "Nighthawks",
            author: "Edward Hopper",
            year: "1942",
            technique: "Öl auf Leinwand",
            dimensions: "84,1 × 152,4 cm",
            discovered_by: "Filmstill und Kunstbuch",
            note: "Urbane Einsamkeit und künstliches Licht.",
            imageUrl: commonsFile("Nighthawks by Edward Hopper 1942.jpg"),
        },
        {
            userId: user.id,
            format: "Physisch",
            title: "The Son of Man",
            author: "René Magritte",
            year: "1964",
            technique: "Öl auf Leinwand",
            dimensions: "116 × 89 cm",
            discovered_by: "Surrealismus-Ausstellung",
            note: "Identität, Verbergen und die seltsame Logik des Alltäglichen.",
            imageUrl: commonsFile("Magritte TheSonOfMan.jpg"),
        },
        {
            userId: user.id,
            format: "Physisch",
            title: "Composition VIII",
            author: "Wassily Kandinsky",
            year: "1923",
            technique: "Öl auf Leinwand",
            dimensions: "140 × 201 cm",
            discovered_by: "Kunstgeschichte-Buch",
            note: "Geometrie und Farbe wie eine visuelle Komposition.",
            imageUrl: commonsFile(
                "Vassily Kandinsky, 1923 - Composition 8.jpg",
            ),
        },
    ];

    const museums = [
        {
            userId: user.id,
            title: "DFF – Deutsches Filminstitut & Filmmuseum",
            city: "Frankfurt am Main",
            exhibition: "Film, Kino und visuelle Kultur",
            date: new Date("2025-05-10"),
            discovered_by: "Frankfurt",
            note: "Eines meiner Lieblingsmuseen – Film als lebendiges Archiv.",
        },
        {
            userId: user.id,
            title: "Städel Museum",
            city: "Frankfurt am Main",
            exhibition: "Sammlung Moderne Kunst",
            date: new Date("2025-04-20"),
            discovered_by: "Frankfurt",
            note: "Ein Lieblingsort für Kunst.",
        },
        {
            userId: user.id,
            title: "Museum Ludwig",
            city: "Köln",
            exhibition: "Picasso",
            date: new Date("2025-06-12"),
            discovered_by: "Reise nach Köln",
            note: "Moderne Kunst und eine besondere Picasso-Sammlung.",
        },
        {
            userId: user.id,
            title: "Hamburger Bahnhof",
            city: "Berlin",
            exhibition: "Zeitgenössische Kunst",
            date: new Date("2025-06-03"),
            discovered_by: "Wochenende in Berlin",
            note: "Ein Lieblingsort für zeitgenössische Kunst.",
        },
        {
            userId: user.id,
            title: "Alte Nationalgalerie",
            city: "Berlin",
            exhibition: "19. Jahrhundert",
            date: new Date("2025-05-14"),
            discovered_by: "Museumsinsel",
            note: "Malerei und Skulptur des 19. Jahrhunderts.",
        },
        {
            userId: user.id,
            title: "Neue Nationalgalerie",
            city: "Berlin",
            exhibition: "Moderne Kunst",
            date: new Date("2025-05-16"),
            discovered_by: "Wochenende in Berlin",
            note: "Architektur und Moderne.",
        },
        {
            userId: user.id,
            title: "Museum Brandhorst",
            city: "München",
            exhibition: "Andy Warhol",
            date: new Date("2025-03-21"),
            discovered_by: "Reise nach München",
            note: "Pop Art und moderne Kunst.",
        },
        {
            userId: user.id,
            title: "Pinakothek der Moderne",
            city: "München",
            exhibition: "Moderne Kunst",
            date: new Date("2025-03-22"),
            discovered_by: "Reise nach München",
            note: "Kunst, Architektur und Design.",
        },
        {
            userId: user.id,
            title: "Kunstmuseum Basel",
            city: "Basel",
            exhibition: "Sammlung Moderne Kunst",
            date: new Date("2025-02-15"),
            discovered_by: "Wochenendreise nach Basel",
            note: "Ein Museum, das man immer wieder besuchen kann.",
        },
        {
            userId: user.id,
            title: "Centre Pompidou",
            city: "Paris",
            exhibition: "Moderne und zeitgenössische Kunst",
            date: new Date("2024-10-11"),
            discovered_by: "Reise nach Paris",
            note: "Ein wichtiger Ort für Moderne.",
        },
        {
            userId: user.id,
            title: "Musée d'Orsay",
            city: "Paris",
            exhibition: "Impressionismus",
            date: new Date("2024-10-13"),
            discovered_by: "Reise nach Paris",
            note: "Licht, Farbe und Malerei.",
        },
        {
            userId: user.id,
            title: "Kunsthistorisches Museum",
            city: "Wien",
            exhibition: "Alte Meister",
            date: new Date("2024-09-12"),
            discovered_by: "Reise nach Wien",
            note: "Bosch, Bruegel und europäische Kunstgeschichte.",
        },
    ];

    const galleries = [
        {
            userId: user.id,
            title: "Galerie Max Hetzler",
            city: "Berlin",
            artist: "Albert Oehlen",
            exhibition: "Neue Arbeiten",
            date: new Date("2025-06-04"),
            note: "Starke zeitgenössische Positionen.",
        },
        {
            userId: user.id,
            title: "Esther Schipper",
            city: "Berlin",
            artist: "Various Artists",
            exhibition: "Contemporary Art",
            date: new Date("2025-06-05"),
            note: "Konzepte, Medien und zeitgenössische Kunst.",
        },
        {
            userId: user.id,
            title: "Sprüth Magers",
            city: "Berlin",
            artist: "Andreas Gursky",
            exhibition: "Photography",
            date: new Date("2025-06-06"),
            note: "Fotografie und konzeptuelle Kunst.",
        },
        {
            userId: user.id,
            title: "David Zwirner",
            city: "Berlin",
            artist: "Wolfgang Tillmans",
            exhibition: "Works",
            date: new Date("2025-06-07"),
            note: "Internationale zeitgenössische Kunst.",
        },
        {
            userId: user.id,
            title: "König Galerie",
            city: "Berlin",
            artist: "Various Artists",
            exhibition: "Contemporary Works",
            date: new Date("2025-06-08"),
            note: "Interessante junge und etablierte Positionen.",
        },
        {
            userId: user.id,
            title: "Galerie Neu",
            city: "Berlin",
            artist: "Various Artists",
            exhibition: "New Works",
            date: new Date("2025-06-09"),
            note: "Ein Berliner Ort für zeitgenössische Kunst.",
        },
        {
            userId: user.id,
            title: "Peres Projects",
            city: "Berlin",
            artist: "Various Artists",
            exhibition: "Group Exhibition",
            date: new Date("2025-06-10"),
            note: "Eine weitere spannende Berliner Galerie.",
        },
    ];

    const images = [
        {
            userId: user.id,
            title: "Untitled",
            creator: "Pablo Picasso",
            year: 1903,
            source: "Kunstbuch",
            discovered_by: "Zufälliger Fund in einem Katalog",
            note: "Eine blaue Figur, die mich wegen ihrer Ruhe behalten lässt.",
        },
        {
            userId: user.id,
            title: "Blue Study",
            creator: "Henri Matisse",
            year: 1911,
            source: "Ausstellungskatalog",
            discovered_by: "Matisse-Ausstellung",
            note: "Farbe fast ohne Gegenstand.",
        },
        {
            userId: user.id,
            title: "Composition",
            creator: "Wassily Kandinsky",
            year: 1926,
            source: "Archiv",
            discovered_by: "Kunstbuchhandlung",
            note: "Eine Seite, die eher wie Musik als wie ein Bild wirkt.",
        },
        {
            userId: user.id,
            title: "Still Life",
            creator: "Giorgio Morandi",
            year: 1956,
            source: "Museumskatalog",
            discovered_by: "Städel",
            note: "Reduktion, bis fast nichts mehr übrig bleibt.",
        },
        {
            userId: user.id,
            title: "Untitled",
            creator: "Sally Mann",
            year: 1990,
            source: "Fotobuch",
            discovered_by: "Fotobuchhandlung",
            note: "Eine stille, leicht unheimliche Erinnerung an Körper und Zeit.",
        },
        {
            userId: user.id,
            title: "Film Still",
            creator: "Ingmar Bergman",
            year: 1966,
            source: "Filmarchiv",
            discovered_by: "DFF",
            note: "Ein einzelner Frame, der als eigenes Bild funktioniert.",
        },
        {
            userId: user.id,
            title: "Blue Interior",
            creator: "David Hockney",
            year: 1970,
            source: "Kunstmagazin",
            discovered_by: "RAY",
            note: "Ein Raum, der durch Farbe größer wirkt als durch Perspektive.",
        },
        {
            userId: user.id,
            title: "Study No. 4",
            creator: "Egon Schiele",
            year: 1912,
            source: "Museumskatalog",
            discovered_by: "Leopold Museum",
            note: "Linie, Körper und Nervosität.",
        },
        {
            userId: user.id,
            title: "Untitled",
            creator: "Laura Makabresku",
            year: 2018,
            source: "Künstlerisches Archiv",
            discovered_by: "Zufälliger Fund",
            note: "Traum und Dunkelheit ohne klare Erklärung.",
        },
        {
            userId: user.id,
            title: "New York",
            creator: "Robert Frank",
            year: 1958,
            source: "Fotobuch",
            discovered_by: "Antiquariat",
            note: "Eine Stadt als Fragment.",
        },
        {
            userId: user.id,
            title: "Still Life",
            creator: "Josef Sudek",
            year: 1954,
            source: "Fotobuch",
            discovered_by: "Antiquariat in Prag",
            note: "Ein stilles Objekt wird zu einer ganzen Atmosphäre.",
        },
        {
            userId: user.id,
            title: "Portrait Study",
            creator: "Man Ray",
            year: 1926,
            source: "Kunstbuch",
            discovered_by: "Buchhandlung in Paris",
            note: "Surrealismus und Fotografie in einem Bild.",
        },
        {
            userId: user.id,
            title: "Red Interior",
            creator: "Henri Matisse",
            year: 1948,
            source: "Kunstbuch",
            discovered_by: "Kunstbuchhandlung",
            note: "Farbe als Raum.",
        },
        {
            userId: user.id,
            title: "The Blue Guitar",
            creator: "David Hockney",
            year: 1977,
            source: "Katalog",
            discovered_by: "Galeriebesuch",
            note: "Ein Motiv zwischen Musik und Bild.",
        },
        {
            userId: user.id,
            title: "Cinema",
            creator: "Jean-Luc Godard",
            year: 1965,
            source: "Filmarchiv",
            discovered_by: "Filmseminar",
            note: "Ein Bild aus einem Film, das unabhängig weiterlebt.",
        },
        {
            userId: user.id,
            title: "Paris",
            creator: "Brassaï",
            year: 1932,
            source: "Fotobuch",
            discovered_by: "Paris-Reise",
            note: "Nacht, Stein und künstliches Licht.",
        },
        {
            userId: user.id,
            title: "Berlin",
            creator: "Michael Schmidt",
            year: 1980,
            source: "Fotobuch",
            discovered_by: "Berlin-Reise",
            note: "Die Stadt ohne touristische Oberfläche.",
        },
        {
            userId: user.id,
            title: "Study of Light",
            creator: "Saul Leiter",
            year: 1960,
            source: "Fotografie-Ausstellung",
            discovered_by: "Fotografie-Ausstellung",
            note: "Farbe, Regen und fragmentierte Sicht.",
        },
        {
            userId: user.id,
            title: "Untitled",
            creator: "Francesca Woodman",
            year: 1977,
            source: "Fotobuch",
            discovered_by: "Empfehlung eines Freundes",
            note: "Körper als Spur statt als Porträt.",
        },
        {
            userId: user.id,
            title: "Interior",
            creator: "Josef Albers",
            year: 1950,
            source: "Kunstbuch",
            discovered_by: "Bauhaus-Archiv",
            note: "Farbe als Konstruktion.",
        },
        {
            userId: user.id,
            title: "Still Life",
            creator: "Paul Cézanne",
            year: 1895,
            source: "Museumskatalog",
            discovered_by: "Städel",
            note: "Ein Motiv, das immer wieder neu gebaut werden kann.",
        },
        {
            userId: user.id,
            title: "Landscape",
            creator: "Ansel Adams",
            year: 1942,
            source: "Fotobuch",
            discovered_by: "Fotografie-Abteilung",
            note: "Landschaft als reine Form und Licht.",
        },
    ];

    const photographs = [
        {
            userId: user.id,
            photographer: "Henri Cartier-Bresson",
            title: "Behind the Gare Saint-Lazare",
            location: "Paris",
            source: "Magnum Photos",
            note: "Ein entscheidender Moment zwischen Bewegung, Geometrie und Zufall.",
            imageUrl: commonsFile(
                "Henri Cartier-Bresson - Behind the Gare Saint-Lazare.jpg",
            ),
        },
        {
            userId: user.id,
            photographer: "Henri Cartier-Bresson",
            title: "Rue Mouffetard",
            location: "Paris",
            source: "Magnum Photos",
            note: "Ein alltäglicher Moment, der durch Timing und Blick zu einer kleinen Geschichte wird.",
            imageUrl: commonsFile(
                "Henri Cartier-Bresson - Rue Mouffetard.jpg",
            ),
        },
        {
            userId: user.id,
            photographer: "Henri Cartier-Bresson",
            title: "Hyères, France",
            location: "Hyères",
            source: "Magnum Photos",
            note: "Geometrie, Bewegung und der berühmte entscheidende Augenblick.",
            imageUrl: commonsFile("Henri Cartier-Bresson - Hyeres.jpg"),
        },
        {
            userId: user.id,
            photographer: "Henri Cartier-Bresson",
            title: "Seville, Spain",
            location: "Sevilla",
            source: "Magnum Photos",
            note: "Kinder, Architektur und ein Moment voller Energie.",
            imageUrl: commonsFile("Henri Cartier-Bresson - Seville.jpg"),
        },
        {
            userId: user.id,
            photographer: "Sally Mann",
            title: "Candy Cigarette",
            location: "Lexington, Virginia",
            source: "Sally Mann / Fotobuch",
            note: "Kindheit zwischen Unschuld, Pose und einer leichten Unruhe.",
            imageUrl: commonsFile("Sally Mann - Candy Cigarette.jpg"),
        },
        {
            userId: user.id,
            photographer: "Sally Mann",
            title: "Immediate Family",
            location: "Virginia, USA",
            source: "Sally Mann / Fotobuch",
            note: "Familie als intime, schöne und manchmal verstörende Landschaft.",
            imageUrl: commonsFile("Sally Mann.jpg"),
        },
        {
            userId: user.id,
            photographer: "Laura Makabresku",
            title: "Untitled",
            location: "Polen",
            source: "Künstlerisches Archiv",
            note: "Märchenhafte Dunkelheit und eine sehr persönliche Form von Melancholie.",
            imageUrl: commonsFile("Laura Makabresku.jpg"),
        },
        {
            userId: user.id,
            photographer: "Laura Makabresku",
            title: "Untitled II",
            location: "Polen",
            source: "Künstlerisches Archiv",
            note: "Eine stille, traumartige Szene zwischen Körper und Natur.",
            imageUrl: commonsFile("Laura Makabresku photography.jpg"),
        },
        {
            userId: user.id,
            photographer: "Alexey Titarenko",
            title: "City of Shadows",
            location: "St. Petersburg",
            source: "Fotobuch",
            note: "Lange Belichtungen machen Menschen zu Geistern in der Stadt.",
            imageUrl: commonsFile("Alexey Titarenko - City of Shadows.jpg"),
        },
        {
            userId: user.id,
            photographer: "Alexey Titarenko",
            title: "The Invisible",
            location: "St. Petersburg",
            source: "Fotobuch",
            note: "Die Stadt wirkt wie Erinnerung statt wie ein konkreter Ort.",
            imageUrl: commonsFile("Alexey Titarenko photography.jpg"),
        },
        {
            userId: user.id,
            photographer: "Constantine Manos",
            title: "American Color",
            location: "USA",
            source: "Magnum Photos",
            note: "Farbe, soziale Beobachtung und präzise komponierte Alltagsszenen.",
            imageUrl: commonsFile("Constantine Manos.jpg"),
        },
        {
            userId: user.id,
            photographer: "Constantine Manos",
            title: "Greek Portfolio",
            location: "Griechenland",
            source: "Magnum Photos",
            note: "Ein dokumentarischer Blick mit außergewöhnlichem Sinn für Farbe und Struktur.",
            imageUrl: commonsFile(
                "Constantine Manos - Greek Portfolio.jpg",
            ),
        },
        {
            userId: user.id,
            photographer: "Sebastião Salgado",
            title: "Workers",
            location: "Brasilien",
            source: "Magnum Photos",
            note: "Arbeit, Körper und Würde in monumentaler Schwarz-Weiß-Fotografie.",
            imageUrl: commonsFile("Sebastiao Salgado.jpg"),
        },
        {
            userId: user.id,
            photographer: "Sebastião Salgado",
            title: "Genesis",
            location: "Amazonien",
            source: "Fotobuch",
            note: "Eine langsame Betrachtung von Landschaft, Menschen und ursprünglichen Lebensräumen.",
            imageUrl: commonsFile("Sebastiao Salgado Genesis.jpg"),
        },
        {
            userId: user.id,
            photographer: "Elliott Erwitt",
            title: "California Kiss",
            location: "Kalifornien",
            source: "Magnum Photos",
            note: "Humor und Zärtlichkeit in einem einzigen präzisen Moment.",
            imageUrl: commonsFile("Elliott Erwitt California Kiss.jpg"),
        },
        {
            userId: user.id,
            photographer: "Robert Capa",
            title: "The Falling Soldier",
            location: "Spanien",
            source: "Magnum Photos",
            note: "Ein ikonisches Bild zwischen Dokumentation, Krieg und fotografischer Legende.",
            imageUrl: commonsFile("Robert Capa - Falling Soldier.jpg"),
        },
        {
            userId: user.id,
            photographer: "Robert Frank",
            title: "Trolley — New Orleans",
            location: "New Orleans",
            source: "Fotobuch",
            note: "Amerika als fragmentierte soziale Landschaft.",
            imageUrl: commonsFile(
                "Robert Frank Trolley New Orleans.jpg",
            ),
        },
        {
            userId: user.id,
            photographer: "Josef Koudelka",
            title: "Gypsies",
            location: "Tschechoslowakei",
            source: "Magnum Photos",
            note: "Reise, Freiheit und Beobachtung in starken Schwarz-Weiß-Bildern.",
            imageUrl: commonsFile("Josef Koudelka Gypsies.jpg"),
        },
        {
            userId: user.id,
            photographer: "Eve Arnold",
            title: "Marilyn Monroe",
            location: "USA",
            source: "Magnum Photos",
            note: "Ein intimer Blick hinter die öffentliche Figur.",
            imageUrl: commonsFile("Eve Arnold Marilyn Monroe.jpg"),
        },
        {
            userId: user.id,
            photographer: "Bruce Davidson",
            title: "East 100th Street",
            location: "New York",
            source: "Magnum Photos",
            note: "Nähe, Nachbarschaft und Alltag ohne romantische Distanz.",
            imageUrl: commonsFile(
                "Bruce Davidson East 100th Street.jpg",
            ),
        },
        {
            userId: user.id,
            photographer: "Inge Morath",
            title: "Spain",
            location: "Spanien",
            source: "Magnum Photos",
            note: "Reise und Beobachtung mit einem ruhigen, menschlichen Blick.",
            imageUrl: commonsFile("Inge Morath Spain.jpg"),
        },
    ];

    const ideas = [
        {
            userId: user.id,
            title: "Archiv der verlorenen Dinge",
            category: "Projekt",
            inspiration:
                "Museen, Flohmärkte, alte Fotografien und persönliche Erinnerungen.",
            description:
                "Ein visuelles Archiv von Dingen, die Menschen einmal besessen, geliebt oder verloren haben. Jedes Objekt bekommt seine eigene kleine Geschichte.",
            next_step:
                "Die ersten 20 Objekte sammeln und ihre Geschichten notieren.",
        },
        {
            userId: user.id,
            title: "Ein Museum für persönliche Erinnerungen",
            category: "Konzept",
            inspiration:
                "DFF, Städel und persönliche Sammlungen.",
            description:
                "Ein imaginäres Museum, in dem keine berühmten Kunstwerke ausgestellt werden, sondern Dinge, Bilder, Musik und Sätze, die für eine einzelne Person wichtig geworden sind.",
            next_step: "Die ersten zehn Räume definieren.",
        },
    ];

    const quotes = [
        {
            userId: user.id,
            title: "Vor allem: Belüge dich selbst nicht.",
            author: "Fjodor Dostojewski",
            source: "Die Brüder Karamasow",
            year: 1880,
            context:
                "Über Ehrlichkeit mit sich selbst und moralische Verantwortung.",
        },
        {
            userId: user.id,
            title:
                "Schmerz und Leiden sind für einen großen Geist und ein tiefes Herz immer unvermeidlich.",
            author: "Fjodor Dostojewski",
            source: "Schuld und Sühne",
            year: 1866,
            context: "Über Intelligenz, Sensibilität und Leiden.",
        },
        {
            userId: user.id,
            title: "Ich bin ein kranker Mensch.",
            author: "Fjodor Dostojewski",
            source: "Aufzeichnungen aus dem Kellerloch",
            year: 1864,
            context:
                "Der Beginn eines radikalen inneren Monologs.",
        },
        {
            userId: user.id,
            title:
                "Auf einen Mörder kann man sich immer verlassen, wenn es um eine kunstvolle Prosa geht.",
            author: "Vladimir Nabokov",
            source: "Lolita",
            year: 1955,
            context:
                "Über Sprache, Stil und die Selbstinszenierung des Erzählers.",
        },
        {
            userId: user.id,
            title:
                "Wir liegen alle in der Gosse, aber einige von uns schauen zu den Sternen.",
            author: "Oscar Wilde",
            source: "Lady Windermere's Fan",
            year: 1892,
            context: "Über Perspektive und Hoffnung.",
        },
        {
            userId: user.id,
            title:
                "Ich öffnete mich der sanften Gleichgültigkeit des Universums.",
            author: "Albert Camus",
            source: "Der Fremde",
            year: 1942,
            context: "Die Akzeptanz der Absurdität.",
        },
        {
            userId: user.id,
            title:
                "Eine Frau braucht Geld und ein eigenes Zimmer, wenn sie Belletristik schreiben will.",
            author: "Virginia Woolf",
            source: "Ein Zimmer für sich allein",
            year: 1929,
            context:
                "Unabhängigkeit als Voraussetzung für kreatives Arbeiten.",
        },
        {
            userId: user.id,
            title: "Jemand musste Josef K. verleumdet haben.",
            author: "Franz Kafka",
            source: "Der Prozess",
            year: 1925,
            context:
                "Der Beginn eines absurden bürokratischen Albtraums.",
        },
        {
            userId: user.id,
            title: "Weisheit kann man nicht vermitteln.",
            author: "Hermann Hesse",
            source: "Siddhartha",
            year: 1922,
            context:
                "Der Unterschied zwischen Wissen und gelebter Erfahrung.",
        },
        {
            userId: user.id,
            title: "Der Große Bruder beobachtet dich.",
            author: "George Orwell",
            source: "1984",
            year: 1949,
            context: "Überwachung und politische Kontrolle.",
        },
        {
            userId: user.id,
            title:
                "Alle Tiere sind gleich, aber manche Tiere sind gleicher als andere.",
            author: "George Orwell",
            source: "Animal Farm",
            year: 1945,
            context: "Die Korruption politischer Sprache.",
        },
        {
            userId: user.id,
            title:
                "Die eigentliche Geschichte der Menschheit beginnt mit der kognitiven Revolution.",
            author: "Yuval Noah Harari",
            source: "Sapiens",
            year: 2011,
            context:
                "Hararis Idee von der kognitiven Revolution.",
        },
        {
            userId: user.id,
            title:
                "Ich habe kein Geld, keine Mittel und keine Hoffnung.",
            author: "Henry Miller",
            source: "Tropic of Cancer",
            year: 1934,
            context:
                "Millers paradoxe Beziehung zu Armut und Freiheit.",
        },
    ];

    await prisma.book.createMany({ data: books });
    await prisma.music.createMany({ data: vinyl });
    await prisma.music.createMany({ data: tracks });
    await prisma.magazine.createMany({ data: magazines });
    await prisma.artwork.createMany({ data: artworks });
    await prisma.museum.createMany({ data: museums });
    await prisma.gallery.createMany({ data: galleries });
    await prisma.image.createMany({ data: images });
    await prisma.photograph.createMany({ data: photographs });
    await prisma.idea.createMany({ data: ideas });
    await prisma.quote.createMany({ data: quotes });

    console.log("Seed erfolgreich abgeschlossen.");
    console.log("20 Bücher");
    console.log("40 Musik — 12 Vinyl + 28 Tracks");
    console.log("5 Magazine");
    console.log("13 Kunstwerke");
    console.log("12 Museen");
    console.log("7 Galerien");
    console.log("22 Bilder");
    console.log("21 Fotografien");
    console.log("2 Ideen");
    console.log("13 Zitate");
    console.log("Gesamt: 155 Objekte");
}

seed()
    .catch((error) => {
        console.error(error);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });