const books = [
    {
        title: "Lolita",
        author: "Vladimir Nabokov",
        year: "1955",
        pages: 336,
        discovered_by: "Buchhandlung in Berlin",
        note: "Eine sprachlich außergewöhnliche Erzählung über Obsession, Selbsttäuschung und die Macht eines unzuverlässigen Erzählers. Das Buch entfaltet seine Wirkung weniger durch schnelle Antworten als durch die Spannung seiner Sprache und Figuren. Gerade die Ambivalenz bleibt lange nach der letzten Seite im Gedächtnis.",
        bestQuote: "„Lolita erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Vladimir Nabokov bleibt besonders die Erinnerung an Buchhandlung in Berlin mit diesem Werk verbunden.“",
        imageUrl: "/images/collections/books/1.jpg",
    },
    {
        title: "Pnin",
        author: "Vladimir Nabokov",
        year: "1957",
        pages: 191,
        discovered_by: "Empfehlung eines Freundes",
        note: "Eine zärtliche und zugleich ironische Nabokov-Figur zwischen Erinnerung, Fremdsein und Komik. Hier wird eine vertraute Welt so präzise beobachtet, dass selbst kleine Gesten Bedeutung bekommen. Die Lektüre lebt von Zwischentönen, Widersprüchen und einer eigenwilligen Atmosphäre.",
        bestQuote: "„Pnin erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Vladimir Nabokov bleibt besonders die Erinnerung an Empfehlung eines Freundes mit diesem Werk verbunden.“",
        imageUrl: "/images/collections/books/2.jpg",
    },
    {
        title: "Ada or Ardor",
        author: "Vladimir Nabokov",
        year: "1969",
        pages: 589,
        discovered_by: "Antiquariat in Paris",
        note: "Eine obsessive, verspielte und vollkommen eigenwillige Welt. Die Erzählung verbindet große Ideen mit sehr persönlichen Konflikten. Dadurch entsteht ein Text, der zugleich intellektuell herausfordernd und emotional nah wirkt.",
        bestQuote: "„Ada or Ardor erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Vladimir Nabokov bleibt besonders die Erinnerung an Antiquariat in Paris mit diesem Werk verbunden.“",
        imageUrl: "/images/collections/books/3.jpg",
    },
    {
        title: "Die Brüder Karamasow",
        author: "Fjodor Dostojewski",
        year: "1880",
        pages: 796,
        discovered_by: "Empfehlung eines Freundes",
        note: "Glaube, Zweifel, Freiheit, Schuld und die schwierigsten Fragen menschlicher Existenz. Das Buch entfaltet seine Wirkung weniger durch schnelle Antworten als durch die Spannung seiner Sprache und Figuren. Gerade die Ambivalenz bleibt lange nach der letzten Seite im Gedächtnis.",
        bestQuote: "„Die Brüder Karamasow erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Fjodor Dostojewski bleibt besonders die Erinnerung an Empfehlung eines Freundes mit diesem Werk verbunden.“",
        imageUrl: "/images/collections/books/4.webp",
    },
    {
        title: "Schuld und Sühne",
        author: "Fjodor Dostojewski",
        year: "1866",
        pages: 671,
        discovered_by: "Leseliste für einen langen Winter",
        note: "Psychologie, Schuld und die Grenzen moralischer Selbstrechtfertigung. Hier wird eine vertraute Welt so präzise beobachtet, dass selbst kleine Gesten Bedeutung bekommen. Die Lektüre lebt von Zwischentönen, Widersprüchen und einer eigenwilligen Atmosphäre.",
        bestQuote: "„Schuld und Sühne erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Fjodor Dostojewski bleibt besonders die Erinnerung an Leseliste für einen langen Winter mit diesem Werk verbunden.“",
        imageUrl: "/images/collections/books/5.jpg",
    },
    {
        title: "Aufzeichnungen aus dem Kellerloch",
        author: "Fjodor Dostojewski",
        year: "1864",
        pages: 160,
        discovered_by: "Universitätsbibliothek",
        note: "Bewusstsein, Trotz und der Widerstand gegen eine allzu vernünftige Welt. Die Erzählung verbindet große Ideen mit sehr persönlichen Konflikten. Dadurch entsteht ein Text, der zugleich intellektuell herausfordernd und emotional nah wirkt.",
        bestQuote: "„Aufzeichnungen aus dem Kellerloch erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Fjodor Dostojewski bleibt besonders die Erinnerung an Universitätsbibliothek mit diesem Werk verbunden.“",
        imageUrl: "/images/collections/books/6.webp",
    },
    {
        title: "Der Idiot",
        author: "Fjodor Dostojewski",
        year: "1869",
        pages: 656,
        discovered_by: "Buchhandlung in Frankfurt",
        note: "Mitgefühl, Naivität und die Frage, ob Güte in einer zynischen Welt bestehen kann. Das Buch entfaltet seine Wirkung weniger durch schnelle Antworten als durch die Spannung seiner Sprache und Figuren. Gerade die Ambivalenz bleibt lange nach der letzten Seite im Gedächtnis.",
        bestQuote: "„Der Idiot erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Fjodor Dostojewski bleibt besonders die Erinnerung an Buchhandlung in Frankfurt mit diesem Werk verbunden.“",
        imageUrl: "/images/collections/books/7.webp",
    },
    {
        title: "Tropic of Cancer",
        author: "Henry Miller",
        year: "1934",
        pages: 318,
        discovered_by: "Buchladen in Prag",
        note: "Paris, Armut, Sexualität, Schreiben und radikale künstlerische Freiheit. Hier wird eine vertraute Welt so präzise beobachtet, dass selbst kleine Gesten Bedeutung bekommen. Die Lektüre lebt von Zwischentönen, Widersprüchen und einer eigenwilligen Atmosphäre.",
        bestQuote: "„Tropic of Cancer erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Henry Miller bleibt besonders die Erinnerung an Buchladen in Prag mit diesem Werk verbunden.“",
        imageUrl: "/images/collections/books/8.jpg",
    },
    {
        title: "Tropic of Capricorn",
        author: "Henry Miller",
        year: "1939",
        pages: 384,
        discovered_by: "Empfehlung eines Schriftstellers",
        note: "Autobiografischer, wilder und sehr persönlicher Miller. Die Erzählung verbindet große Ideen mit sehr persönlichen Konflikten. Dadurch entsteht ein Text, der zugleich intellektuell herausfordernd und emotional nah wirkt.",
        bestQuote: "„Tropic of Capricorn erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Henry Miller bleibt besonders die Erinnerung an Empfehlung eines Schriftstellers mit diesem Werk verbunden.“",
        imageUrl: "/images/collections/books/9.jpg",
    },
    {
        title: "1984",
        author: "George Orwell",
        year: "1949",
        pages: 328,
        discovered_by: "Schulbibliothek",
        note: "Überwachung, Sprache, politische Macht und die Zerstörung unabhängigen Denkens. Das Buch entfaltet seine Wirkung weniger durch schnelle Antworten als durch die Spannung seiner Sprache und Figuren. Gerade die Ambivalenz bleibt lange nach der letzten Seite im Gedächtnis.",
        bestQuote: "„1984 erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei George Orwell bleibt besonders die Erinnerung an Schulbibliothek mit diesem Werk verbunden.“",
        imageUrl: "/images/collections/books/10.jpg",
    },
    {
        title: "Animal Farm",
        author: "George Orwell",
        year: "1945",
        pages: 112,
        discovered_by: "Empfehlung eines Freundes",
        note: "Eine kleine politische Fabel über Macht und ihre Korruption. Hier wird eine vertraute Welt so präzise beobachtet, dass selbst kleine Gesten Bedeutung bekommen. Die Lektüre lebt von Zwischentönen, Widersprüchen und einer eigenwilligen Atmosphäre.",
        bestQuote: "„Animal Farm erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei George Orwell bleibt besonders die Erinnerung an Empfehlung eines Freundes mit diesem Werk verbunden.“",
        imageUrl: "/images/collections/books/11.jpeg",
    },
    {
        title: "Der Steppenwolf",
        author: "Hermann Hesse",
        year: "1927",
        pages: 237,
        discovered_by: "Buchhandlung in Frankfurt",
        note: "Für Menschen, die sich zwischen mehreren Versionen ihrer selbst bewegen. Die Erzählung verbindet große Ideen mit sehr persönlichen Konflikten. Dadurch entsteht ein Text, der zugleich intellektuell herausfordernd und emotional nah wirkt.",
        bestQuote: "„Der Steppenwolf erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Hermann Hesse bleibt besonders die Erinnerung an Buchhandlung in Frankfurt mit diesem Werk verbunden.“",
        imageUrl: "/images/collections/books/12.jpg",
    },
    {
        title: "Siddhartha",
        author: "Hermann Hesse",
        year: "1922",
        pages: 152,
        discovered_by: "Reise nach Zürich",
        note: "Die Suche nach einem eigenen Weg statt nach einer fertigen Wahrheit. Das Buch entfaltet seine Wirkung weniger durch schnelle Antworten als durch die Spannung seiner Sprache und Figuren. Gerade die Ambivalenz bleibt lange nach der letzten Seite im Gedächtnis.",
        bestQuote: "„Siddhartha erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Hermann Hesse bleibt besonders die Erinnerung an Reise nach Zürich mit diesem Werk verbunden.“",
        imageUrl: "/images/collections/books/13.jpg",
    },
    {
        title: "Demian",
        author: "Hermann Hesse",
        year: "1919",
        pages: 176,
        discovered_by: "Empfehlung eines Freundes",
        note: "Identität, Erwachsenwerden und die Suche nach dem eigenen inneren Weg. Hier wird eine vertraute Welt so präzise beobachtet, dass selbst kleine Gesten Bedeutung bekommen. Die Lektüre lebt von Zwischentönen, Widersprüchen und einer eigenwilligen Atmosphäre.",
        bestQuote: "„Demian erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Hermann Hesse bleibt besonders die Erinnerung an Empfehlung eines Freundes mit diesem Werk verbunden.“",
        imageUrl: "/images/collections/books/14.jpg",
    },
    {
        title: "Sapiens",
        author: "Yuval Noah Harari",
        year: "2011",
        pages: 443,
        discovered_by: "Empfehlung beim Abendessen",
        note: "Geschichte der Menschheit und die Geschichten, die Gesellschaften zusammenhalten. Die Erzählung verbindet große Ideen mit sehr persönlichen Konflikten. Dadurch entsteht ein Text, der zugleich intellektuell herausfordernd und emotional nah wirkt.",
        bestQuote: "„Sapiens erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Yuval Noah Harari bleibt besonders die Erinnerung an Empfehlung beim Abendessen mit diesem Werk verbunden.“",
        imageUrl: "/images/collections/books/15.jpg",
    },
    {
        title: "Homo Deus",
        author: "Yuval Noah Harari",
        year: "2015",
        pages: 449,
        discovered_by: "Buchhandlung am Bahnhof",
        note: "Technologie, Zukunft und die mögliche nächste Phase der Menschheit. Das Buch entfaltet seine Wirkung weniger durch schnelle Antworten als durch die Spannung seiner Sprache und Figuren. Gerade die Ambivalenz bleibt lange nach der letzten Seite im Gedächtnis.",
        bestQuote: "„Homo Deus erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Yuval Noah Harari bleibt besonders die Erinnerung an Buchhandlung am Bahnhof mit diesem Werk verbunden.“",
        imageUrl: "/images/collections/books/16.jpeg",
    },
    {
        title: "21 Lessons for the 21st Century",
        author: "Yuval Noah Harari",
        year: "2018",
        pages: 372,
        discovered_by: "Flughafenbuchhandlung",
        note: "Gegenwart, Technologie, Politik und die Frage, worauf Menschen ihre Aufmerksamkeit richten sollten. Hier wird eine vertraute Welt so präzise beobachtet, dass selbst kleine Gesten Bedeutung bekommen. Die Lektüre lebt von Zwischentönen, Widersprüchen und einer eigenwilligen Atmosphäre.",
        bestQuote: "„21 Lessons for the 21st Century erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Yuval Noah Harari bleibt besonders die Erinnerung an Flughafenbuchhandlung mit diesem Werk verbunden.“",
        imageUrl: "/images/collections/books/17.jpg",
    },
    {
        title: "Der Fremde",
        author: "Albert Camus",
        year: "1942",
        pages: 123,
        discovered_by: "Französische Buchhandlung",
        note: "Absurdität, Entfremdung und emotionale Distanz. Die Erzählung verbindet große Ideen mit sehr persönlichen Konflikten. Dadurch entsteht ein Text, der zugleich intellektuell herausfordernd und emotional nah wirkt.",
        bestQuote: "„Der Fremde erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Albert Camus bleibt besonders die Erinnerung an Französische Buchhandlung mit diesem Werk verbunden.“",
        imageUrl: "/images/collections/books/18.webp",
    },
    {
        title: "Der Prozess",
        author: "Franz Kafka",
        year: "1925",
        pages: 255,
        discovered_by: "Spaziergang durch Prag",
        note: "Bürokratie, Schuld und das Gefühl, in einem unverständlichen System gefangen zu sein. Das Buch entfaltet seine Wirkung weniger durch schnelle Antworten als durch die Spannung seiner Sprache und Figuren. Gerade die Ambivalenz bleibt lange nach der letzten Seite im Gedächtnis.",
        bestQuote: "„Der Prozess erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Franz Kafka bleibt besonders die Erinnerung an Spaziergang durch Prag mit diesem Werk verbunden.“",
        imageUrl: "/images/collections/books/19.webp",
    },
    {
        title: "Ein Zimmer für sich allein",
        author: "Virginia Woolf",
        year: "1929",
        pages: 112,
        discovered_by: "Buchhandlung für Kunst und Literatur",
        note: "Unabhängigkeit, Geld und geistiger Raum als Voraussetzung für Kreativität. Hier wird eine vertraute Welt so präzise beobachtet, dass selbst kleine Gesten Bedeutung bekommen. Die Lektüre lebt von Zwischentönen, Widersprüchen und einer eigenwilligen Atmosphäre.",
        bestQuote: "„Ein Zimmer für sich allein erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Virginia Woolf bleibt besonders die Erinnerung an Buchhandlung für Kunst und Literatur mit diesem Werk verbunden.“",
        imageUrl: "/images/collections/books/20.jpeg",
    },
];

const vinyl = [
    {
        format: "Physisch",
        title: "The Dark Side of the Moon",
        author: "Pink Floyd",
        year: "1973",
        discovered_by: "Plattenladen in Berlin",
        note: "Eine Platte, die wegen Klang, Atmosphäre und Erinnerung geblieben ist. Beim Hören entsteht ein eigener Raum aus Klang, Erinnerung und Zeit. Besonders stark ist, wie das Album auch nach vielen Durchläufen neue Details freigibt.",
        bestQuote: "„The Dark Side of the Moon erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Pink Floyd bleibt besonders die Erinnerung an Plattenladen in Berlin mit diesem Werk verbunden.“",
        imageUrl: "/images/collections/vinyl/1.webp",
    },
    {
        format: "Physisch",
        title: "Wish You Were Here",
        author: "Pink Floyd",
        year: "1975",
        discovered_by: "Plattenbörse in Frankfurt",
        note: "Eine Platte, die wegen Klang, Atmosphäre und Erinnerung geblieben ist. Diese Platte funktioniert als geschlossenes Ganzes und nicht nur als Sammlung einzelner Songs. Ihre Atmosphäre verändert sich mit Stimmung, Ort und dem Moment des Hörens.",
        bestQuote: "„Wish You Were Here erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Pink Floyd bleibt besonders die Erinnerung an Plattenbörse in Frankfurt mit diesem Werk verbunden.“",
        imageUrl: "/images/collections/vinyl/2.webp",
    },
    {
        format: "Physisch",
        title: "Animals",
        author: "Pink Floyd",
        year: "1977",
        discovered_by: "Empfehlung eines Musikers",
        note: "Eine Platte, die wegen Klang, Atmosphäre und Erinnerung geblieben ist. Der Klang trägt eine sehr eigene Handschrift und macht jede Wiederholung anders. Zwischen den großen Momenten sind es oft die kleinen musikalischen Details, die hängen bleiben.",
        bestQuote: "„Animals erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Pink Floyd bleibt besonders die Erinnerung an Empfehlung eines Musikers mit diesem Werk verbunden.“",
        imageUrl: "/images/collections/vinyl/3.webp",
    },
    {
        format: "Physisch",
        title: "Rain Dogs",
        author: "Tom Waits",
        year: "1985",
        discovered_by: "Vinyl-Abteilung in Paris",
        note: "Eine Platte, die wegen Klang, Atmosphäre und Erinnerung geblieben ist. Beim Hören entsteht ein eigener Raum aus Klang, Erinnerung und Zeit. Besonders stark ist, wie das Album auch nach vielen Durchläufen neue Details freigibt.",
        bestQuote: "„Rain Dogs erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Tom Waits bleibt besonders die Erinnerung an Vinyl-Abteilung in Paris mit diesem Werk verbunden.“",
        imageUrl: "/images/collections/vinyl/4.webp",
    },
    {
        format: "Physisch",
        title: "I'm Your Man",
        author: "Leonard Cohen",
        year: "1988",
        discovered_by: "Plattenladen in Wien",
        note: "Eine Platte, die wegen Klang, Atmosphäre und Erinnerung geblieben ist. Diese Platte funktioniert als geschlossenes Ganzes und nicht nur als Sammlung einzelner Songs. Ihre Atmosphäre verändert sich mit Stimmung, Ort und dem Moment des Hörens.",
        bestQuote: "„I'm Your Man erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Leonard Cohen bleibt besonders die Erinnerung an Plattenladen in Wien mit diesem Werk verbunden.“",
        imageUrl: "/images/collections/vinyl/5.webp",
    },
    {
        format: "Physisch",
        title: "The Queen Is Dead",
        author: "The Smiths",
        year: "1986",
        discovered_by: "Empfehlung eines Freundes",
        note: "Eine Platte, die wegen Klang, Atmosphäre und Erinnerung geblieben ist. Der Klang trägt eine sehr eigene Handschrift und macht jede Wiederholung anders. Zwischen den großen Momenten sind es oft die kleinen musikalischen Details, die hängen bleiben.",
        bestQuote: "„The Queen Is Dead erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei The Smiths bleibt besonders die Erinnerung an Empfehlung eines Freundes mit diesem Werk verbunden.“",
        imageUrl: "/images/collections/vinyl/6.webp",
    },
    {
        format: "Physisch",
        title: "Unknown Pleasures",
        author: "Joy Division",
        year: "1979",
        discovered_by: "Plattenladen in Manchester",
        note: "Eine Platte, die wegen Klang, Atmosphäre und Erinnerung geblieben ist. Beim Hören entsteht ein eigener Raum aus Klang, Erinnerung und Zeit. Besonders stark ist, wie das Album auch nach vielen Durchläufen neue Details freigibt.",
        bestQuote: "„Unknown Pleasures erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Joy Division bleibt besonders die Erinnerung an Plattenladen in Manchester mit diesem Werk verbunden.“",
        imageUrl: "/images/collections/vinyl/7.jpeg",
    },
    {
        format: "Physisch",
        title: "Closer",
        author: "Joy Division",
        year: "1980",
        discovered_by: "Second-Hand-Plattenladen",
        note: "Eine Platte, die wegen Klang, Atmosphäre und Erinnerung geblieben ist. Diese Platte funktioniert als geschlossenes Ganzes und nicht nur als Sammlung einzelner Songs. Ihre Atmosphäre verändert sich mit Stimmung, Ort und dem Moment des Hörens.",
        bestQuote: "„Closer erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Joy Division bleibt besonders die Erinnerung an Second-Hand-Plattenladen mit diesem Werk verbunden.“",
        imageUrl: "/images/collections/vinyl/8.jpg",
    },
    {
        format: "Physisch",
        title: "The Velvet Underground & Nico",
        author: "The Velvet Underground & Nico",
        year: "1967",
        discovered_by: "Plattenbörse",
        note: "Eine Platte, die wegen Klang, Atmosphäre und Erinnerung geblieben ist. Der Klang trägt eine sehr eigene Handschrift und macht jede Wiederholung anders. Zwischen den großen Momenten sind es oft die kleinen musikalischen Details, die hängen bleiben.",
        bestQuote: "„The Velvet Underground & Nico erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei The Velvet Underground & Nico bleibt besonders die Erinnerung an Plattenbörse mit diesem Werk verbunden.“",
        imageUrl: "/images/collections/vinyl/9.webp",
    },
    {
        format: "Physisch",
        title: "Selected Ambient Works 85–92",
        author: "Aphex Twin",
        year: "1992",
        discovered_by: "Empfehlung eines DJs",
        note: "Eine Platte, die wegen Klang, Atmosphäre und Erinnerung geblieben ist. Beim Hören entsteht ein eigener Raum aus Klang, Erinnerung und Zeit. Besonders stark ist, wie das Album auch nach vielen Durchläufen neue Details freigibt.",
        bestQuote: "„Selected Ambient Works 85–92 erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Aphex Twin bleibt besonders die Erinnerung an Empfehlung eines DJs mit diesem Werk verbunden.“",
        imageUrl: "/images/collections/vinyl/10.webp",
    },
    {
        format: "Physisch",
        title: "Die Mensch·Maschine",
        author: "Kraftwerk",
        year: "1978",
        discovered_by: "Plattenladen in Düsseldorf",
        note: "Eine Platte, die wegen Klang, Atmosphäre und Erinnerung geblieben ist. Diese Platte funktioniert als geschlossenes Ganzes und nicht nur als Sammlung einzelner Songs. Ihre Atmosphäre verändert sich mit Stimmung, Ort und dem Moment des Hörens.",
        bestQuote: "„Die Mensch·Maschine erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Kraftwerk bleibt besonders die Erinnerung an Plattenladen in Düsseldorf mit diesem Werk verbunden.“",
        imageUrl: "/images/collections/vinyl/11.webp",
    },
    {
        format: "Physisch",
        title: "The Köln Concert",
        author: "Keith Jarrett",
        year: "1975",
        discovered_by: "Jazz-Abteilung eines Antiquariats",
        note: "Eine Platte, die wegen Klang, Atmosphäre und Erinnerung geblieben ist. Der Klang trägt eine sehr eigene Handschrift und macht jede Wiederholung anders. Zwischen den großen Momenten sind es oft die kleinen musikalischen Details, die hängen bleiben.",
        bestQuote: "„The Köln Concert erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Keith Jarrett bleibt besonders die Erinnerung an Jazz-Abteilung eines Antiquariats mit diesem Werk verbunden.“",
        imageUrl: "/images/collections/vinyl/12.jpg",
    },
];

const tracks = [
    {
        format: "Digital",
        title: "Shine On You Crazy Diamond",
        author: "Pink Floyd",
        year: "1975",
        discovered_by: "Plattenabend",
        note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist. Der Song verdichtet eine Stimmung in wenigen Minuten und bleibt gerade deshalb so unmittelbar. Melodie, Stimme und Produktion greifen ineinander, ohne ihre Eigenart zu verlieren.",
        bestQuote: "„Shine On You Crazy Diamond erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Pink Floyd bleibt besonders die Erinnerung an Plattenabend mit diesem Werk verbunden.“",
    },
    {
        format: "Digital",
        title: "Comfortably Numb",
        author: "Pink Floyd",
        year: "1979",
        discovered_by: "Spotify-Radio",
        note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist. Hier zählt nicht nur der Refrain, sondern auch das, was zwischen den einzelnen Passagen passiert. Der Track verändert seine Wirkung je nachdem, wann und wie man ihn hört.",
        bestQuote: "„Comfortably Numb erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Pink Floyd bleibt besonders die Erinnerung an Spotify-Radio mit diesem Werk verbunden.“",
    },
    {
        format: "Digital",
        title: "Echoes",
        author: "Pink Floyd",
        year: "1971",
        discovered_by: "Plattenabend",
        note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist. Ein Stück mit einer klaren emotionalen Temperatur und einer starken klanglichen Identität. Gerade seine Details machen aus einem kurzen Moment etwas, das im Kopf weiterläuft.",
        bestQuote: "„Echoes erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Pink Floyd bleibt besonders die Erinnerung an Plattenabend mit diesem Werk verbunden.“",
    },
    {
        format: "Digital",
        title: "Us and Them",
        author: "Pink Floyd",
        year: "1973",
        discovered_by: "Lieblingsplaylist",
        note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist. Der Song verdichtet eine Stimmung in wenigen Minuten und bleibt gerade deshalb so unmittelbar. Melodie, Stimme und Produktion greifen ineinander, ohne ihre Eigenart zu verlieren.",
        bestQuote: "„Us and Them erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Pink Floyd bleibt besonders die Erinnerung an Lieblingsplaylist mit diesem Werk verbunden.“",
    },
    {
        format: "Digital",
        title: "Time",
        author: "Pink Floyd",
        year: "1973",
        discovered_by: "Alte Playlist",
        note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist. Hier zählt nicht nur der Refrain, sondern auch das, was zwischen den einzelnen Passagen passiert. Der Track verändert seine Wirkung je nachdem, wann und wie man ihn hört.",
        bestQuote: "„Time erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Pink Floyd bleibt besonders die Erinnerung an Alte Playlist mit diesem Werk verbunden.“",
    },
    {
        format: "Digital",
        title: "Wish You Were Here",
        author: "Pink Floyd",
        year: "1975",
        discovered_by: "Alte Playlist",
        note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist. Ein Stück mit einer klaren emotionalen Temperatur und einer starken klanglichen Identität. Gerade seine Details machen aus einem kurzen Moment etwas, das im Kopf weiterläuft.",
        bestQuote: "„Wish You Were Here erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Pink Floyd bleibt besonders die Erinnerung an Alte Playlist mit diesem Werk verbunden.“",
    },
    {
        format: "Digital",
        title: "Hallelujah",
        author: "Leonard Cohen",
        year: "1984",
        discovered_by: "Filmabend",
        note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist. Der Song verdichtet eine Stimmung in wenigen Minuten und bleibt gerade deshalb so unmittelbar. Melodie, Stimme und Produktion greifen ineinander, ohne ihre Eigenart zu verlieren.",
        bestQuote: "„Hallelujah erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Leonard Cohen bleibt besonders die Erinnerung an Filmabend mit diesem Werk verbunden.“",
    },
    {
        format: "Digital",
        title: "Famous Blue Raincoat",
        author: "Leonard Cohen",
        year: "1971",
        discovered_by: "Empfehlung eines Freundes",
        note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist. Hier zählt nicht nur der Refrain, sondern auch das, was zwischen den einzelnen Passagen passiert. Der Track verändert seine Wirkung je nachdem, wann und wie man ihn hört.",
        bestQuote: "„Famous Blue Raincoat erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Leonard Cohen bleibt besonders die Erinnerung an Empfehlung eines Freundes mit diesem Werk verbunden.“",
    },
    {
        format: "Digital",
        title: "The Partisan",
        author: "Leonard Cohen",
        year: "1969",
        discovered_by: "Dokumentarfilm",
        note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist. Ein Stück mit einer klaren emotionalen Temperatur und einer starken klanglichen Identität. Gerade seine Details machen aus einem kurzen Moment etwas, das im Kopf weiterläuft.",
        bestQuote: "„The Partisan erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Leonard Cohen bleibt besonders die Erinnerung an Dokumentarfilm mit diesem Werk verbunden.“",
    },
    {
        format: "Digital",
        title: "Tango Till They're Sore",
        author: "Tom Waits",
        year: "1985",
        discovered_by: "Tom-Waits-Playlist",
        note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist. Der Song verdichtet eine Stimmung in wenigen Minuten und bleibt gerade deshalb so unmittelbar. Melodie, Stimme und Produktion greifen ineinander, ohne ihre Eigenart zu verlieren.",
        bestQuote: "„Tango Till They're Sore erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Tom Waits bleibt besonders die Erinnerung an Tom-Waits-Playlist mit diesem Werk verbunden.“",
    },
    {
        format: "Digital",
        title: "Jockey Full of Bourbon",
        author: "Tom Waits",
        year: "1985",
        discovered_by: "Film entdeckt",
        note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist. Hier zählt nicht nur der Refrain, sondern auch das, was zwischen den einzelnen Passagen passiert. Der Track verändert seine Wirkung je nachdem, wann und wie man ihn hört.",
        bestQuote: "„Jockey Full of Bourbon erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Tom Waits bleibt besonders die Erinnerung an Film entdeckt mit diesem Werk verbunden.“",
    },
    {
        format: "Digital",
        title: "There Is a Light That Never Goes Out",
        author: "The Smiths",
        year: "1986",
        discovered_by: "Alte Playlist",
        note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist. Ein Stück mit einer klaren emotionalen Temperatur und einer starken klanglichen Identität. Gerade seine Details machen aus einem kurzen Moment etwas, das im Kopf weiterläuft.",
        bestQuote: "„There Is a Light That Never Goes Out erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei The Smiths bleibt besonders die Erinnerung an Alte Playlist mit diesem Werk verbunden.“",
    },
    {
        format: "Digital",
        title: "Heaven Knows I'm Miserable Now",
        author: "The Smiths",
        year: "1984",
        discovered_by: "Empfehlung eines Freundes",
        note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist. Der Song verdichtet eine Stimmung in wenigen Minuten und bleibt gerade deshalb so unmittelbar. Melodie, Stimme und Produktion greifen ineinander, ohne ihre Eigenart zu verlieren.",
        bestQuote: "„Heaven Knows I'm Miserable Now erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei The Smiths bleibt besonders die Erinnerung an Empfehlung eines Freundes mit diesem Werk verbunden.“",
    },
    {
        format: "Digital",
        title: "Love Will Tear Us Apart",
        author: "Joy Division",
        year: "1980",
        discovered_by: "Clubnacht",
        note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist. Hier zählt nicht nur der Refrain, sondern auch das, was zwischen den einzelnen Passagen passiert. Der Track verändert seine Wirkung je nachdem, wann und wie man ihn hört.",
        bestQuote: "„Love Will Tear Us Apart erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Joy Division bleibt besonders die Erinnerung an Clubnacht mit diesem Werk verbunden.“",
    },
    {
        format: "Digital",
        title: "Atmosphere",
        author: "Joy Division",
        year: "1980",
        discovered_by: "Spotify",
        note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist. Ein Stück mit einer klaren emotionalen Temperatur und einer starken klanglichen Identität. Gerade seine Details machen aus einem kurzen Moment etwas, das im Kopf weiterläuft.",
        bestQuote: "„Atmosphere erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Joy Division bleibt besonders die Erinnerung an Spotify mit diesem Werk verbunden.“",
    },
    {
        format: "Digital",
        title: "Bela Lugosi's Dead",
        author: "Bauhaus",
        year: "1979",
        discovered_by: "Empfehlung eines DJs",
        note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist. Der Song verdichtet eine Stimmung in wenigen Minuten und bleibt gerade deshalb so unmittelbar. Melodie, Stimme und Produktion greifen ineinander, ohne ihre Eigenart zu verlieren.",
        bestQuote: "„Bela Lugosi's Dead erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Bauhaus bleibt besonders die Erinnerung an Empfehlung eines DJs mit diesem Werk verbunden.“",
    },
    {
        format: "Digital",
        title: "A Forest",
        author: "The Cure",
        year: "1980",
        discovered_by: "Radio",
        note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist. Hier zählt nicht nur der Refrain, sondern auch das, was zwischen den einzelnen Passagen passiert. Der Track verändert seine Wirkung je nachdem, wann und wie man ihn hört.",
        bestQuote: "„A Forest erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei The Cure bleibt besonders die Erinnerung an Radio mit diesem Werk verbunden.“",
    },
    {
        format: "Digital",
        title: "Pictures of You",
        author: "The Cure",
        year: "1989",
        discovered_by: "Alte Playlist",
        note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist. Ein Stück mit einer klaren emotionalen Temperatur und einer starken klanglichen Identität. Gerade seine Details machen aus einem kurzen Moment etwas, das im Kopf weiterläuft.",
        bestQuote: "„Pictures of You erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei The Cure bleibt besonders die Erinnerung an Alte Playlist mit diesem Werk verbunden.“",
    },
    {
        format: "Digital",
        title: "Roads",
        author: "Portishead",
        year: "1994",
        discovered_by: "Filmabend",
        note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist. Der Song verdichtet eine Stimmung in wenigen Minuten und bleibt gerade deshalb so unmittelbar. Melodie, Stimme und Produktion greifen ineinander, ohne ihre Eigenart zu verlieren.",
        bestQuote: "„Roads erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Portishead bleibt besonders die Erinnerung an Filmabend mit diesem Werk verbunden.“",
    },
    {
        format: "Digital",
        title: "Glory Box",
        author: "Portishead",
        year: "1994",
        discovered_by: "Spotify",
        note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist. Hier zählt nicht nur der Refrain, sondern auch das, was zwischen den einzelnen Passagen passiert. Der Track verändert seine Wirkung je nachdem, wann und wie man ihn hört.",
        bestQuote: "„Glory Box erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Portishead bleibt besonders die Erinnerung an Spotify mit diesem Werk verbunden.“",
    },
    {
        format: "Digital",
        title: "Teardrop",
        author: "Massive Attack",
        year: "1998",
        discovered_by: "Trip-Hop-Playlist",
        note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist. Ein Stück mit einer klaren emotionalen Temperatur und einer starken klanglichen Identität. Gerade seine Details machen aus einem kurzen Moment etwas, das im Kopf weiterläuft.",
        bestQuote: "„Teardrop erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Massive Attack bleibt besonders die Erinnerung an Trip-Hop-Playlist mit diesem Werk verbunden.“",
    },
    {
        format: "Digital",
        title: "Angel",
        author: "Massive Attack",
        year: "1998",
        discovered_by: "Film entdeckt",
        note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist. Der Song verdichtet eine Stimmung in wenigen Minuten und bleibt gerade deshalb so unmittelbar. Melodie, Stimme und Produktion greifen ineinander, ohne ihre Eigenart zu verlieren.",
        bestQuote: "„Angel erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Massive Attack bleibt besonders die Erinnerung an Film entdeckt mit diesem Werk verbunden.“",
    },
    {
        format: "Digital",
        title: "Porcelain",
        author: "Moby",
        year: "1999",
        discovered_by: "Alte Playlist",
        note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist. Hier zählt nicht nur der Refrain, sondern auch das, was zwischen den einzelnen Passagen passiert. Der Track verändert seine Wirkung je nachdem, wann und wie man ihn hört.",
        bestQuote: "„Porcelain erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Moby bleibt besonders die Erinnerung an Alte Playlist mit diesem Werk verbunden.“",
    },
    {
        format: "Digital",
        title: "Windowlicker",
        author: "Aphex Twin",
        year: "1999",
        discovered_by: "Empfehlung eines DJs",
        note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist. Ein Stück mit einer klaren emotionalen Temperatur und einer starken klanglichen Identität. Gerade seine Details machen aus einem kurzen Moment etwas, das im Kopf weiterläuft.",
        bestQuote: "„Windowlicker erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Aphex Twin bleibt besonders die Erinnerung an Empfehlung eines DJs mit diesem Werk verbunden.“",
    },
    {
        format: "Digital",
        title: "Strings of Life",
        author: "Rhythim Is Rhythim",
        year: "1987",
        discovered_by: "Techno-Archiv",
        note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist. Der Song verdichtet eine Stimmung in wenigen Minuten und bleibt gerade deshalb so unmittelbar. Melodie, Stimme und Produktion greifen ineinander, ohne ihre Eigenart zu verlieren.",
        bestQuote: "„Strings of Life erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Rhythim Is Rhythim bleibt besonders die Erinnerung an Techno-Archiv mit diesem Werk verbunden.“",
    },
    {
        format: "Digital",
        title: "L'Ange Naïf",
        author: "Sven Väth",
        year: "1992",
        discovered_by: "Frankfurter Clubnacht",
        note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist. Hier zählt nicht nur der Refrain, sondern auch das, was zwischen den einzelnen Passagen passiert. Der Track verändert seine Wirkung je nachdem, wann und wie man ihn hört.",
        bestQuote: "„L'Ange Naïf erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Sven Väth bleibt besonders die Erinnerung an Frankfurter Clubnacht mit diesem Werk verbunden.“",
    },
    {
        format: "Digital",
        title: "Insomnia",
        author: "Faithless",
        year: "1995",
        discovered_by: "90er-Playlist",
        note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist. Ein Stück mit einer klaren emotionalen Temperatur und einer starken klanglichen Identität. Gerade seine Details machen aus einem kurzen Moment etwas, das im Kopf weiterläuft.",
        bestQuote: "„Insomnia erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei Faithless bleibt besonders die Erinnerung an 90er-Playlist mit diesem Werk verbunden.“",
    },
    {
        format: "Digital",
        title: "Blue Monday",
        author: "New Order",
        year: "1983",
        discovered_by: "Musikvideo",
        note: "Ein Track, der wegen Atmosphäre, Erinnerung oder Sound geblieben ist. Der Song verdichtet eine Stimmung in wenigen Minuten und bleibt gerade deshalb so unmittelbar. Melodie, Stimme und Produktion greifen ineinander, ohne ihre Eigenart zu verlieren.",
        bestQuote: "„Blue Monday erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei New Order bleibt besonders die Erinnerung an Musikvideo mit diesem Werk verbunden.“",
    },
];

const magazines = [
    {
        title: "RAY",
        issue: "N°24",
        date: "Januar 2026",
        discovered_by: "Meine Großmutter",
        note: "Ein Filmmagazin mit einem außergewöhnlich starken visuellen Charakter. Die Ausgabe ist nicht nur wegen ihres Inhalts interessant, sondern auch als Zeitdokument ihrer visuellen Kultur. Layout, Fotografie und Redaktion erzählen gemeinsam von einem bestimmten Blick auf Kunst und Film.",
        bestQuote: "„RAY erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei  bleibt besonders die Erinnerung an Meine Großmutter mit diesem Werk verbunden.“",
        imageUrl: "/images/collections/magazines/1.jpg",
    },
    {
        title: "RAY",
        issue: "N°31",
        date: "November 2021",
        discovered_by: "Flohmarkt in Frankfurt",
        note: "Ein weiteres Stück visueller Filmgeschichte. Besonders spannend ist das Zusammenspiel von Text und Bild. Die Ausgabe bewahrt eine Atmosphäre, die sich deutlich von heutiger schneller Medienproduktion unterscheidet.",
        bestQuote: "„RAY erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei  bleibt besonders die Erinnerung an Flohmarkt in Frankfurt mit diesem Werk verbunden.“",
        imageUrl: "/images/collections/magazines/2.jpg",
    },
    {
        title: "Cahiers du cinéma",
        issue: "N°113",
        date: "November 1960",
        discovered_by: "Filmseminar",
        note: "Film als Kunstform und als Denken. Die Ausgabe ist nicht nur wegen ihres Inhalts interessant, sondern auch als Zeitdokument ihrer visuellen Kultur. Layout, Fotografie und Redaktion erzählen gemeinsam von einem bestimmten Blick auf Kunst und Film.",
        bestQuote: "„Cahiers du cinéma erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei  bleibt besonders die Erinnerung an Filmseminar mit diesem Werk verbunden.“",
        imageUrl: "/images/collections/magazines/3.webp",
    },
    {
        title: "Sight & Sound",
        issue: "N°31",
        date: "September 2021",
        discovered_by: "Filmbuchhandlung in Berlin",
        note: "Ein kleines Stück Filmgeschichte und Filmkritik. Besonders spannend ist das Zusammenspiel von Text und Bild. Die Ausgabe bewahrt eine Atmosphäre, die sich deutlich von heutiger schneller Medienproduktion unterscheidet.",
        bestQuote: "„Sight & Sound erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei  bleibt besonders die Erinnerung an Filmbuchhandlung in Berlin mit diesem Werk verbunden.“",
        imageUrl: "/images/collections/magazines/1.jpg",
    },
    {
        title: "Aperture",
        issue: "N°256",
        date: "2024",
        discovered_by: "Fotografie-Ausstellung",
        note: "Fotografie, Kunst und visuelle Kultur. Die Ausgabe ist nicht nur wegen ihres Inhalts interessant, sondern auch als Zeitdokument ihrer visuellen Kultur. Layout, Fotografie und Redaktion erzählen gemeinsam von einem bestimmten Blick auf Kunst und Film.",
        bestQuote: "„Aperture erinnert daran, dass man manchmal länger bei einem Eindruck bleiben muss.“ „Bei  bleibt besonders die Erinnerung an Fotografie-Ausstellung mit diesem Werk verbunden.“",
        imageUrl: "/images/collections/magazines/5.png",
    },
];

const artworks = [
    {
        format: "Physisch",
        title: "The Old Guitarist",
        author: "Pablo Picasso",
        year: "1903",
        technique: "Öl auf Holz",
        dimensions: "122,9 × 82,6 cm",
        discovered_by: "Museum Ludwig",
        note: "Das Werk verbindet formale Entscheidungen mit einer starken emotionalen Wirkung und erschließt sich bei längerem Betrachten immer wieder neu. Komposition, Material und Motiv erzeugen eine Spannung, die weit über den ersten Eindruck hinausgeht.",
        imageUrl: "/images/collections/artworks/1.webp",
    },
    {
        format: "Physisch",
        title: "La Vie",
        author: "Pablo Picasso",
        year: "1903",
        technique: "Öl auf Leinwand",
        dimensions: "196,5 × 128,5 cm",
        discovered_by: "Picasso-Ausstellung",
        note: "Mich interessiert besonders, wie Bildsprache und historische Situation ineinandergreifen. Je länger man schaut, desto mehr verschieben sich die Beziehungen zwischen Figur, Raum, Farbe und Bedeutung.",
        imageUrl: "/images/collections/artworks/2.jpg",
    },
    {
        format: "Physisch",
        title: "The Blue Room",
        author: "Pablo Picasso",
        year: "1901",
        technique: "Öl auf Leinwand",
        dimensions: "50,5 × 62,5 cm",
        discovered_by: "Kunstbuch über Picasso",
        note: "Das Werk verbindet formale Entscheidungen mit einer starken emotionalen Wirkung und erschließt sich bei längerem Betrachten immer wieder neu. Komposition, Material und Motiv erzeugen eine Spannung, die weit über den ersten Eindruck hinausgeht.",
        imageUrl: "/images/collections/artworks/3.jpg",
    },
    {
        format: "Physisch",
        title: "Guernica",
        author: "Pablo Picasso",
        year: "1937",
        technique: "Öl auf Leinwand",
        dimensions: "349,3 × 776,6 cm",
        discovered_by: "Kunstgeschichte-Seminar",
        note: "Mich interessiert besonders, wie Bildsprache und historische Situation ineinandergreifen. Je länger man schaut, desto mehr verschieben sich die Beziehungen zwischen Figur, Raum, Farbe und Bedeutung.",
        imageUrl: "/images/collections/artworks/4.jpg",
    },
    {
        format: "Physisch",
        title: "The Kiss",
        author: "Gustav Klimt",
        year: "1908",
        technique: "Öl und Blattgold auf Leinwand",
        dimensions: "180 × 180 cm",
        discovered_by: "Belvedere in Wien",
        note: "Das Werk verbindet formale Entscheidungen mit einer starken emotionalen Wirkung und erschließt sich bei längerem Betrachten immer wieder neu. Komposition, Material und Motiv erzeugen eine Spannung, die weit über den ersten Eindruck hinausgeht.",
        imageUrl: "/images/collections/artworks/5.webp",
    },
    {
        format: "Physisch",
        title: "Death and Life",
        author: "Gustav Klimt",
        year: "1915",
        technique: "Öl auf Leinwand",
        dimensions: "178 × 198 cm",
        discovered_by: "Klimt-Ausstellung",
        note: "Mich interessiert besonders, wie Bildsprache und historische Situation ineinandergreifen. Je länger man schaut, desto mehr verschieben sich die Beziehungen zwischen Figur, Raum, Farbe und Bedeutung.",
        imageUrl: "/images/collections/artworks/6.jpg",
    },
    {
        format: "Physisch",
        title: "Self-Portrait with Physalis",
        author: "Egon Schiele",
        year: "1912",
        technique: "Öl auf Leinwand",
        dimensions: "42,2 × 32,4 cm",
        discovered_by: "Leopold Museum",
        note: "Das Werk verbindet formale Entscheidungen mit einer starken emotionalen Wirkung und erschließt sich bei längerem Betrachten immer wieder neu. Komposition, Material und Motiv erzeugen eine Spannung, die weit über den ersten Eindruck hinausgeht.",
        imageUrl: "/images/collections/artworks/7.jpeg",
    },
    {
        format: "Physisch",
        title: "The Garden of Earthly Delights",
        author: "Hieronymus Bosch",
        year: "1500",
        technique: "Öl auf Holz",
        dimensions: "205,5 × 384,9 cm",
        discovered_by: "Kunsthistorisches Museum",
        note: "Mich interessiert besonders, wie Bildsprache und historische Situation ineinandergreifen. Je länger man schaut, desto mehr verschieben sich die Beziehungen zwischen Figur, Raum, Farbe und Bedeutung.",
        imageUrl: "/images/collections/artworks/8.webp",
    },
    {
        format: "Physisch",
        title: "The Dance",
        author: "Henri Matisse",
        year: "1910",
        technique: "Öl auf Leinwand",
        dimensions: "260 × 391 cm",
        discovered_by: "Matisse-Katalog",
        note: "Das Werk verbindet formale Entscheidungen mit einer starken emotionalen Wirkung und erschließt sich bei längerem Betrachten immer wieder neu. Komposition, Material und Motiv erzeugen eine Spannung, die weit über den ersten Eindruck hinausgeht.",
        imageUrl: "/images/collections/artworks/9.jpg",
    },
    {
        format: "Physisch",
        title: "Blue Nude II",
        author: "Henri Matisse",
        year: "1952",
        technique: "Gouache auf Papier, Cut-out",
        dimensions: "116,2 × 88,9 cm",
        discovered_by: "Ausstellung über Matisse",
        note: "Mich interessiert besonders, wie Bildsprache und historische Situation ineinandergreifen. Je länger man schaut, desto mehr verschieben sich die Beziehungen zwischen Figur, Raum, Farbe und Bedeutung.",
        imageUrl: "/images/collections/artworks/10.webp",
    },
    {
        format: "Physisch",
        title: "Nighthawks",
        author: "Edward Hopper",
        year: "1942",
        technique: "Öl auf Leinwand",
        dimensions: "84,1 × 152,4 cm",
        discovered_by: "Filmstill und Kunstbuch",
        note: "Das Werk verbindet formale Entscheidungen mit einer starken emotionalen Wirkung und erschließt sich bei längerem Betrachten immer wieder neu. Komposition, Material und Motiv erzeugen eine Spannung, die weit über den ersten Eindruck hinausgeht.",
        imageUrl: "/images/collections/artworks/11.webp",
    },
    {
        format: "Physisch",
        title: "The Son of Man",
        author: "René Magritte",
        year: "1964",
        technique: "Öl auf Leinwand",
        dimensions: "116 × 89 cm",
        discovered_by: "Surrealismus-Ausstellung",
        note: "Mich interessiert besonders, wie Bildsprache und historische Situation ineinandergreifen. Je länger man schaut, desto mehr verschieben sich die Beziehungen zwischen Figur, Raum, Farbe und Bedeutung.",
        imageUrl: "/images/collections/artworks/12.jpg",
    },
    {
        format: "Physisch",
        title: "Composition VIII",
        author: "Wassily Kandinsky",
        year: "1923",
        technique: "Öl auf Leinwand",
        dimensions: "140 × 201 cm",
        discovered_by: "Kunstgeschichte-Buch",
        note: "Das Werk verbindet formale Entscheidungen mit einer starken emotionalen Wirkung und erschließt sich bei längerem Betrachten immer wieder neu. Komposition, Material und Motiv erzeugen eine Spannung, die weit über den ersten Eindruck hinausgeht.",
        imageUrl: "/images/collections/artworks/13.webp",
    },
];

const museums = [
    {
        title: "DFF – Deutsches Filminstitut & Filmmuseum",
        city: "Frankfurt am Main",
        exhibition: "Film, Kino und visuelle Kultur",
        date: new Date("2025-05-10"),
        discovered_by: "Frankfurt",
        note: "Der Besuch war mehr als ein Rundgang durch einzelne Werke, weil die Räume und die Auswahl der Sammlung selbst eine Erzählung bilden. Besonders hängen geblieben ist die Verbindung zwischen historischen Kontexten und der unmittelbaren Erfahrung vor dem Original.",
    },
    {
        title: "Städel Museum",
        city: "Frankfurt am Main",
        exhibition: "Sammlung Moderne Kunst",
        date: new Date("2025-04-20"),
        discovered_by: "Frankfurt",
        note: "Dieses Museum eignet sich für langsames Sehen statt für einen schnellen Überblick. Die Atmosphäre der Räume und die Art, wie unterschiedliche Positionen miteinander in Beziehung gesetzt werden, machen den Besuch zu einer eigenen Erinnerung.",
    },
    {
        title: "Museum Ludwig",
        city: "Köln",
        exhibition: "Picasso",
        date: new Date("2025-06-12"),
        discovered_by: "Reise nach Köln",
        note: "Der Besuch war mehr als ein Rundgang durch einzelne Werke, weil die Räume und die Auswahl der Sammlung selbst eine Erzählung bilden. Besonders hängen geblieben ist die Verbindung zwischen historischen Kontexten und der unmittelbaren Erfahrung vor dem Original.",
    },
    {
        title: "Hamburger Bahnhof",
        city: "Berlin",
        exhibition: "Zeitgenössische Kunst",
        date: new Date("2025-06-03"),
        discovered_by: "Wochenende in Berlin",
        note: "Dieses Museum eignet sich für langsames Sehen statt für einen schnellen Überblick. Die Atmosphäre der Räume und die Art, wie unterschiedliche Positionen miteinander in Beziehung gesetzt werden, machen den Besuch zu einer eigenen Erinnerung.",
    },
    {
        title: "Alte Nationalgalerie",
        city: "Berlin",
        exhibition: "19. Jahrhundert",
        date: new Date("2025-05-14"),
        discovered_by: "Museumsinsel",
        note: "Der Besuch war mehr als ein Rundgang durch einzelne Werke, weil die Räume und die Auswahl der Sammlung selbst eine Erzählung bilden. Besonders hängen geblieben ist die Verbindung zwischen historischen Kontexten und der unmittelbaren Erfahrung vor dem Original.",
    },
    {
        title: "Neue Nationalgalerie",
        city: "Berlin",
        exhibition: "Moderne Kunst",
        date: new Date("2025-05-16"),
        discovered_by: "Wochenende in Berlin",
        note: "Dieses Museum eignet sich für langsames Sehen statt für einen schnellen Überblick. Die Atmosphäre der Räume und die Art, wie unterschiedliche Positionen miteinander in Beziehung gesetzt werden, machen den Besuch zu einer eigenen Erinnerung.",
    },
    {
        title: "Museum Brandhorst",
        city: "München",
        exhibition: "Andy Warhol",
        date: new Date("2025-03-21"),
        discovered_by: "Reise nach München",
        note: "Der Besuch war mehr als ein Rundgang durch einzelne Werke, weil die Räume und die Auswahl der Sammlung selbst eine Erzählung bilden. Besonders hängen geblieben ist die Verbindung zwischen historischen Kontexten und der unmittelbaren Erfahrung vor dem Original.",
    },
    {
        title: "Pinakothek der Moderne",
        city: "München",
        exhibition: "Moderne Kunst",
        date: new Date("2025-03-22"),
        discovered_by: "Reise nach München",
        note: "Dieses Museum eignet sich für langsames Sehen statt für einen schnellen Überblick. Die Atmosphäre der Räume und die Art, wie unterschiedliche Positionen miteinander in Beziehung gesetzt werden, machen den Besuch zu einer eigenen Erinnerung.",
    },
    {
        title: "Kunstmuseum Basel",
        city: "Basel",
        exhibition: "Sammlung Moderne Kunst",
        date: new Date("2025-02-15"),
        discovered_by: "Wochenendreise nach Basel",
        note: "Der Besuch war mehr als ein Rundgang durch einzelne Werke, weil die Räume und die Auswahl der Sammlung selbst eine Erzählung bilden. Besonders hängen geblieben ist die Verbindung zwischen historischen Kontexten und der unmittelbaren Erfahrung vor dem Original.",
    },
    {
        title: "Centre Pompidou",
        city: "Paris",
        exhibition: "Moderne und zeitgenössische Kunst",
        date: new Date("2024-10-11"),
        discovered_by: "Reise nach Paris",
        note: "Dieses Museum eignet sich für langsames Sehen statt für einen schnellen Überblick. Die Atmosphäre der Räume und die Art, wie unterschiedliche Positionen miteinander in Beziehung gesetzt werden, machen den Besuch zu einer eigenen Erinnerung.",
    },
    {
        title: "Musée d'Orsay",
        city: "Paris",
        exhibition: "Impressionismus",
        date: new Date("2024-10-13"),
        discovered_by: "Reise nach Paris",
        note: "Der Besuch war mehr als ein Rundgang durch einzelne Werke, weil die Räume und die Auswahl der Sammlung selbst eine Erzählung bilden. Besonders hängen geblieben ist die Verbindung zwischen historischen Kontexten und der unmittelbaren Erfahrung vor dem Original.",
    },
    {
        title: "Kunsthistorisches Museum",
        city: "Wien",
        exhibition: "Alte Meister",
        date: new Date("2024-09-12"),
        discovered_by: "Reise nach Wien",
        note: "Dieses Museum eignet sich für langsames Sehen statt für einen schnellen Überblick. Die Atmosphäre der Räume und die Art, wie unterschiedliche Positionen miteinander in Beziehung gesetzt werden, machen den Besuch zu einer eigenen Erinnerung.",
    },
    {
        title: "Museum für Moderne Kunst (MMK)",
        city: "Frankfurt am Main",
        exhibition: "Moderne und Gegenwart",
        date: new Date("2025-07-02"),
        discovered_by: "Museumsufer",
        note: "Das MMK interessiert mich wegen der Art, wie Architektur und Sammlung miteinander arbeiten. Zwischen Malerei, Installation und Medienkunst entstehen hier immer wieder unerwartete Blickwechsel, die einen einzelnen Besuch sehr konzentriert machen.",
    },
    {
        title: "SCHIRN Kunsthalle Frankfurt",
        city: "Frankfurt am Main",
        exhibition: "Kunst der Moderne und Gegenwart",
        date: new Date("2025-07-03"),
        discovered_by: "Altstadt Frankfurt",
        note: "Die wechselnden Ausstellungen machen die Schirn zu einem Ort, an den man mit unterschiedlichen Erwartungen zurückkehrt. Besonders spannend ist für mich die Verbindung zwischen großen kunsthistorischen Themen und einer klaren, zeitgenössischen Vermittlung.",
    },
    {
        title: "Kunsthalle Mannheim",
        city: "Mannheim",
        exhibition: "Sammlung und Gegenwartskunst",
        date: new Date("2025-07-19"),
        discovered_by: "Wochenendausflug",
        note: "Der Bau selbst verändert die Wahrnehmung der Kunst, weil sich intime Räume und offene Bereiche abwechseln. Die Sammlung erlaubt es, klassische Moderne und jüngere Positionen nicht getrennt, sondern als fortlaufendes Gespräch zu betrachten.",
    },
    {
        title: "Museum Folkwang",
        city: "Essen",
        exhibition: "Malerei, Fotografie und Design",
        date: new Date("2025-07-26"),
        discovered_by: "Reise ins Ruhrgebiet",
        note: "Mich beeindruckt die Breite der Sammlung, in der Fotografie, Malerei und Design selbstverständlich nebeneinanderstehen. Dadurch entsteht ein Blick auf Kunstgeschichte, der weniger wie eine starre Chronologie und mehr wie ein Netzwerk wirkt.",
    },
    {
        title: "K20 Kunstsammlung Nordrhein-Westfalen",
        city: "Düsseldorf",
        exhibition: "Klassische Moderne",
        date: new Date("2025-08-09"),
        discovered_by: "Kunstwochenende",
        note: "Ein Museum, das zentrale Werke der Moderne mit großer Ruhe präsentiert und Vergleiche zwischen Künstlern möglich macht. Besonders wertvoll ist die Gelegenheit, bekannte Bilder im Original und damit in ihrer tatsächlichen Größe, Materialität und Farbwirkung zu erleben.",
    },
];

const galleries = [
    {
        title: "Galerie Max Hetzler",
        city: "Berlin",
        artist: "Albert Oehlen",
        exhibition: "Neue Arbeiten",
        date: new Date("2025-06-04"),
        note: "Interessant war vor allem, die Arbeiten im direkten räumlichen Zusammenhang zu sehen, statt sie nur reproduziert zu kennen. Die Ausstellung machte sichtbar, wie stark Maßstab, Material und Hängung die Wahrnehmung verändern.",
    },
    {
        title: "Esther Schipper",
        city: "Berlin",
        artist: "Various Artists",
        exhibition: "Contemporary Art",
        date: new Date("2025-06-05"),
        note: "Die Galerie schafft einen konzentrierten Rahmen für zeitgenössische Positionen und lässt den Werken genügend Eigenraum. Besonders spannend ist der Kontrast zwischen konzeptueller Idee und der sehr unmittelbaren physischen Präsenz der Arbeiten.",
    },
    {
        title: "Sprüth Magers",
        city: "Berlin",
        artist: "Andreas Gursky",
        exhibition: "Photography",
        date: new Date("2025-06-06"),
        note: "Interessant war vor allem, die Arbeiten im direkten räumlichen Zusammenhang zu sehen, statt sie nur reproduziert zu kennen. Die Ausstellung machte sichtbar, wie stark Maßstab, Material und Hängung die Wahrnehmung verändern.",
    },
    {
        title: "David Zwirner",
        city: "Berlin",
        artist: "Wolfgang Tillmans",
        exhibition: "Works",
        date: new Date("2025-06-07"),
        note: "Die Galerie schafft einen konzentrierten Rahmen für zeitgenössische Positionen und lässt den Werken genügend Eigenraum. Besonders spannend ist der Kontrast zwischen konzeptueller Idee und der sehr unmittelbaren physischen Präsenz der Arbeiten.",
    },
    {
        title: "König Galerie",
        city: "Berlin",
        artist: "Various Artists",
        exhibition: "Contemporary Works",
        date: new Date("2025-06-08"),
        note: "Interessant war vor allem, die Arbeiten im direkten räumlichen Zusammenhang zu sehen, statt sie nur reproduziert zu kennen. Die Ausstellung machte sichtbar, wie stark Maßstab, Material und Hängung die Wahrnehmung verändern.",
    },
    {
        title: "Galerie Neu",
        city: "Berlin",
        artist: "Various Artists",
        exhibition: "New Works",
        date: new Date("2025-06-09"),
        note: "Die Galerie schafft einen konzentrierten Rahmen für zeitgenössische Positionen und lässt den Werken genügend Eigenraum. Besonders spannend ist der Kontrast zwischen konzeptueller Idee und der sehr unmittelbaren physischen Präsenz der Arbeiten.",
    },
    {
        title: "Peres Projects",
        city: "Berlin",
        artist: "Various Artists",
        exhibition: "Group Exhibition",
        date: new Date("2025-06-10"),
        note: "Interessant war vor allem, die Arbeiten im direkten räumlichen Zusammenhang zu sehen, statt sie nur reproduziert zu kennen. Die Ausstellung machte sichtbar, wie stark Maßstab, Material und Hängung die Wahrnehmung verändern.",
    },
    {
        title: "Capitain Petzel",
        city: "Berlin",
        artist: "Various Artists",
        exhibition: "Contemporary Positions",
        date: new Date("2025-06-11"),
        note: "Die Ausstellung verbindet unterschiedliche künstlerische Sprachen ohne sie auf einen gemeinsamen Stil zu reduzieren. Gerade die Spannung zwischen Material, Konzept und persönlicher Handschrift macht den Besuch interessant.",
    },
    {
        title: "neugerriemschneider",
        city: "Berlin",
        artist: "Various Artists",
        exhibition: "Current Works",
        date: new Date("2025-06-12"),
        note: "Ein Ort, an dem einzelne Positionen genug Raum bekommen, um sich langsam zu entfalten. Mich interessiert besonders, wie Präsentation und Kontext die Wahrnehmung eines Werkes verändern.",
    },
    {
        title: "KOW",
        city: "Berlin",
        artist: "Various Artists",
        exhibition: "Contemporary Narratives",
        date: new Date("2025-06-13"),
        note: "Die Arbeiten wirken politisch und persönlich zugleich, ohne ihre Ambivalenz zu verlieren. Die Galerie ist interessant, weil sie Fragen nach Gesellschaft, Bildkultur und Gegenwart konsequent miteinander verbindet.",
    },
    {
        title: "Galerie Buchholz",
        city: "Berlin",
        artist: "Various Artists",
        exhibition: "Modern and Contemporary Art",
        date: new Date("2025-06-14"),
        note: "Historische und zeitgenössische Positionen treten hier in einen produktiven Dialog. Dadurch entstehen Vergleiche, die einzelne Werke aus ihrem vertrauten kunsthistorischen Rahmen lösen.",
    },
];

const images = [
    {
        title: "Der Mann mit der Kamera (Kino-Auge)",
        creator: "Dziga Vertov",
        year: 1929,
        source: "Sowjetisches Stummfilm-Archiv",
        discovered_by: "Buch",
        note: "Diese berühmte Doppelbelichtung verschmilzt das menschliche Auge direkt mit der Linse einer Kamera. Sie verkörpert das revolutionäre avantgardistische Konzept des Kino-Auges (Kinoglaz) von Dziga Vertov. Das Bild gilt bis heute als ein zeitloses Meisterwerk der frühen sowjetischen Montage.",
        imageUrl: "/images/collections/images/1.jpg"
    },
    {
        title: "Leap of Faith (Jeanloup Sieff in New York)",
        creator: "Louis Faurer",
        year: 1960,
        source: "Straßenfotografie-Archiv, New York",
        discovered_by: "Ausstellung",
        note: "In diesem dynamischen Schnappschuss fängt Louis Faurer einen faszinierenden Moment der Straßenfotografie in New York ein. Er zeigt den berühmten Fotografen Jeanloup Sieff bei einem enthusiastischen Sprung in voller Bewegung, um den perfekten Winkel für sein gehendes Model zu finden. Diese Aufnahme ist ein wunderbares visuelles Zeugnis gegenseitiger künstlerischer Inspiration.",
        imageUrl: "/images/collections/images/2.jpg"
    },
    {
        title: "Living in Oblivion (Filmstill mit Filmklappe)",
        creator: "Tom DiCillo",
        year: 1995,
        source: "Indie-Film-Archiv",
        discovered_by: "Zufall",
        note: "Dieses markante Standbild zeigt eine Filmklappe direkt vor den Augen der ausdrucksstarken Schauspielerin Catherine Keener. Es stammt aus Tom DiCillos legendärer Indie-Komödie, die die skurrilen und chaotischen Abenteuer einer Low-Budget-Filmproduktion porträtiert. Ein wunderbares Motiv, das die Meta-Ebene des Kinos feiert.",
        imageUrl: "/images/collections/images/3.jpg"
    },
    {
        title: "Porträt von Jean Cocteau",
        creator: "Germaine Krull",
        year: 1929,
        source: "Avantgarde-Fotografie, Paris",
        discovered_by: "Buch",
        note: "Dieses faszinierende Doppelbelichtungsporträt zeigt den berühmten französischen Schriftsteller und Universalkünstler Jean Cocteau. Er erscheint wie in Trance, umgeben von einer Vielzahl surrealer, geisterhafter Hände im Raum. Germaine Krulls meisterhafte Fotomontage fängt die mystische und kreative Aura des Künstlers perfekt ein.",
        imageUrl: "/images/collections/images/4.jpg"
    },
    {
        title: "The Blindfold of God (Surrealistisches Porträt)",
        creator: "Kevin Carden",
        year: 2013,
        source: "Digital Art Portfolio",
        discovered_by: "Internet",
        note: "Diese eindringliche visuelle Komposition zeigt einen Mann im eleganten Anzug, dessen Augen von einer Binde mit der Aufschrift 'GOD' verdeckt sind. Seine tastenden Hände symbolisieren die verzweifelte Suche nach Orientierung und Wahrheit in einer modernen Welt. Das Werk stellt eine tiefgründige visuelle Metapher für spirituelle Blindheit, Glauben und die Grenzen der menschlichen Wahrnehmung dar.",
        imageUrl: "/images/collections/images/5.jpg"
    },
    {
        title: "Carel Schuh-Werbung (Hotel des Trois Couronnes, Vevey)",
        creator: "Jeanloup Sieff",
        year: 1985,
        source: "Carel Werbekampagne, Schweiz",
        discovered_by: "Ausstellung",
        note: "Dieses ikonische Schwarz-Weiß-Foto entstand im Rahmen einer langjährigen und fruchtbaren Zusammenarbeit zwischen dem Fotografen und der Luxusmarke Carel. Es zeigt die eleganten Beine einer Ballerina en pointe vor der malerischen Kulisse des Genfersees in Vevey, Schweiz. Jeanloup Sieff verbindet in dieser minimalistischen Modeaufnahme meisterhaft Sinnlichkeit, Eleganz und eine Prise Humor.",
        imageUrl: "/images/collections/images/6.jpg"
    },
    {
        title: "Der Mann mit der Kamera (Miniatur-Kameramann)",
        creator: "Dziga Vertov",
        year: 1929,
        source: "Sowjetisches Stummfilm-Archiv",
        discovered_by: "Zufall",
        note: "Diese bahnbrechende Trickaufnahme zeigt den Kameramann Michail Kaufman, wie er scheinbar auf einer gigantischen Filmkamera balanciert. Durch die geschickte Montage wird die Kamera selbst zu einem monumentalen, fast architektonischen Objekt erhoben. Die Szene feiert die absolute visuelle Überlegenheit des modernen Stummfilm-Kinos.",
        imageUrl: "/images/collections/images/8.jpg"
    },
    {
        title: "La Notte (Spanisches Kinoplakat)",
        creator: "Michelangelo Antonioni",
        year: 1961,
        source: "Filmplakat-Archiv",
        discovered_by: "Internet",
        note: "Dieses ausdrucksstarke spanische Originalplakat wirbt für Michelangelo Antonionis filmisches Meisterwerk 'La Notte' aus dem Jahr 1961. Die Grafik fängt die tiefe existenzielle Entfremdung und die melancholische Distanz zwischen den Hauptdarstellern Marcello Mastroianni und Jeanne Moreau perfekt ein. Ein großartiges Dokument europäischer Filmgeschichte.",
        imageUrl: "/images/collections/images/9.jpg"
    },
    {
        title: "La Chinoise (Kinoplakat)",
        creator: "Jean-Luc Godard",
        year: 1967,
        source: "Französisches New-Wave-Archiv",
        discovered_by: "Buch",
        note: "Das leuchtend rote, minimalistische Kinoplakat zu Jean-Luc Godards 'La Chinoise' ist ein echtes visuelles Statement des Jahres 1967. Es bricht radikal mit klassischen Designkonventionen, indem es kleine, prägnante Filmausschnitte unter einer dominanten Farbfläche platziert. Diese Gestaltung spiegelt die politische und ästhetische Aufbruchstimmung der Nouvelle Vague perfekt wider.",
        imageUrl: "/images/collections/images/10.jpg"
    },
    {
        title: "Stalker (Alternatives Plakat-Design)",
        creator: "Andrej Tarkowski",
        year: 1979,
        source: "Kino-Kunstsammlung",
        discovered_by: "Internet",
        note: "Dieses kunstvolle, moderne Plakat fängt die mystische und schwermütige Atmosphäre von Andrej Tarkowskis Science-Fiction-Meisterwerk 'Stalker' ein. Vor einem geheimnisvollen, nebligen Portal steht die einsame Silhouette des Stalkers, begleitet von dem treuen Hund in der verbotenen Zone. Das minimalistische Farbkonzept unterstreicht die tiefe visuelle Poesie dieser unvergesslichen filmischen Reise.",
        imageUrl: "/images/collections/images/12.jpg"
    },
    {
        title: "Profil von Jean-Luc Godard",
        creator: "Jean-Luc Godard (Kollage / unbekannter Fotograf)",
        year: 1965,
        source: "Nouvelle Vague Dokumentation",
        discovered_by: "Buch",
        note: "Diese ikonische Schwarz-Weiß-Kollage zeigt das markante Profil des jungen Regisseurs Jean-Luc Godard mit einer brennenden Zigarette im Mund. Um seinen Kopf legt sich kreisförmig das berühmte, provokante Zitat über die Rolle der Kunst im politischen Diskurs. Es ist ein kraftvolles Porträt eines Künstlers, der das Kino für immer verändert hat.",
        imageUrl: "/images/collections/images/13.jpg"
    },
    {
        title: "Der Mann mit der Kamera (Augen-Kollage)",
        creator: "Dziga Vertov",
        year: 1929,
        source: "Sowjetisches Stummfilm-Archiv",
        discovered_by: "Zufall",
        note: "Diese hypnotische Montage aus zahlreichen menschlichen Augen ist ein zentrales visuelles Element aus Dziga Vertovs bahnbrechendem Stummfilm. Sie symbolisiert die unbegrenzte, allsehende Macht des technischen Kamera-Auges im modernen urbanen Raum. Die rhythmische Anordnung der Blicke fesselt den Betrachter bis heute und zeigt die frühe Innovationskraft sowjetischer Schnitttechniken.",
        imageUrl: "/images/collections/images/15.jpg"
    },
    {
        title: "Hour of the Wolf (Vargtimmen - Kinoplakat)",
        creator: "Ingmar Bergman",
        year: 1968,
        source: "Schwedisches Filmarchiv",
        discovered_by: "Ausstellung",
        note: "Das kontrastreiche, rosafarbene Plakat zu Ingmar Bergmans 'Vargtimmen' (Die Stunde des Wolfs) erzeugt eine zutiefst beunruhigende Stimmung. Zwei gigantische Hände scheinen eine schutzlose, winzige Gestalt in einem Sarg zu halten, während das düstere Gesicht von Max von Sydow im Hintergrund wacht. Es fängt die Essenz dieses psychologischen Horror-Klassikers über Albträume und existenzielle Ängste perfekt ein.",
        imageUrl: "/images/collections/images/16.jpg"
    },
    {
        title: "Life isn't a Godard film (Filmstill aus 'Eine Frau ist eine Frau')",
        creator: "Jean-Luc Godard",
        year: 1961,
        source: "Kollage / Nouvelle Vague Archiv",
        discovered_by: "Internet",
        note: "Dieses charmante Filmstill stammt aus Godards farbenfroher Komödie 'Eine Frau ist eine Frau' mit Anna Karina und Jean-Paul Belmondo. Der freche, nachträglich überlagerte Slogan 'Life isn't a Godard film' bricht humorvoll die vierte Wand und spielt mit den Erwartungen des Publikums. Das Bild ist eine wunderbare Hommage an die Leichtigkeit und den visuellen Witz der Nouvelle Vague.",
        imageUrl: "/images/collections/images/20.jpg"
    },
    {
        title: "Cinéma Différent (Magazin-Cover Nr. 9-10)",
        creator: "Collectif Jeune Cinéma",
        year: 1978,
        source: "Französisches Avantgarde-Filmjournal",
        discovered_by: "Ausstellung",
        note: "Dieses seltene Cover der französischen Avantgarde-Zeitschrift 'Cinéma Différent' (Ausgabe 9-10) besticht durch seine radikale Schwarz-Weiß-Ästhetik. Es zeigt eine surreal verfremdete Person mit Sonnenbrille und einer weißen, organischen Struktur im Gesicht, ergänzt durch vertikale Filmstreifen-Motive am Rand. Die Gestaltung reflektiert den kompromisslosen Geist des damaligen experimentellen Filmemachens in Europa.",
        imageUrl: "/images/collections/images/21.jpg"
    },
    {
        title: "La Notte (Filmstill mit Marcello Mastroianni)",
        creator: "Michelangelo Antonioni",
        year: 1961,
        source: "Italienisches Filmarchiv",
        discovered_by: "Zufall",
        note: "Dieses meisterhaft komponierte Schwarz-Weiß-Still aus Michelangelo Antonionis 'La Notte' fängt die lähmende Erschöpfung des modernen Lebens ein. Es zeigt den Hauptdarsteller Marcello Mastroianni kraftlos auf dem Teppich liegend, während im rechten Vordergrund die eleganten Beine von Monica Vitti die Szene einrahmen. Die Bildaufteilung verdeutlicht die emotionale Distanz und die unüberbrückbare Kluft zwischen den Charakteren.",
        imageUrl: "/images/collections/images/24.jpg"
    },
    {
        title: "À bout de souffle (Außer Atem - Kinoplakat)",
        creator: "Jean-Luc Godard",
        year: 1960,
        source: "Französisches New-Wave-Archiv",
        discovered_by: "Buch",
        note: "Das legendäre Originalplakat zu 'À bout de souffle' (Außer Atem) markiert den glanzvollen Beginn der Nouvelle Vague im Jahr 1960. Das kontrastreiche Schwarz-Weiß-Motiv zeigt die innige, fast greifbare Intimität zwischen Jean Seberg mit ihrem ikonischen Kurzhaarschnitt und dem rebellischen Jean-Paul Belmondo. Dieses ikonische Design ist ein zeitloses Meisterwerk der modernen Plakatkunst.",
        imageUrl: "/images/collections/images/25.jpg"
    },
    {
        title: "Vivre sa vie (Die Geschichte der Nana - Kinoplakat)",
        creator: "Jean-Luc Godard",
        year: 1962,
        source: "Französisches New-Wave-Archiv",
        discovered_by: "Zufall",
        note: "Dieses minimalistische und zutiefst melancholische Filmplakat wirbt für Godards Meisterwerk 'Vivre sa vie' (Die Geschichte der Nana). Es konzentriert sich ganz auf die feinen, verletzlichen Profilzüge der unvergleichlichen Anna Karina, die hier den Inbegriff französischer Kinopoesie verkörpert. Der clevere Einsatz von dicken, serifenlosen Lettern untersteicht den modernen, fast dokumentarischen Charakter des Films.",
        imageUrl: "/images/collections/images/26.jpg"
    },
    {
        title: "Woman in the Dunes (Suna no onna - Filmstill)",
        creator: "Hiroshi Teshigahara",
        year: 1964,
        source: "Japanisches Filmarchiv",
        discovered_by: "Buch",
        note: "Dieses beklemmende Standbild stammt aus Hiroshi Teshigaharas surrealem Meisterwerk 'Woman in the Dunes' (Suna no onna). Mehrere menschliche Gesichter scheinen stumm und regungslos im feinen, allgegenwärtigen Wüstensand zu versinken. Das Bild dient als kraftvolle visuelle Metapher für den existenziellen Sisyphus-Kampf und die unausweichliche Monotonie des menschlichen Daseins.",
        imageUrl: "/images/collections/images/27.jpg"
    },
    {
        title: "Letztes Jahr in Marienbad (Filmstill)",
        creator: "Alain Resnais",
        year: 1961,
        source: "Französisches Filmarchiv",
        discovered_by: "Ausstellung",
        note: "Dieses traumhafte Standbild aus Alain Resnais' hypnotischem Meisterwerk 'Letztes Jahr in Marienbad' entführt den Betrachter in eine world of illusions. Es zeigt die elegante Delphine Seyrig in einem prachtvoll verzierten Barocksaal, umgeben von stummen, wie Statuen wirkenden Männern im Smoking. Die Komposition spiegelt das verworrene Labyrinth aus Erinnerung, Zeit und Vergessenheit wider, das den gesamten Film prägt.",
        imageUrl: "/images/collections/images/28.jpg"
    },
    {
        title: "Stalker (Filmstill mit Fliege)",
        creator: "Andrej Tarkowski",
        year: 1979,
        source: "Sowjetisches Filmarchiv",
        discovered_by: "Zufall",
        note: "Diese weltberühmte, extrem verlangsamte Nahaufnahme zeigt eine menschliche Hand, auf der eine winzige Fliege krabbelt. Es ist eines der am intensivsten diskutierten Motive aus Andrej Tarkowskis Meisterwerk 'Stalker'. Das Bild dient als ergreifendes Symbol für die absolute Vergänglichkeit, die tiefe Melancholie und die visuelle Poesie des Kinos.",
        imageUrl: "/images/collections/images/29.jpg"
    },
    {
        title: "Shanghai Express (Filmstill mit Marlene Dietrich)",
        creator: "Josef von Sternberg",
        year: 1932,
        source: "Klassisches Hollywood-Archiv",
        discovered_by: "Ausstellung",
        note: "Diese legendäre Chiaroscuro-Aufnahme zeigt die unsterbliche Marlene Dietrich in Josef von Sternbergs Meisterwerk 'Shanghai Express'. Mit vollendeter Grandezza beugt sie sich im tiefen Schatten nach vorne, um ihre Zigarette an einer flackernden Kerzenflamme zu entzünden. Josef von Sternbergs meisterhafte Licht- und Schattengestaltung formt hier eines der glamourösesten Porträts der Hollywood-Geschichte.",
        imageUrl: "/images/collections/images/30.jpg"
    },
    {
        title: "Eyes Wide Shut (Venezianische Maske)",
        creator: "Stanley Kubrick",
        year: 1999,
        source: "Warner Bros. Archiv",
        discovered_by: "Internet",
        note: "Diese opulent verzierte, funkelnde venezianische Maske liegt geheimnisvoll auf einem luxuriösen, lila Samtkissen. Sie ist das zentrale, verunsichernde Symbol für Täuschung, verborgene Begierden und Doppelleben aus Stanley Kubricks finalem Meisterwerk 'Eyes Wide Shut'. Das Bild fesselt den Betrachter durch sein tiefes, stimmungsvolles Farbspiel und seine mystische Aura.",
        imageUrl: "/images/collections/images/31.jpg"
    },
    {
        title: "La Main Revolver (Vogue-Fotografie)",
        creator: "Guy Bourdin",
        year: 1974,
        source: "Vogue Paris / Modearchiv",
        discovered_by: "Buch",
        note: "Diese provokante Farbfotografie des französischen Künstlers Guy Bourdin zeigt eine Frauenhand mit perfekt rot lackierten Fingernägeln, die einen silbernen Revolver hält. Die Waffe ragt bedrohlich durch einen schweren, tiefroten Vorhang aus edlem Samt. Bourdin bricht hier auf geniale Weise die Grenzen zwischen High-Fashion-Ästhetik, Surrealismus und einer fast filmischen Kriminalerzählung auf.",
        imageUrl: "/images/collections/images/32.jpg"
    }
];

const photographs = [
    {
        photographer: "Henri Cartier-Bresson",
        title: "Behind the Gare Saint-Lazare",
        location: "Paris",
        source: "Magnum Photos",
        note: "Die Fotografie hält einen konkreten Augenblick fest und verwandelt ihn zugleich in eine offene Geschichte. Besonders stark ist das Verhältnis zwischen beobachteter Realität, Komposition und dem, was außerhalb des Bildrandes nur angedeutet wird.",
        imageUrl: "/images/collections/photos/1.webp",
    },
    {
        photographer: "Henri Cartier-Bresson",
        title: "Rue Mouffetard",
        location: "Paris",
        source: "Magnum Photos",
        note: "Das Bild wirkt zunächst spontan, ist aber formal sehr präzise aufgebaut. Licht, Abstand und Blickrichtung schaffen eine Spannung, durch die der dokumentarische Moment zugleich persönlich und zeitlos erscheint.",
        imageUrl: "/images/collections/photos/2.webp",
    },
    {
        photographer: "Henri Cartier-Bresson",
        title: "Hyères, France",
        location: "Hyères",
        source: "Magnum Photos",
        note: "Die Fotografie hält einen konkreten Augenblick fest und verwandelt ihn zugleich in eine offene Geschichte. Besonders stark ist das Verhältnis zwischen beobachteter Realität, Komposition und dem, was außerhalb des Bildrandes nur angedeutet wird.",
        imageUrl: "/images/collections/photos/3.jpeg",
    },
    {
        photographer: "Henri Cartier-Bresson",
        title: "Seville, Spain",
        location: "Sevilla",
        source: "Magnum Photos",
        note: "Das Bild wirkt zunächst spontan, ist aber formal sehr präzise aufgebaut. Licht, Abstand und Blickrichtung schaffen eine Spannung, durch die der dokumentarische Moment zugleich persönlich und zeitlos erscheint.",
        imageUrl: "/images/collections/photos/4.webp",
    },
    {
        photographer: "Sally Mann",
        title: "Candy Cigarette",
        location: "Lexington, Virginia",
        source: "Sally Mann / Fotobuch",
        note: "Die Fotografie hält einen konkreten Augenblick fest und verwandelt ihn zugleich in eine offene Geschichte. Besonders stark ist das Verhältnis zwischen beobachteter Realität, Komposition und dem, was außerhalb des Bildrandes nur angedeutet wird.",
        imageUrl: "/images/collections/photos/5.jpg",
    },
    {
        photographer: "Sally Mann",
        title: "Immediate Family",
        location: "Virginia, USA",
        source: "Sally Mann / Fotobuch",
        note: "Das Bild wirkt zunächst spontan, ist aber formal sehr präzise aufgebaut. Licht, Abstand und Blickrichtung schaffen eine Spannung, durch die der dokumentarische Moment zugleich persönlich und zeitlos erscheint.",
        imageUrl: "/images/collections/photos/6.jpeg",
    },
    {
        photographer: "Laura Makabresku",
        title: "Untitled",
        location: "Polen",
        source: "Künstlerisches Archiv",
        note: "Die Fotografie hält einen konkreten Augenblick fest und verwandelt ihn zugleich in eine offene Geschichte. Besonders stark ist das Verhältnis zwischen beobachteter Realität, Komposition und dem, was außerhalb des Bildrandes nur angedeutet wird.",
        imageUrl: "/images/collections/photos/1.webp",
    },
    {
        photographer: "Laura Makabresku",
        title: "Untitled II",
        location: "Polen",
        source: "Künstlerisches Archiv",
        note: "Das Bild wirkt zunächst spontan, ist aber formal sehr präzise aufgebaut. Licht, Abstand und Blickrichtung schaffen eine Spannung, durch die der dokumentarische Moment zugleich persönlich und zeitlos erscheint.",
        imageUrl: "/images/collections/photos/8.jpeg",
    },
    {
        photographer: "Alexey Titarenko",
        title: "City of Shadows",
        location: "St. Petersburg",
        source: "Fotobuch",
        note: "Die Fotografie hält einen konkreten Augenblick fest und verwandelt ihn zugleich in eine offene Geschichte. Besonders stark ist das Verhältnis zwischen beobachteter Realität, Komposition und dem, was außerhalb des Bildrandes nur angedeutet wird.",
        imageUrl: "/images/collections/photos/9.webp",
    },
    {
        photographer: "Alexey Titarenko",
        title: "The Invisible",
        location: "St. Petersburg",
        source: "Fotobuch",
        note: "Das Bild wirkt zunächst spontan, ist aber formal sehr präzise aufgebaut. Licht, Abstand und Blickrichtung schaffen eine Spannung, durch die der dokumentarische Moment zugleich persönlich und zeitlos erscheint.",
        imageUrl: "/images/collections/photos/10.jpeg",
    },
    {
        photographer: "Constantine Manos",
        title: "American Color",
        location: "USA",
        source: "Magnum Photos",
        note: "Die Fotografie hält einen konkreten Augenblick fest und verwandelt ihn zugleich in eine offene Geschichte. Besonders stark ist das Verhältnis zwischen beobachteter Realität, Komposition und dem, was außerhalb des Bildrandes nur angedeutet wird.",
        imageUrl: "/images/collections/photos/11.jpg",
    },
    {
        photographer: "Constantine Manos",
        title: "Greek Portfolio",
        location: "Griechenland",
        source: "Magnum Photos",
        note: "Das Bild wirkt zunächst spontan, ist aber formal sehr präzise aufgebaut. Licht, Abstand und Blickrichtung schaffen eine Spannung, durch die der dokumentarische Moment zugleich persönlich und zeitlos erscheint.",
        imageUrl: "/images/collections/photos/12.jpg",
    },
    {
        photographer: "Sebastião Salgado",
        title: "Workers",
        location: "Brasilien",
        source: "Magnum Photos",
        note: "Die Fotografie hält einen konkreten Augenblick fest und verwandelt ihn zugleich in eine offene Geschichte. Besonders stark ist das Verhältnis zwischen beobachteter Realität, Komposition und dem, was außerhalb des Bildrandes nur angedeutet wird.",
        imageUrl: "/images/collections/photos/13.jpeg",
    },
    {
        photographer: "Sebastião Salgado",
        title: "Genesis",
        location: "Amazonien",
        source: "Fotobuch",
        note: "Das Bild wirkt zunächst spontan, ist aber formal sehr präzise aufgebaut. Licht, Abstand und Blickrichtung schaffen eine Spannung, durch die der dokumentarische Moment zugleich persönlich und zeitlos erscheint.",
        imageUrl: "/images/collections/photos/14.jpg",
    },
    {
        photographer: "Elliott Erwitt",
        title: "California Kiss",
        location: "Kalifornien",
        source: "Magnum Photos",
        note: "Die Fotografie hält einen konkreten Augenblick fest und verwandelt ihn zugleich in eine offene Geschichte. Besonders stark ist das Verhältnis zwischen beobachteter Realität, Komposition und dem, was außerhalb des Bildrandes nur angedeutet wird.",
        imageUrl: "/images/collections/photos/15.webp",
    },
    {
        photographer: "Robert Capa",
        title: "The Falling Soldier",
        location: "Spanien",
        source: "Magnum Photos",
        note: "Das Bild wirkt zunächst spontan, ist aber formal sehr präzise aufgebaut. Licht, Abstand und Blickrichtung schaffen eine Spannung, durch die der dokumentarische Moment zugleich persönlich und zeitlos erscheint.",
        imageUrl: "/images/collections/photos/16.jpg",
    },
    {
        photographer: "Robert Frank",
        title: "Trolley — New Orleans",
        location: "New Orleans",
        source: "Fotobuch",
        note: "Die Fotografie hält einen konkreten Augenblick fest und verwandelt ihn zugleich in eine offene Geschichte. Besonders stark ist das Verhältnis zwischen beobachteter Realität, Komposition und dem, was außerhalb des Bildrandes nur angedeutet wird.",
        imageUrl: "/images/collections/photos/17.jpeg",
    },
    {
        photographer: "Josef Koudelka",
        title: "Gypsies",
        location: "Tschechoslowakei",
        source: "Magnum Photos",
        note: "Das Bild wirkt zunächst spontan, ist aber formal sehr präzise aufgebaut. Licht, Abstand und Blickrichtung schaffen eine Spannung, durch die der dokumentarische Moment zugleich persönlich und zeitlos erscheint.",
        imageUrl: "/images/collections/photos/18.jpg",
    },
    {
        photographer: "Eve Arnold",
        title: "Marilyn Monroe",
        location: "USA",
        source: "Magnum Photos",
        note: "Die Fotografie hält einen konkreten Augenblick fest und verwandelt ihn zugleich in eine offene Geschichte. Besonders stark ist das Verhältnis zwischen beobachteter Realität, Komposition und dem, was außerhalb des Bildrandes nur angedeutet wird.",
        imageUrl: "/images/collections/photos/19.jpg",
    },
    {
        photographer: "Bruce Davidson",
        title: "East 100th Street",
        location: "New York",
        source: "Magnum Photos",
        note: "Das Bild wirkt zunächst spontan, ist aber formal sehr präzise aufgebaut. Licht, Abstand und Blickrichtung schaffen eine Spannung, durch die der dokumentarische Moment zugleich persönlich und zeitlos erscheint.",
        imageUrl: "/images/collections/photos/20.jpeg",
    },
    {
        photographer: "Inge Morath",
        title: "Spain",
        location: "Spanien",
        source: "Magnum Photos",
        note: "Die Fotografie hält einen konkreten Augenblick fest und verwandelt ihn zugleich in eine offene Geschichte. Besonders stark ist das Verhältnis zwischen beobachteter Realität, Komposition und dem, was außerhalb des Bildrandes nur angedeutet wird.",
        imageUrl: "/images/collections/photos/21.jpg",
    },
];

const ideas = [
    {
        title: "Archiv der verlorenen Dinge",
        category: "Projekt",
        inspiration:
            "Museen, Flohmärkte, alte Fotografien und persönliche Erinnerungen.",
        description:
            "Ein visuelles Archiv von Dingen, die Menschen einmal besessen, geliebt oder verloren haben. Jedes Objekt bekommt seine eigene kleine Geschichte.",
        next_step:
            "Die ersten 20 Objekte sammeln und ihre Geschichten notieren.",
    },
    {
        title: "Ein Museum für persönliche Erinnerungen",
        category: "Konzept",
        inspiration:
            "DFF, Städel und persönliche Sammlungen.",
        description:
            "Ein imaginäres Museum, in dem keine berühmten Kunstwerke ausgestellt werden, sondern Dinge, Bilder, Musik und Sätze, die für eine einzelne Person wichtig geworden sind.",
        next_step: "Die ersten zehn Räume definieren.",
    },
    {
        title: "Atlas persönlicher Orte",
        category: "Projekt",
        inspiration: "Stadtpläne, Fotografien und Erinnerungen an wiederkehrende Wege.",
        description: "Eine Sammlung von Orten, die nicht wegen ihrer touristischen Bedeutung wichtig sind, sondern wegen persönlicher Begegnungen und kleiner Beobachtungen. Jeder Ort erhält ein Bild, eine kurze Notiz und eine zeitliche Spur.",
        next_step: "Zehn Orte auswählen und die erste Karte anlegen.",
    },
    {
        title: "Archiv des künstlichen Lichts",
        category: "Fotografie",
        inspiration: "Nachtfotografie, Kino und beleuchtete Fenster in Städten.",
        description: "Ein visuelles Projekt über Lichtquellen, die nachts Räume definieren und Menschen sichtbar oder unsichtbar machen. Straßenlaternen, Neon, Kinos und Schaufenster werden als kleine Bühnen betrachtet.",
        next_step: "Eine erste Serie mit 30 Nachtaufnahmen planen.",
    },
    {
        title: "Bibliothek der wiedergefundenen Sätze",
        category: "Konzept",
        inspiration: "Notizbücher, gelesene Bücher und zufällig aufgeschnappte Gespräche.",
        description: "Ein digitales Archiv für Sätze, die zunächst verloren gehen und später in einem anderen Zusammenhang wieder auftauchen. Die Sammlung verbindet Textfragmente mit Fundort, Datum und persönlicher Assoziation.",
        next_step: "Ein einheitliches Format für die ersten 50 Einträge entwickeln.",
    },
];

const quotes = [
    {
        title: "Vor allem: Belüge dich selbst nicht.",
        author: "Fjodor Dostojewski",
        source: "Die Brüder Karamasow",
        year: 1880,
        context:
            "Über Ehrlichkeit mit sich selbst und moralische Verantwortung.",
    },
    {
        title:
            "Schmerz und Leiden sind für einen großen Geist und ein tiefes Herz immer unvermeidlich.",
        author: "Fjodor Dostojewski",
        source: "Schuld und Sühne",
        year: 1866,
        context: "Über Intelligenz, Sensibilität und Leiden.",
    },
    {
        title: "Ich bin ein kranker Mensch.",
        author: "Fjodor Dostojewski",
        source: "Aufzeichnungen aus dem Kellerloch",
        year: 1864,
        context:
            "Der Beginn eines radikalen inneren Monologs.",
    },
    {
        title:
            "Auf einen Mörder kann man sich immer verlassen, wenn es um eine kunstvolle Prosa geht.",
        author: "Vladimir Nabokov",
        source: "Lolita",
        year: 1955,
        context:
            "Über Sprache, Stil und die Selbstinszenierung des Erzählers.",
    },
    {
        title:
            "Wir liegen alle in der Gosse, aber einige von uns schauen zu den Sternen.",
        author: "Oscar Wilde",
        source: "Lady Windermere's Fan",
        year: 1892,
        context: "Über Perspektive und Hoffnung.",
    },
    {
        title:
            "Ich öffnete mich der sanften Gleichgültigkeit des Universums.",
        author: "Albert Camus",
        source: "Der Fremde",
        year: 1942,
        context: "Die Akzeptanz der Absurdität.",
    },
    {
        title:
            "Eine Frau braucht Geld und ein eigenes Zimmer, wenn sie Belletristik schreiben will.",
        author: "Virginia Woolf",
        source: "Ein Zimmer für sich allein",
        year: 1929,
        context:
            "Unabhängigkeit als Voraussetzung für kreatives Arbeiten.",
    },
    {
        title: "Jemand musste Josef K. verleumdet haben.",
        author: "Franz Kafka",
        source: "Der Prozess",
        year: 1925,
        context:
            "Der Beginn eines absurden bürokratischen Albtraums.",
    },
    {
        title: "Weisheit kann man nicht vermitteln.",
        author: "Hermann Hesse",
        source: "Siddhartha",
        year: 1922,
        context:
            "Der Unterschied zwischen Wissen und gelebter Erfahrung.",
    },
    {
        title: "Der Große Bruder beobachtet dich.",
        author: "George Orwell",
        source: "1984",
        year: 1949,
        context: "Überwachung und politische Kontrolle.",
    },
    {
        title:
            "Alle Tiere sind gleich, aber manche Tiere sind gleicher als andere.",
        author: "George Orwell",
        source: "Animal Farm",
        year: 1945,
        context: "Die Korruption politischer Sprache.",
    },
    {
        title:
            "Die eigentliche Geschichte der Menschheit beginnt mit der kognitiven Revolution.",
        author: "Yuval Noah Harari",
        source: "Sapiens",
        year: 2011,
        context:
            "Hararis Idee von der kognitiven Revolution.",
    },
    {
        title:
            "Ich habe kein Geld, keine Mittel und keine Hoffnung.",
        author: "Henry Miller",
        source: "Tropic of Cancer",
        year: 1934,
        context:
            "Millers paradoxe Beziehung zu Armut und Freiheit.",
    },
];

export { books, vinyl, tracks, magazines, artworks, museums, galleries, images, photographs, ideas, quotes };
