
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Session: 'Session',
  Account: 'Account',
  Verification: 'Verification',
  Book: 'Book',
  Music: 'Music',
  Magazine: 'Magazine',
  Artwork: 'Artwork',
  Museum: 'Museum',
  Gallery: 'Gallery',
  Image: 'Image',
  Photograph: 'Photograph',
  Idea: 'Idea',
  Quote: 'Quote',
  NewCollection: 'NewCollection'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  createdAt: 'createdAt',
  emailVerified: 'emailVerified',
  image: 'image',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const SessionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  token: 'token',
  updatedAt: 'updatedAt',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent'
} as const

export type SessionScalarFieldEnum = (typeof SessionScalarFieldEnum)[keyof typeof SessionScalarFieldEnum]


export const AccountScalarFieldEnum = {
  id: 'id',
  accountId: 'accountId',
  providerId: 'providerId',
  issuer: 'issuer',
  userId: 'userId',
  accessToken: 'accessToken',
  refreshToken: 'refreshToken',
  idToken: 'idToken',
  accessTokenExpiresAt: 'accessTokenExpiresAt',
  refreshTokenExpiresAt: 'refreshTokenExpiresAt',
  scope: 'scope',
  password: 'password',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AccountScalarFieldEnum = (typeof AccountScalarFieldEnum)[keyof typeof AccountScalarFieldEnum]


export const VerificationScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier',
  value: 'value',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type VerificationScalarFieldEnum = (typeof VerificationScalarFieldEnum)[keyof typeof VerificationScalarFieldEnum]


export const BookScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  title: 'title',
  author: 'author',
  year: 'year',
  pages: 'pages',
  discovered_by: 'discovered_by',
  note: 'note',
  bestQuote: 'bestQuote',
  imageUrl: 'imageUrl',
  createdAt: 'createdAt'
} as const

export type BookScalarFieldEnum = (typeof BookScalarFieldEnum)[keyof typeof BookScalarFieldEnum]


export const MusicScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  format: 'format',
  title: 'title',
  author: 'author',
  year: 'year',
  discovered_by: 'discovered_by',
  note: 'note',
  bestQuote: 'bestQuote',
  imageUrl: 'imageUrl',
  createdAt: 'createdAt'
} as const

export type MusicScalarFieldEnum = (typeof MusicScalarFieldEnum)[keyof typeof MusicScalarFieldEnum]


export const MagazineScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  title: 'title',
  issue: 'issue',
  date: 'date',
  discovered_by: 'discovered_by',
  note: 'note',
  bestQuote: 'bestQuote',
  imageUrl: 'imageUrl',
  createdAt: 'createdAt'
} as const

export type MagazineScalarFieldEnum = (typeof MagazineScalarFieldEnum)[keyof typeof MagazineScalarFieldEnum]


export const ArtworkScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  format: 'format',
  title: 'title',
  author: 'author',
  year: 'year',
  technique: 'technique',
  dimensions: 'dimensions',
  discovered_by: 'discovered_by',
  note: 'note',
  imageUrl: 'imageUrl',
  createdAt: 'createdAt'
} as const

export type ArtworkScalarFieldEnum = (typeof ArtworkScalarFieldEnum)[keyof typeof ArtworkScalarFieldEnum]


export const MuseumScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  title: 'title',
  city: 'city',
  exhibition: 'exhibition',
  date: 'date',
  discovered_by: 'discovered_by',
  note: 'note',
  imageUrl: 'imageUrl',
  createdAt: 'createdAt'
} as const

export type MuseumScalarFieldEnum = (typeof MuseumScalarFieldEnum)[keyof typeof MuseumScalarFieldEnum]


export const GalleryScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  title: 'title',
  city: 'city',
  artist: 'artist',
  exhibition: 'exhibition',
  date: 'date',
  note: 'note',
  imageUrl: 'imageUrl',
  createdAt: 'createdAt'
} as const

export type GalleryScalarFieldEnum = (typeof GalleryScalarFieldEnum)[keyof typeof GalleryScalarFieldEnum]


export const ImageScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  title: 'title',
  creator: 'creator',
  year: 'year',
  source: 'source',
  discovered_by: 'discovered_by',
  note: 'note',
  imageUrl: 'imageUrl',
  createdAt: 'createdAt'
} as const

export type ImageScalarFieldEnum = (typeof ImageScalarFieldEnum)[keyof typeof ImageScalarFieldEnum]


export const PhotographScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  photographer: 'photographer',
  title: 'title',
  location: 'location',
  source: 'source',
  note: 'note',
  imageUrl: 'imageUrl',
  createdAt: 'createdAt'
} as const

export type PhotographScalarFieldEnum = (typeof PhotographScalarFieldEnum)[keyof typeof PhotographScalarFieldEnum]


export const IdeaScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  title: 'title',
  category: 'category',
  inspiration: 'inspiration',
  description: 'description',
  next_step: 'next_step',
  imageUrl: 'imageUrl',
  createdAt: 'createdAt'
} as const

export type IdeaScalarFieldEnum = (typeof IdeaScalarFieldEnum)[keyof typeof IdeaScalarFieldEnum]


export const QuoteScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  title: 'title',
  author: 'author',
  source: 'source',
  year: 'year',
  context: 'context',
  imageUrl: 'imageUrl',
  createdAt: 'createdAt'
} as const

export type QuoteScalarFieldEnum = (typeof QuoteScalarFieldEnum)[keyof typeof QuoteScalarFieldEnum]


export const NewCollectionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  title: 'title',
  description: 'description',
  reason: 'reason',
  imageUrl: 'imageUrl',
  createdAt: 'createdAt'
} as const

export type NewCollectionScalarFieldEnum = (typeof NewCollectionScalarFieldEnum)[keyof typeof NewCollectionScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

